### ISSUE TITLE
Zpool add problem

### ISSUE THREAD

**Issue by RicardoLorenzo** [zfsonlinux/zfs#1028]
If i use two type of disks (/dev/sdb is SAS RAID, and /dev/sdc, /dev/sdd USB disks). The problem is about efi_write() method.

  # zpool create -f Pool1 /dev/sdb
  # zpool add -f Pool1 /dev/sdc
cannot label 'sdc': try using parted(8) and then provide a specific slice: -4

But, if i use:

  # zpool create -f Pool1 /dev/sdb /dev/sdc

Everything is fine!

And:

  # zpool create -f Pool1 /dev/sdc
  # zpool add -f Pool1 /dev/sdd

Everything is fine again!

**Comment by behlendorf** [comment]
Closing as stale.  If in fact this is still and issue we can reopen it.

**Comment by gmoseley** [comment]
@behlendorf

Same issue happening today:

> root@hostname:~# zpool create -f -o ashift=12 Raidz2-0 raidz2 /dev/sda /dev/sdc /dev/sde /dev/sdf /dev/sdg
> cannot label 'sda': try using parted(8) and then provide a specific slice: -2


> root@hostname:~# zpool labelclear /dev/sda
> failed to read label from /dev/sda
> root@hostname:~# zpool labelclear /dev/sdc
> failed to read label from /dev/sdc
> root@hostname:~# zpool labelclear /dev/sde
> failed to read label from /dev/sde
> root@hostname:~# zpool labelclear /dev/sdf
> failed to read label from /dev/sdf
> root@hostname:~# zpool labelclear /dev/sdg
> failed to read label from /dev/sdg


> NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
> sda       8:0    0   5.5T  0 disk 
> sdb       8:16   0 931.5G  0 disk 
> ├─sdb1    8:17   0  1007K  0 part 
> ├─sdb2    8:18   0     1G  0 part 
> └─sdb3    8:19   0   930G  0 part 
> sdc       8:32   0   5.5T  0 disk 
> sdd       8:48   0 953.9G  0 disk 
> ├─sdd1    8:49   0  1007K  0 part 
> ├─sdd2    8:50   0     1G  0 part 
> └─sdd3    8:51   0   930G  0 part 
> sde       8:64   0   5.5T  0 disk 
> sdf       8:80   0   5.5T  0 disk 
> sdg       8:96   0   5.5T  0 disk 
> sdh       8:112  0   5.5T  0 disk 
> sdi       8:128  0   5.5T  0 disk 
> sdj       8:144  0   5.5T  0 disk 
> sdk       8:160  0   5.5T  0 disk 
> sdl       8:176  0   5.5T  0 disk 
> sdm       8:192  1  14.4G  0 disk 
> ├─sdm1    8:193  1   224K  0 part 
> ├─sdm2    8:194  1   2.8M  0 part 
> ├─sdm3    8:195  1     1G  0 part 
> └─sdm4    8:196  1   300K  0 part 
> nvme0n1 259:0    0 465.8G  0 disk 

I found this thread after trying to build a RAIDZ2 in PVE with the following configuration getting the following error:

<img width="608" alt="image" src="https://github.com/openzfs/zfs/assets/38480687/b3a9195b-c8fe-415d-ae2a-697ded47b274">


command '/sbin/zpool create -o 'ashift=12' RAIDZ2-0 raidz2 /dev/disk/by-id/scsi-35000cca24d346e7c /dev/disk/by-id/scsi-35000cca24d358c10 /dev/disk/by-id/scsi-35000cca24d357604 /dev/disk/by-id/scsi-35000cca24d2f5030 /dev/disk/by-id/scsi-35000cca24d36fad0' failed: exit code 1

<img width="457" alt="image" src="https://github.com/openzfs/zfs/assets/38480687/9b889641-a75d-4e60-a989-5bf13f177295">

pve-manager/7.4-3/9002ab8a (running kernel: 5.15.102-1-pve)

<html>
<body>
<div ccp_infra_version='3' ccp_infra_timestamp='1693432469737' ccp_infra_user_hash='1565411791' ccp_infra_copy_id='a793f124-0f5a-43ca-99ed-a33d9f4a6c90' data-ccp-timestamp='1693432469737'><html><head><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"><style>table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
</style></head><body link="#0563C1" vlink="#954F72">

SuperMicro 6028 | Chassis | 6028U-TR4T+ 2U SuperServer
-- | -- | --
  | Board | Super X10DRU-i+
  | HBA | aoc-s3008l-l8e1-N122
  | Backplane | BPN-SAS3-826EL1

</body></html></div>
</body>
</html>

I'm going to keep poking around on this for a couple days so if you need anything or want a test env let me know. Otherwise I'll update here with any solutions I find
