### ISSUE TITLE
.zfs/snapshots only work on 64-bit systems

### ISSUE THREAD

**Issue by muskii** [zfsonlinux/zfs#2002]
I'm unable to access the .zfs directory on my fresh ZoL install.

ZoL version is 0.6.2
Linux version is 3.11
The system is a raspberrypi with a test pool (file vdevs) and a couple of snapshots

Setting snapdir=visible does not help.
Snaphot can still be cloned and then accessed.

I (cross-)compiled everything from source so i must have disabled/skipped something.
I'm a newbie so i don't really know where to look to find the cause.

**Comment by TrevorScheitrum** [comment]
Sorry to revive a 1.5 year old thread (!) but could one of you point me to how to cross compile ZOL for raspberry pi?  I tried the compiling instructions for ZFS and SPL on the 1rst Gen Raspberry pi B+ 
here:
https://github.com/zfsonlinux/spl

and also tried compiling ZFS from here:
https://github.com/zfsonlinux/zfs

its been a month or so since my last try, but i got stuck fixing error message after error message finally got it to compile and install but using ANY ZFS command fails to print any output to the terminal window.  For example running "sudo zpool status" doesn't print anything.

I realize this is an issue thread and not a help forum, but I figured I'd ask since i spent a lot of time trying to get this to work, and very few people on the internet seem to have it working on a raspberry pi.

**Comment by behlendorf** [comment]
@TrevorScheitrum the latest stable release and master code should just work.  In fact, the buildbot regularly tests each build on a rpi2, take a look at the [arm build slaves](http://build.zfsonlinux.org/buildslaves/Debian-8-arm-buildslave1).  Just make sure you have the needed kernel devel headers installed (which I know can be a pain for the rpi) and build as normal.

**Comment by TrevorScheitrum** [comment]
those seem to be for raspberry pi 2 which is ARMv7, the original raspberry pi (and A/B/B+ Variants) seem to use ARMv6 https://en.wikipedia.org/wiki/Raspberry_Pi does ZFS not work with ARMv6?  is the answer to just buy the newer generation chip that includes ARMv7?

**Comment by behlendorf** [comment]
@TrevorScheitrum it should work with ARMv6 as well without modification.

**Comment by TrevorScheitrum** [comment]
@behlendorf awesome, i'll try it this week, thanks!

**Comment by dschwartz783** [comment]
Fun fact: The kernel headers are regularly posted here, simultaneously with RPI kernel releases: https://www.niksula.hut.fi/~mhiienka/Rpi/linux-headers-rpi/
Just make sure you get the v7 version for the RPi2 or 3!
Download the headers to the pi and install with dpkg. Done. :)

**Comment by TrevorScheitrum** [comment]
@behlendorf really sorry to keep bringing this up, if there's a better method of asking questions, please don't hesitate to point me in that direction. 

I tried many times and failed to get ZFS running on my raspberry pi 1.  I bought an odroid-c2 once i heard that ZFS was going to be built into Ubuntu 16.04 and that the C2 will run the ARM version of Ubuntu 16.04.  From what I can see ZFS support doesn't seem to be included in the ARM version of 16.04 (at least the odroid version doesn't have it) I've tried again multiple times to compile SPL and ZFS from source and get it running and have hit multiple brick walls with my approaches.  Do you have any suggestions or resources i could look at to get ZFS running on the ARM64 platform?  I have a couple neat projects I'd like to work on with ZFS on ARM, but pretty frustrated i can't get it working by myself, and there's not a lot of details for getting this stuff running with ARM.

I tried cloning and building the repos from here:
https://github.com/zfsonlinux/spl
https://github.com/zfsonlinux/zfs

tried running these on commands on each source repo according to the github readme's
sudo ./autogen.sh
sudo ./configure
sudo  make pkg
and got this error which i'm confused about because i have the header files for my kernel installed:
+ echo kmodtool error: Don't know how to handle 3.14.29-56 -- /lib/modules/3.14.29-56/build/Makefile not found

rather than do make package, i also tried to just do:
sudo make; sudo make install
that completes and installs, but says it can't find the ZFS modules when i do
sudo modprobe zfs

i tried taking another approach and read through the custom build docs and used alien to try to install it
https://github.com/zfsonlinux/zfs/wiki/Custom-Packages
this results in the same error when doing the make pkg
make pkg-utils pkg-kmod


And that's where i'm at.  Any help would be greatly appreciated, thanks!

**Comment by behlendorf** [comment]
@TrevorScheitrum I believe @morrone was able to build on the odroid-c2.  It's my understanding that all he needed to do was point the spl/zfs builds at the correct Linux headers and objects using `--with-linux` and `--with-linux-obj`.  In fact, I was hoping to add an odroid-c2 to the automated buildbot as am aarch64 builder.

**Comment by morrone** [comment]
>  I bought an odroid-c2 once i heard that ZFS was going to be built into Ubuntu 16.04 and that the C2 will run the ARM version of Ubuntu 16.04. From what I can see ZFS support doesn't seem to be included in the ARM version of 16.04 (at least the odroid version doesn't have it)

While most of the Odriod C2 OS is ubuntu 16.04, the Linux kernel included is not.  It is a much older 3.14 kernel patched specifically for the C2 hardware.

I was able to _compile_ SPL and ZFS, if I remember correctly, but packing was a lost cause.  The zfsonlinux project does not really provide dpkg style packaging.  It is relying on the "alien" command to convert rpm packages to dpkg packages.  That tends to only work for the most simple of package types.  The alien approach hasn't worked for zfs on Ubuntu system for me anywhere that I have tried it.

So you can probably get it to compile with just "make", but yes, make "pkg-kmod" is not going to work on Ubuntu.

**Comment by TrevorScheitrum** [comment]
sudo make; sudo make install worked, thank you.  I must have done a kernel upgrade or something when i tried this previously, as i definitely got an error message before.

I now officially have ZFS working on an odroid-c2, thank you all for your help!
