### ISSUE TITLE
Direct IO

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#224]
The direct IO handlers have not yet been implemented. Supporting direct IO would have been a problem a few years back because of how ZFS copies everything in to the ARC cache. However, recently ZFS started supporting a zero-copy interface which we may be able to leverage for direct IO support.

**Comment by maci0** [comment]
the solution in illumos kvm is rather crude too:
https://github.com/joyent/illumos-kvm-cmd/blob/master/block/raw-posix.c#L97

**Comment by pavel-odintsov** [comment]
It's rather better than "silent ignore O_DIRECT".

**Comment by behlendorf** [comment]
After investigating what it will take to support this I'm bumping this functionality from the 0.6.4 tag.  To add this functionality we must implement the `address_space_operations.direct_IO` callback for the ZPL.  This will allow us to pin in memory the pages for IO which have been passed by the application.  IO can then be performed directly to those pages.  This will require us to add an additional interface to the DMU which accepts an `struct iov_iter`.  While this work isn't particularly difficult, it's also not critical functionality and we don't want it to hold up the next release.

**Comment by ryao** [comment]
@behlendorf I spotted the following article that compares ZFS to ext4's data=journal configuration:

https://www.percona.com/blog/2014/05/23/improve-innodb-performance-write-bound-loads/

Of particular interest is that setting `data=journal` on ext4 makes it transactional like ZFS and initially made it unable to support `O_DIRECT` as well. `O_DIRECT` support was later implemented by mapping `O_DIRECT` to `O_DSYNC`. If/when we add `O_DIRECT` support, one option would be to implement the same mapping.

**Comment by ryao** [comment]
@behlendorf We can not just pin the user pages. We also need to mark them CoW so that userland cannot modify them as they are being read. Otherwise, we risk writing incorrect checksums. In the case of compression, userland modification of the pages while the compression algorithm is run would result in undefined behavior and might pose a security risk.

**Comment by Bronek** [comment]
@ryao thanks for the writeup. I use ZFS zvols as a backing storage for qemu, and am also vaguely familiar with how databases perform IO. Mapping direct_IO to AIO is definitely good first step but it would be great if both 2. and 3. received (eventually) attention as well.

Regarding 2. COW seems definitely like a good direction. I would also expect lower memory utilisation and possibly other performance gains from O_DIRECT if (and only if) compression is not enabled.
Regarding 3. that's interesting one. One can rather trivially (although not cheaply) increase IO subsystem performance by attaching nvme PCIe backed SLOG device; it would be great if ZIL could be used (if configured so - an extra option would be needed) as a primary backing storage mapped to O_DIRECT rather than indirect logging. This would help to preserve the benefits of fast SLOG device i.e. very low latency of synchronous writes; while at the same time guaranteeing data safety and low memory utilisation (primary goals of O_DIRECT in scenarios I am familar with).

**Comment by nigoroll** [comment]
As a preliminary yet generic relief I have written an interposer to either map O_DIRECT to O_DSYNC or just ignore it. As most of the source infrastructure required was already there, I integrated it into https://code.uplex.de/liblongpath - ignoring, for the time being, that the main purpose of the liblongpath project was quite different.
The relevant commit is https://code.uplex.de/liblongpath/liblongpath/commit/2e46a921ce2b6b1caa56d39cbd58be85c5988bd0
The commit message contains basic usage info, I have not (yet) added any other documentation for this feature.

**Comment by ryao** [comment]
@nigoroll Most Linux filesystem drivers, including ZoL, treat O_SYNC and O_DSYNC the same, sothat will not make much difference here.

You can get the indirect logging on all I/Os (O_DIRECT or not) that I mentioned by setting logbias=throughput on the dataset..

**Comment by nigoroll** [comment]
@ryao, I fail to understand how your comment relates to the interposer I have written. Its purpose is to provide relief where `O_DIRECT` cannot be avoided and `open()` calls returning with `EINVAL` break applications (which may even be closed source). Basically this implements what @pruiz suggested, but on the level of an interposer library.

**Comment by ryao** [comment]
@nigoroll I was thinking of this from the perspective of performance, where software using O_DIRECT almost always uses O_SYNC, so it does not improve things over the patch to ZoL to ignore O_DIRECT by mapping it to AIO. It makes more sense when thinking about software compatibility.

**Comment by azeemism** [comment]
@ryao, should I be removing `innodb_flush_method` variable for `/etc/mysql/my.cnf`if I find it there? or pick a different value other than `innodb_flush_method=O_DIRECT`?

Other valid values:
```
fdatasync
O_DSYNC
O_DIRECT_NO_FSYNC
```

What would be best?

**Comment by ryao** [comment]
@azeemism `fdatasync` is the best option for MariaDB on ZFS right now. O_DSYNC is the equivalent of calling `fdatasync` after each and every write operation while neither O_Direct nor O_DIRECT_NO_FSYNC should work on ZFS unless you patch it to implement the `->directIO` VFS operation. Patching ZFS to add it would have no benefit in production over using `fdatasync` at best and at worse, would render MariaDB crash-unsafe.

**Comment by MarkGavalda** [comment]
MariaDB 10.1 throws "[ERROR] InnoDB: Unrecognized value fdatasync for innodb_flush_method" so no more fdatasync. Interestingly the documentation still mentions it: https://mariadb.com/kb/en/mariadb/xtradbinnodb-server-system-variables/#innodb_flush_method

**Comment by rlaager** [comment]
@ryao How much work would it take (on top of your commit earlier) to make O_DIRECT imply primarycache=metadata semantics?

**Comment by FlorianHeigl** [comment]
Anyone can comment on that first post in this issue?
That looked into the double buffering matter and hinted it might not be a problem anymore after 2011? Like maci0 said, the other ways seem really crude.
And I'd rather have it disable like it does now than map into fdatasync.

Application: "please don't buffer this at all, I'm trying to optimize here while keeping data safe"
FS: "Sure, I'll not buffer this at all. I'll not slow you down and I'll not lie to you about when the data is on disk"
FS turns around and says "yeah, we'll just flush when application does flushes, heh, it can't be worse than ext3, right?!"

**Comment by nigoroll** [comment]
@FlorianHeigl many comments here related to the initial note, just take the time to read them. Things are  not that easy, if you want to understand why, I'd recommend  @ryao s comment as of 23 Jul 2015

**Comment by mcr-ksh** [comment]
+1. libvirt wont run with those flags:

    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='none' io='native'/>

**Comment by MyPod** [comment]
@mcr-ksh although that combination of cache and io is optimal, you can still get libvirt to use volumes hosted on zfs by either not defining cache and io, or by selecting io='threads' and an appropriate cache policy

**Comment by lnxbil** [comment]
It would be really great if we could get this simple sounding fix (create a shim to `AIO`) of @ryao:

> Given the lack of standardization and ZFS' heritage, one solution to
provide compatibility with userland processes that expect DirectIO is to
treat DirectIO as a hint that we ignore. This can be done trivially by
implementing a shim that maps aops->direct_IO to AIO. There is also
already code in ZoL for bypassing the page cache when O_DIRECT is
specified, but it has been inert until now.

If this is only a simple hack that does not imply the drawbacks he mentioned in 1-4, could it be implemented and e.g. activated by a filesystem property of some sort?

**Comment by Vringe** [comment]
I also have problems adding the cache=none parameter to libvirt XML.
Please add direct IO support.

**Comment by kpande** [comment]
libvirt can use cache=none on ZVOL.

**Comment by Bronek** [comment]
@kpande I can confirm it works, when used with io=native . Although performance is not great  , compared to cache=writeback io=threads .

**Comment by Vringe** [comment]
@kpande Yes, but I'm not using ZVOL. It's just the RAW file which is stored in the dataset.

@Bronek According to the docs, **directsync** is described as follows: This mode causes qemu-kvm to interact with the disk image file or block device with both O_DSYNC and O_DIRECT semantics, where writes are reported as completed only when the data has been committed to the storage device, and when it is also desirable to bypass the host page cache. Like cache=writethrough, it is helpful to guests that do not send flushes when needed. It was the last cache mode added, completing the possible combinations of caching and direct access semantics.

I think you're right. Seems like it is very similar to writeback, except for the performance impact.

**Comment by lnxbil** [comment]
@Vringe Don't store RAW files as ZFS as files. There is no benefit and it is not as fast as it could be. ZVOL is perfect for that and you can snapshot a VM at a time and you have a constant (vol)block size.

**Comment by Vringe** [comment]
@lnxbil Each VM has it's own dataset, so I can easily create snapshots. During my performance tests, I found out that ZVOLs are not really better performing than datasets. There were also some really wierd problems I had with ZVOLs. The environment is running well. I just want to use swap on the guest machines instead of using the hosts cache.

**Comment by lnxbil** [comment]
@Vringe yet you cannot use trim and therefore have not so efficient thin provisioning. You can also have bad write amplification with a dataset if you have not set the recordsize properly. If you have different access pattern from you emulation layer. zvol will always use the volblocksize

**Comment by livelace** [comment]
That is why I cannot use Ovirt with Local Storage configuration for years, because it wants DIRECT_IO.

**Comment by kpande** [comment]
use zvol, O_DIRECT works fine there.

**Comment by livelace** [comment]
>use zvol, O_DIRECT works fine there.

Do you use Ovirt ?

**Comment by jumbi77** [comment]
Any news on real o_direct support since scatter-gather list gets merged? Just curious, thanks

**Comment by cwedgwood** [comment]
@jumbi77 I think we have to consider what `O_DIRECT` actually means for ZFS ZPL.

Historically in the past for other file-systems it more-or-less meant that the data was transferred from the disks directly into the userspace buffers without any intermediate buffering, but with newer storage stacks that mapping isn't possible (this is true for non ZFS in many cases too).

@behlendorf I suggest `O_DIRECT` really means `O_SYNC` with "as little buffering as possible".

**Comment by rlaager** [comment]
I think it means "as little buffering as possible". If I want O_SYNC, I'll say O_SYNC (instead of or in addition to O_DIRECT). The open(2) man page on Linux explicitly says that it doesn't guarantee the same semantics as O_SYNC and you need to pass both if you want both.

**Comment by pk1234** [comment]
We are using ZFS on all of our production machines (mostly Solaris an Linux) and our backup strategy is based upon ZFS-snapshots.

So far we only used Oracle Databases on Solaris machines and Oracle runs just fine on ZFS. There's even a Sun-whitepaper with information about optimal ZFS-configuration for Oracle databases.

Unfortunately Oracle fails under Linux if Archive Log files are stored within a ZFS volume and I would not mention this here if Direct IO wasn't the culprit. Here's a single line from strace-output:

`open("/var/oracle/diag/rdbms/b1/B1/metadata/ADR_INTERNAL.mif", O_RDONLY|O_DIRECT) = -1 EINVAL (Invalid argument)`

I'm aware of the following 3 possible solutions:

- adding pseudo direct IO support to ZFS
- ignoring O_DIRECT within ZFS
- ignoring O_DIRECT outside of ZFS

I tried to ignore O_DIRECT within ZFS first and my idea was to find the line of source where ZFS refuses to open a file with O_DIRECT-flag. But searching within the ZFS source code for O_DIRECT resulted in almost nothing. Seems like the ZFS-software does not reject open() calls with O_DIRECT but the VFS layer knows that ZFS is lacking DirectIO-support and therefore rejects open() calls with O_DIRECT.

Is that correct? Can I patch my kernel such that VFS does ignore O_DIRECT for ZFS filesystems?

So I tried to add direct IO support to ZFS. Have a look at [this patch](https://github.com/zfsonlinux/zfs/commit/a08c76a8ad63c28384ead72b53a3d7ef73f39357) from 2015. It does not work with current ZFS and I doubt that i has worked with former versions (there are unbalanced #if-/#endif-lines and `int rw = iov_iter_rw(iter);` uses the undeclared variable `iter`).

But the idea should work: Adding a zpl_direct_IO() routine to zpl_file.c and adding this routine to the zpl_address_space_operations structure.

I tried that but i did not bother with the config-macros that detect what kind of VFS-API is in use with my 4.4.113-kernel. Here's what I added to zpl_file.d:

```
static size_t
zpl_direct_IO(struct kiocb *kiocb, struct iov_iter *from, loff_t offset)
{
        if(iov_iter_rw(from)== WRITE){
                return (zpl_iter_write_common(kiocb, from->iov, from->nr_segs, kiocb->ki_nbytes));
        }
        return (zpl_iter_read_common(kiocb, iovp, nr_segs, kiocb->ki_nbytes));
}

const struct address_space_operations zpl_address_space_operations = {
        .readpages      = zpl_readpages,
        .readpage       = zpl_readpage,
        .writepage      = zpl_writepage,
        .writepages     = zpl_writepages,
        .direct_IO      = zpl_direct_IO
};
```
This does not work. Calling zpl_iter_write_common() with 3 parameters was copy&pasted from the 2015-patch, but zpl_iter_write_common() has 6 parameters right now. To make this work I need some expert-advise.

How do I add the missing parameters to zpl_iter_write_common() and zpl_iter_read_common()? Does that make sense at all?

Since adding direct IO support into my kernel with the above hack failed I decided to ignore O_DIRECT outside of ZFS. LD_PRELOAD is your friend if you try to replace a system call with something else. In my case I created the library libOpenWithoutDirectIO.so from the following source code:
```
/* compile this with
   gcc -Wall -fPIC -shared -o libOpenWithoutDirectIO.so thisfile.c
   and use
   export LD_PRELOAD=/path/to/libOpenWithoutDirectIO.so
*/
#define _GNU_SOURCE
#include <dlfcn.h>
#include <fcntl.h>
#include <stdarg.h>

int open(const char *path, int flags, ...){
        static int (*func)(const char *path, int flags, ...);

        if(!func) func=dlsym(RTLD_NEXT,"open");
        flags &= ~O_DIRECT;
        if(flags & O_CREAT){
                va_list a; mode_t mode;
                va_start(a,flags); mode=va_arg(a,mode_t); va_end(a);
                return func(path, flags, mode);
        }
        return func(path, flags);
}

int open64(const char *path, int flags, ...){
        static int (*func)(const char *path, int flags, ...);

        if(!func) func=dlsym(RTLD_NEXT,"open64");
        flags &= ~O_DIRECT;
        if(flags & O_CREAT){
                va_list a; mode_t mode;
                va_start(a,flags); mode=va_arg(a,mode_t); va_end(a);
                return func(path, flags, mode);
        }
        return func(path, flags);
}
```
This will remove O_DIRECT on every open()/open64() system call. I don't like this because O_DIRECT should be removed if and only if path is pointing to a file that is located within a ZFS-volume. With the above hack O_DIRECT is removed from every open()/open64() call.

But Orace is running now on top of ZFS.

Any comments?

Peter

**Comment by nigoroll** [comment]
@pk1234 see
https://github.com/zfsonlinux/zfs/issues/224#issuecomment-160126586
https://code.uplex.de/liblongpath/liblongpath/commit/2e46a921ce2b6b1caa56d39cbd58be85c5988bd0

Here we try the original flags and only remove O_DIRECT if they fail.

**Comment by lnxbil** [comment]
Hi Peter,

> This will remove O_DIRECT on every open()/open64() system call. I don't like this because O_DIRECT should be removed if and only if path is pointing to a file that is located within a ZFS-volume. With the above hack O_DIRECT is removed from every open()/open64() call.

I tried a similar thing over a year ago and my listener was not able to work in xml mode, only plaintext mode. I could not patch that, yet the database was working. I have to search the writeup of my work at home and post it here. It's so funny to see that we both tried to solve the problem similarly. I went also one step further and tried to patch glibc to just use it everywhere, transparently, yet that did not work in the limited time I had. I finished my investigation after spending over 10h on that topic.

**Comment by nigoroll** [comment]
@lnxbil I can tell you that my interposer does the job.

**Comment by behlendorf** [comment]
@au-phiware whoops, no I did not.  It was accidentally caused by merging the SPL and it's history in to the ZFS repository.  See PR #7556, we'll probably have a few more of these.

**Comment by paulkramme** [comment]
What is the progress on this? I tried installing OVirt, but, as Oirt needs direct IO, the installation failed. 

My workaround is to use a ZVOL with XFS in it.

**Comment by shodanshok** [comment]
@behlendorf any update on the matter? I agree that O_DIRECT can be implemented by simply treating it as a hint ZFS can ignore. As another step, it would be great if O_DIRECT requests pollute the ARC as little as possible (basically what you suggested in your comment on 22 Apr 2014).

**Comment by behlendorf** [comment]
No one I'm aware of is working on this.  If someone would like to take a crack at it I'm happy help with the design, which could initially be the basic one described above, and review the changes.

**Comment by shodanshok** [comment]
@ryao If I understand it correctly, your old patch https://github.com/zfsonlinux/zfs/commit/a08c76a8ad63c28384ead72b53a3d7ef73f39357 basically ignores O_DIRECT by serving reads/writes using normal AIO functions.

Any chances to update it for newer ZFS / kernel releases?

**Comment by behlendorf** [comment]
> Would be a simple "ignore O_DIRECT" policy be acceptable in current ZoL?

Something verify similar would acceptable. The approach taken by @ryao is an excellent start but we need to incorporate two additional changes to stay consistent with the intent of O_DIRECT.  Otherwise we risk breaking existing applications which depend on this behavior.

* O_DIRECT should to behave as if O_SYNC were set.

* As @rlaager [suggested](https://github.com/zfsonlinux/zfs/issues/224#issuecomment-229752050) O_DIRECT IO's should imply `primarycache=metadata` for those blocks.

Both of these should be relatively easy to implement since all of the needed functionality already exists.

**Comment by rlaager** [comment]
I disagree with the idea that O_DIRECT should imply O_SYNC. My interest here is with cache=none for qemu. As was already mentioned, qemu has cache=none (O_DIRECT) and cache=directsync (both O_DSYNC and O_DIRECT). If someone wants both O_DIRECT and O_SYNC, they can ask for both.

**Comment by shodanshok** [comment]
As @rlaager suggested, O_DIRECT should *not* imply O_SYNC. From [open() man page](http://man7.org/linux/man-pages/man2/open.2.html):

> O_DIRECT (since Linux 2.4.10)
>               Try to minimize cache effects of the I/O to and from this
>               file.  In general this will degrade performance, but it is
>               useful in special situations, such as when applications do
>               their own caching.  File I/O is done directly to/from user-
>               space buffers.  The O_DIRECT flag on its own makes an effort
>               to transfer data synchronously, but does not give the
>               guarantees of the O_SYNC flag that data and necessary metadata
>               are transferred.  To guarantee synchronous I/O, O_SYNC must be
>               used in addition to O_DIRECT.  See NOTES below for further
>               discussion.

For a first implementation even simply ignoring O_DIRECT (similar to FreeBSD) should be better than current behavior (where open() with O_DIRECT fails with an error). If we can wire O_DIRECT with `primarycache=metadata` this would be great, however.

**Comment by behlendorf** [comment]
Thanks for explicitly calling out what the man page has to say about this.  Given that, I agree we just want the minimal caching behavior.

**Comment by behlendorf** [comment]
I've opened #7823 with an updated version of @ryao's original patch.  It does not implement the `primarycache=metadata` suggestion and instead behaves the same way as Illumos and FreeBSD.  After some investigation I decided there were additional complexities which needed more analysis and would be better tackled at a latter date.  See the PR for additional details.
