### ISSUE TITLE
ZFS locking the system when mounting the storage, out of memory problem.

### ISSUE THREAD

**Issue by siggjen** [zfsonlinux/zfs#2579]
I have created zpool storage /srv/zfs about 7 TB. Option dedup and compress is on in a Debian 7.5 server (IBM x3550M4 24 GB memory) 

There are 5 zfs file systems there:
storage/backup1
storage/backup2
storage/daily_backup
storage/weekly_backup
storage/monthly_backup

After a heat problem in the serverroom the server was hung. I had to power it off and start it again when heat was down to normal levels.

Now every time I zfs mount -a (had to turn off zfs mount on boot to get into the server) the command doesn't return to bash without a CTRL ^C. After a while the server hangs, but answers PING.
It shows on KVM console: INFO: task txg_sync blocked for more than 120 seconds. Eventually the last info on console shows out of memory killing procs. then finally Kernel Panic - not syncing: out of memory and no killable processes...

Snip of /var/log/messages after zfs mount -a
https://gist.github.com/siggjen/2d6f7a8fb6282d99e6b2#file-gistfile1-txt

**Comment by mailinglists35** [comment]
@siggjen have you managed to successfully import your pool using another OS?

**Comment by siggjen** [comment]
I went for BTRFS instead and don't face such problems anymore.

**Comment by behlendorf** [comment]
@siggjen thanks for the reply.  Unfortunately, since I haven't seen any similar reports to this and you've moved the system to BTRFS it doesn't look like there's much we can do.  Perhaps you'll give ZFS another try in a few years.

**Comment by theking2** [comment]
Exactly same problem here. Have started the system about 5 times now. After 45min of blocked txg_sync it runs OOM and kills zfs mount. Does it indeed continue where it left off? In that case I can continue restarting it after ran OOM and hope to work.

**Comment by vinayadatta** [comment]
I face similar issues and it's mainly because my dedup was turned on, deduplication management is the culprit which starts at startup and doesn't give up until it's completed. But that process needs 100s of GBs of RAM so it's practically not possible to complete before the system runs out of memory and hangs. 

Once I managed to disable ZED.service and destroy the dataset that had dedup turned on, and then I did not have the memory fill up issue.. Luckily I did not need any of those files in that dataset anymore..

Although my previous attempt was successful I've started to experience the same issue on a different dataset due to dedup set to on on the existing files. I can't seem to un-dedup the existing files now even though I have set dedup=off (just the way ZFS handles it).

When ZED service is disabled I'm not sure how to access my files to delete my suspected files as mount service is stopped as well, need to see if I can somehow mount the dataset and clear my suspected files (hopefully my suspected files are the ones causing the issue)
