### ISSUE TITLE
Unable to clear permanent errors.

### ISSUE THREAD

**Issue by fling-** [zfsonlinux/zfs#2617]
```
studio ~ # zpool clear studio-striped
studio ~ # zpool clear studio-striped studio-striped_leg_a
studio ~ # zpool clear studio-striped studio-striped_leg_b
studio ~ # zpool status -v studio-striped
  pool: studio-striped
 state: ONLINE
status: One or more devices has experienced an error resulting in data
        corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
        entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub repaired 0 in 13h25m with 0 errors on Wed Aug 20 10:34:36 2014
config:

        NAME                    STATE     READ WRITE CKSUM
        studio-striped          ONLINE       0     0     0
          studio-striped_leg_a  ONLINE       0     0     0
          studio-striped_leg_b  ONLINE       0     0     0

errors: Permanent errors have been detected in the following files:

        <0x39c>:<0xb>
```

I had an UNC sector ( represented as 8x logical 512B sectors on the drive).
lost ~50K of data in the middle of a single file (more than 4K because of compression?).
I had rewritten 8 affected sectors then I reimported the pool and destroyed dataset containing the file and tried to clear without luck.
Clear does not work even aftrer a scrub.

**Comment by montanaviking** [comment]
I have a similar issue, namely I got the following errors:
 pool: zbackup4
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub repaired 0 in 13h47m with 0 errors on Wed Apr 19 12:03:40 2017
config:

	NAME        STATE     READ WRITE CKSUM
	zbackup4    ONLINE       0     0     0
	  sdd       ONLINE       0     0     0

errors: Permanent errors have been detected in the following files:

        <metadata>:<0x0>
        <metadata>:<0x1>
        <metadata>:<0x1d780>
        /zbackup4/home/
#################
The ZFS version is:
$ dmesg | grep ZFS
[    5.719507] ZFS: Loaded module v0.6.5.9-1~trusty, ZFS pool version 5000, ZFS filesystem version 5
and I'm running Ubuntu 14.04
Sibyl 3.13.0-116-generic #163-Ubuntu SMP Fri Mar 31 14:13:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

A scrub did not help to clear the errors, nor did zpool clear zbackup4.
zbackup4 This is a backup USB-connected drive with copies=2 to provide some degree of redundancy (for a single drive).
This external drive shows a good SMART status with no reallocated sectors.

I suspect the ZFS errors were caused by a momentary USB interruption and/or ZFS caused error and are likely not physical.

Do I need to go ahead and rebuild this backup pool? Is there a way to clear the error?
Thanks so much,
Phil

**Comment by richardelling** [comment]
The "permanent errors" list contains information from up to two scrubs (current and previous). If you believe the errors to be transient, then try another scrub.

**Comment by montanaviking** [comment]
Hi Richard,
I'll try that now. I didn't see any checksum errors on the last scrub
(first scrub since the errors). Just wondering, would a scrub reveal all
real errors as checksum errors? In other words, is there any case where
real corruption could occur with zero checksum errors? My machine has ECC
too.
Thanks and Best,
Phil

**Comment by richardelling** [comment]
... if they are checksum errors, that really depends on if there were errors reported by the underlying drivers.

If you want to look at the details `zpool events` is your friend

**Comment by montanaviking** [comment]
Hi Richard,
Here is the result
$ zpool events
TIME                           CLASS
Apr 18 2017 22:18:34.963746059 resource.fs.zfs.statechange
Apr 18 2017 22:18:34.963746059 resource.fs.zfs.statechange
Apr 18 2017 22:18:34.963746059 resource.fs.zfs.statechange
Apr 18 2017 22:18:34.963746059 resource.fs.zfs.statechange
Apr 18 2017 22:18:35.047746061 resource.fs.zfs.statechange
Apr 18 2017 22:18:36.295746087 resource.fs.zfs.statechange
Apr 18 2017 22:18:36.303746087 resource.fs.zfs.statechange
Apr 18 2017 22:18:36.311746087 resource.fs.zfs.statechange
Apr 18 2017 22:18:36.771746097 ereport.fs.zfs.config.sync
Apr 18 2017 22:18:37.143746104 ereport.fs.zfs.config.sync
Apr 18 2017 22:19:23.747747069 resource.fs.zfs.statechange
Apr 18 2017 22:19:32.535747251 ereport.fs.zfs.config.sync
Apr 18 2017 22:19:45.919747528 ereport.fs.zfs.config.sync
Apr 18 2017 23:02:08.269770154 ereport.fs.zfs.scrub.start
Apr 19 2017 12:03:40.154740631 ereport.fs.zfs.scrub.finish
Apr 19 2017 12:08:43.374746906 ereport.fs.zfs.zpool.destroy
Apr 19 2017 12:08:45.394746948 ereport.fs.zfs.config.sync
Apr 19 2017 12:09:03.638747326 resource.fs.zfs.statechange
Apr 19 2017 12:09:04.142747336 ereport.fs.zfs.config.sync
Apr 19 2017 12:09:04.446747342 ereport.fs.zfs.config.sync
Apr 19 2017 12:55:27.154804933 ereport.fs.zfs.scrub.finish
Apr 19 2017 14:32:27.954925401 ereport.fs.zfs.scrub.start

Thanks,
Phil

**Comment by richardelling** [comment]
If a checksum or other error is found, there should be an e[rror]report describing its details. These events are since boot or when the zfs driver was loaded. The error log is on-disk. So it is possible that the events reports do not tell the whole story.

**Comment by montanaviking** [comment]
Hi Richard,
Thanks so much for your advice and time! It turns out your suggestion of
performing another scrub worked. It looks like it needed two scrubs to
clear the "permanent" errors. SMART had also shown that the drive was OK. I
use ZFS for my USB backup drives too (send them snapshots) with the backup
drives' set to copies=2 to provide error correction.
Best,
Phil

**Comment by richardelling** [comment]
We're glad to hear the good news!

For the archives, it is not uncommon to see transient errors on USB or similar, hot-pluggable interfaces. From ZFS's perspective, such errors appear as drive errors and are treated as such. But if they are transient, the two-scrub process should clear them out of the error log. If they are permanent (also common on USB disks :-( ) then the details can be displayed by `zpool events [-v]`
