### ISSUE TITLE
/dev/zfs should use strings when passing values of index properties

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#2731]
Currently, properties are sent to the kernel using integers, which is prone to break. We should switch the /dev/zfs interface to using strings. This is likely a pre-requisite for /dev/zfs ioctl stabilization.

**Comment by behlendorf** [comment]
Closing.  This issue was addressed by the following commits which provide nvpair validation for new style ioc input and a mechanism for the installed kernel module to advertise what features and properties are supported.

b83a0e2 Add basic zfs ioc input nvpair validation
e8bcb69 Add zfs module feature and property info to sysfs
