### ISSUE TITLE
Zpool labelclear on a partition containing a LUKS/dm-crypt volume destroys the volume

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#2811]
Clearing the ZFS label from the last partition of a GPT disk today, i ran into a neat detail - this process removes the LUKS header, or some other identifying piece of the on-disk structure required for cryptsetup to even recognize the volume as LUKS.

The disk is one of a pair, each split 80/20 for cache and log respectively, with the log partitions used as a mirror VDEV (so i've not lost data, i hope). Once the pool contents became more vital, the partitions were removed from another pool, encrypted, and reintroduced to this one as the decrypted volumes in the same layout. Upon attempting to import the pool, the prior label was discovered, zpool labelclear used, and the LUKS container destroyed.

Is this expected behavior? If so, we probably want to document it in the man pages, with an explicit warning about LUKS and parting with one's data.

**Comment by devZer0** [comment]
why has this been closed ?

https://github.com/zfsonlinux/zfs/issues/6261

**Comment by devZer0** [comment]
>i would expect zpool labelclear to overwrite the first and last 512KB of the block device specified

please look on this from the end user`s perspective (not the developers perspective) - according to manpage i would expect zpool labelclear would remove zfs label information from the disk and not silently wipe other regions of the disk which already contain complete other, non zfs related information. as i reported in my ticket i screwed my 2TB disk which already was being used for something completely different the zfs - but when adding more disks and trying to use them for zfs i found that there was old zfs information on that disk (because i didn`t dd the whole disk till the end) and i simply wanted to get rid of the orphaned label at the end of the disk. but zpool labelclear wiped the beginning, too. i think that is stupid and at least it needs documented

man zpool:
zpool labelclear [-f] device
             Removes ZFS label information from the specified device.  The
             device must not be part of an active pool configuration.

**Comment by kpande** [comment]
@devZer0 "the device must not be part of an active pool configuration" is this what you missed?

**Comment by devZer0** [comment]
i don't remember if i used -f or not, but the disk was not part of an active pool configuration anymore. see my comment in #6261

**Comment by GregorKopka** [comment]
After further thinking about this I have to revise my comment from 2014 with https://github.com/zfsonlinux/zfs/issues/6261#issuecomment-346662290
