### ISSUE TITLE
Alternate paths for drives

### ISSUE THREAD

**Issue by prometheanfire** [zfsonlinux/zfs#2856]
we could also use guids maybe?

#2155 for more info

**Comment by adilger** [comment]
Why does ZFS even care about device paths?  It could just re-lookup the GUID using blkid/libblkid whenever it needs to, and since blkid caches these GUIDs in a single flat file produced by udev when devices are added to the system, it doesn't need to scan the disks.

**Comment by behlendorf** [comment]
It absolutely could be.  This is basically what illumos does using the devid when it can't find the right device at the expected path.  Although that's less common on illumos because they always enumerate the devices sequentially and they block until all the devices are enumerated.  That's not fast but it has the advantage of being dead simple.

Under Linux that was never implemented because given the kernel interfaces available it wasn't an easy thing to do.  And honestly very few people have revisited this code since I first implemented it.  

I completely agree we should integrated more tightly with blkid but so far it hasn't been a critical issue.  It's also worth pointing out that relying on blkid exclusively probably isn't desirable because that will have the side effect of changing the device names in commands like `zpool status`.  Many people like the ability to give those devices meaningful human readable names.  But I completely agree we should use libblkid more to identify the devices.
