### ISSUE TITLE
zvols, device-mapper, LVM2, and LIO target (targetcli)

### ISSUE THREAD

**Issue by esamatti** [zfsonlinux/zfs#2994]
My Setup:
1) I have a Fedora 21 x64 system that boots to a little 32GB SSD, and I am using "targetcli" to present LUNs to fiber channel initiators.  

2) For the backstores I am using ZFS on Linux (zfs-testing).  I started out using the stable but have since installed the testing code to try to resolve my issue.

3) I have a dual-port Emulex 4Gb FC HBA daisy-chained in a multipath configuration to FC storage enclosures exposing a total 24 1TB drives.  I also have a Qlogic quad port FC HBA for the targets.

4) I am using dm-multipath with aliases (A0,A1, A2, A3, etc...) in the /dev/disk/by-vdev for the devices in the zpools.

My Problem:
1) after creating a zvol and presenting it to an FC client as a LUN using targetcli, I was able to install the OS (linux with LVM) and everything works just fine.

2) After reboot, it looks like LVM scans the zvols and the VGs and LVs from the linux that was installed on the zvol shows up in /dev/mapper.

3) targetcli is not able to add the backstore because it's already in use (by dev-mapper I believe).

4) I tried blacklisting all WWNs except the 24 FC disks in /etc/multipath.conf but all the partitions still show up in /dev/mapper. :(

5) If I remove all the unwanted entries using "dmsetup remove <mapper_id>" if I do it before the target starts, and then the target will work.

Question:
How can I ensure that nothing else tries to scan or use the zvols I create when using ZFS as SAN backstores? I only want FC target stack (and associated initiators) to access those volumes, but not the local LVM, or anything else.

Let me know if you need me to post any logs or anything else to help solve this.

**Comment by jmhickman** [comment]
I know this is kind of stale, but I wanted to chip in anyway in case someone arrives here with Google.

I ran into essentially this same issue. My hardware setup isn't nearly so high end, but the commonality was LVM on the ZoL host box stealing mounts to the stuff on a zvol that I had exposed to a XenServer machine as a VM repository. `targetcli` would get really mad and claim that the datasets were busy, and I actually couldn't even export the pools for the same reason because I didn't know to look to dev-mapper devices as a possible cause. 

I was able to halt this behavior by adding a line to lvm.conf in the "global_filter" section
`global_filter = ["r|/dev/zd*|"]`

I also found that CentOS won't actually even install the LVM stuff if you don't use it to set up the system. So just telling the installer to use standard ext4 or xfs partitions gets around having to do this in the first place.

**Comment by adila01** [comment]
@jmhickman I can verify that your workaround does indeed work. Thank you.

**Comment by makhomed** [comment]
@jmhickman, @adila01, ```global_filter``` in lvm.conf has regular expression syntax, 
so correct directive should be:
```
global_filter = ["r|/dev/zd.*|",  "a|.*/|"]
```
