### ISSUE TITLE
boot hangs with nested mountpoint after recent kernel and zfs updates 

### ISSUE THREAD

**Issue by ross** [zfsonlinux/zfs#2995]
as best as i can tell it has something to do with having a nested mountpoint, i.e. 

tank/home has mountpoint=/home
tank/crashplan has mountpoint=/home/ross/crashplan

zfs installed via the stable ppa. this had worked for ~6 months. if i boot in to rescue mode it seems to come up correctly. i can then start networking (which remounts everything r/w) and go to a root shell and everything is there and mounted. as soon as i go back to a normal boot or exit the root shell and resume booting it hangs after zfs is initialized and the root volume is remounted r/w.

it's happening with several kernels now (ones that previously worked) so i'm guessing it was a change in the zfs code. the latest kernel is 0-43 and it seems to have the same issue as the one listed below. 

i was able to track it down when i did ctrl-alt-del to reboot the system. i'd (very quickly/briefly) see a graphical message saying there was a problem mounting tank/crashplan.

my work around was to boot in to rescue mode, start networking, and go in to a root shell and do.

```
zfs set mountpoint=/tank/crashplan tank/crashplan
cd /home/ross
rm crashplan
ln -s /tank/crashplan
```

after doing that the system boots up fine. tried to do a bit more debugging via initramfs, but the zfs commands didn't seem to be available to me there (as another issue seemed to imply they might be.) so that's all the details i have atm. let me know if there's something else to be tried/checked.

```
animal$ uname -a
Linux animal 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
animal$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```

```
animal$ dpkg -l | grep zfs
ii  dkms                                                  2.2.0.3-1.1ubuntu5.14.04+zfs9~trusty                all          Dynamic Kernel Module Support Framework
ii  libzfs2                                               0.6.3-4~trusty                                      amd64        Native OpenZFS filesystem library for Linux
ii  mountall                                              2.53-zfs1                                           amd64        filesystem mounting tool
ii  ubuntu-zfs                                            8~trusty                                            amd64        Native ZFS filesystem metapackage for Ubuntu.
ii  zfs-auto-snapshot                                     1.1.0-0ubuntu1~trusty                               all          ZFS Automatic Snapshot Service
ii  zfs-dkms                                              0.6.3-4~trusty                                      amd64        Native OpenZFS filesystem kernel modules for Linux
ii  zfs-doc                                               0.6.3-4~trusty                                      amd64        Native OpenZFS filesystem documentation and examples.
ii  zfsutils                                              0.6.3-4~trusty                                      amd64        Native OpenZFS management utilities for Linux
```

**Comment by GregorKopka** [comment]
My guess is zfs wrongly sorty the order of mounts not by mountpoint, but by dataset path.
 This would lead to mointing *tank/crashplan* before *tank/home* (which fails since /home/ross dosn't exist at that point).

Do you have a *tank/home/ross*? If so could you try to 
`zfs inherit mountpoint tank/crashplan; zfs rename tank/crashplan tank/home/ross/crashplan`
and see if that boots cleanly?

You should also be able to reproduce the problem in a running system by issuing `zpool export tank && zpool import tank` (in case tank dosn't contain your rootfs and no services run from it, so an `init 2` or similar might do the trick)

**Comment by dajhorn** [comment]
@ross 

> it's happening with several kernels now (ones that previously worked) so i'm guessing it was a change in the zfs code. the latest kernel is 0-43 and it seems to have the same issue as the one listed below.

Can you boot into older kernels and report the last working version?

Please also check for mountall glitching.  Add the `--debug --verbose` switches to the `exec` line in the `/etc/init/mountall.conf` file and check for `/var/log/init/mountall*` files afterwards.

If the crashplan daemon isn't fully hooked into the Ubuntu init subsystem, then it may be keeping file files open or leaving temporary files under the nested mountpoint.  Check for stray handles with a tool like `lsof`.

ZoL requires an existing non-empty mountpoint by default, and the error message can be hidden or non-obvious.


> after doing that the system boots up fine. tried to do a bit more debugging via initramfs, but the zfs commands didn't seem to be available to me there (as another issue seemed to imply they might be.)

Installing the `zfs-initramfs` package will put things like `/sbin/zdb` into the initrd.

**Comment by GregorKopka** [comment]
After a similar issue on the mailing list (https://groups.google.com/a/zfsonlinux.org/d/msg/zfs-discuss/eeQQA3sb2cI/j7GVt6qDroMJ) my suspicion grows that mountall is sorting the datasets by `name` instead of `mountpoint` (inherited or specified) to obtain the order in which to mount.

**Comment by dajhorn** [comment]
People getting something like this should open a new ticket and go through the usual troubleshooting motions, particularly by reporting logs and software versions.

Several distinct things are happening in this family of bug reports:

1. A kernel regression in Trusty seems to be affecting a few installations.  (This bug is not yet diagnosed, but it is easily kludged by running a different kernel build.)
1. Local (java) applications that start early and hook storage facilities outside of the `upstart` framework are known to be problematic.  (Such things are unsupported by distro, but configuration hints and contributed fixes are nevertheless welcome.)
1. The `mountall` utility is somewhat different for each Ubuntu release, but all versions minimally sort by mountpoint dependency only.  The `pool/archive /archive` example given on the discussion list should certainly work, but a log that reports the failing attempted mount order for the entire system is required for troubleshooting.  
1. Init parallelization in Trusty is more aggressive than Precise, which can express race conditions more frequently after a distribution upgrade.

**Comment by vanbcguy** [comment]
I can add a few details...

I don't believe this is kernel related, I had nested mounts working find with the Trusty kernel under Ubuntu 12.04, but after upgrading to 14.04 using the same kernel version I started experiencing problems.  So a consistent kernel version, which should help eliminate point 1 at least in my case.

I even went so far as to do a 'zpool import -N' in recovery mode and confirmed that the pool was successfully imported before resuming a normal boot.  The issue was still present in that case, which should rule out any issues around points 2 and 4 above.

I did have the '--verbose' flag passed to mountall when trying to troubleshoot this, however it doesn't appear to have logged anything.  In the instances where I went to Recovery mode and then resumed normal boot I DID end up getting a hint in the form of a message indicating that the disk for one of the mountpoints was not yet present; in that case I had:

pool/archive      /archive
pool/Images      /archive/Images
<etc>

...mountpoints, and the message was from pool/Images.

I'm doing some testing now, I've created a couple of zfs filesystems:

pool/testing        /testing
pool/willitbreak  /testing/willitbreak

'zfs list' shows them in the above order, the system boots fine.

rename 'willitbreak' to 'awillitbreak', now zfs list shows this order:

pool/awillitbreak  /testing/willitbreak
pool/testing         /testing

...and the system hangs on mount.
