### ISSUE TITLE
zevents is full of ereport.fs.zfs.delay

### ISSUE THREAD

**Issue by alexanderhaensch** [zfsonlinux/zfs#3005]
We are running a pool with 14 disks and a L2Arc and ZIL. I recently noticed, a lot of ereport.fs.zfs.delay in the zpool event output. Frankly, i was not checking the output before, so i am not sure if it was there before.
zpool events -v | grep vdev_path | sort |uniq -c 
showed that the effect is very much averaged over all devices in the pool, except ARC and ZIL.

The zio_delay were not that high, mostly around zio_delay = 0x81. I have no idea what the value means. In what unit are these values? Milliseconds? Seconds?

We do not "feel" any unnatural slowdowns, while the system is running for over 100days. Maybe a reboot would solve the issue?

**Comment by behlendorf** [comment]
The delay warning should only be triggered when an IO takes longer than 30 seconds to complete.  This is _very_ briefly mentioned in the `fs-module-parameters(5)` man page but that section really needs to be expanded upon.

```
       zio_delay_max (int)
                   Max zio millisec delay before posting event

                   Default value: 30,000.
```

Since the events are printed in hexadecimal I'd expect to see the zio_delay values all exceed 0x7530 and at that point I'd think there would be a noticeable performance issue.  But that doesn't sound like what your observing.  There could be a bug here which is resulting in the events being posted more often than they should.

Could you post in an example of one of these events, it may shed some light on what's going on.  Also please include the ZoL versions your running.

**Comment by alexanderhaensch** [comment]
Some hint emerged yesterday: The events seem to happen if a recursive chmod is executed.
Is it possible at all that chmod is producing some delay in writes?
I will try to confirm that the events are correlated with chmod -R. From the times the events occur and the execution of recursive chmod fits together.

**Comment by alexanderhaensch** [comment]
The update to 0.6.4 maybe fixed the issue. It was running now for 2 weeks without the messages in events.

**Comment by alexanderhaensch** [comment]
the issue is solved.
