### ISSUE TITLE
zfs tracepoints are not enabled 

### ISSUE THREAD

**Issue by kiranfractal** [zfsonlinux/zfs#3119]
Hi,

I installed zfs by enabling zfs-testing in the zfs.repo file and I tried to check if zfs tracepoints are enabled but it is not.

Let me know what should I do.

[root@li349-79 events]# ls
block   ext4    header_event  irq          jbd2  mce     napi  power  sched  signal  sock      timer  workqueue
enable  ftrace  header_page   irq_vectors  kmem  module  net   ras    scsi   skb     syscalls  udp    writeback

[root@li349-79 events]# tail -f /var/log/messages
Feb 19 06:37:58 li349-79 yum[1024]: Installed: spl-dkms-0.6.3-71_g086476f.el6.noarch
Feb 19 06:37:58 li349-79 yum[1024]: Installed: spl-0.6.3-71_g086476f.el6.x86_64
Feb 19 06:43:40 li349-79 yum[1024]: Installed: zfs-dkms-0.6.3-202_g33b4de5.el6.noarch
Feb 19 06:43:40 li349-79 yum[1024]: Installed: libzfs2-0.6.3-202_g33b4de5.el6.x86_64
Feb 19 06:43:40 li349-79 yum[1024]: Installed: zfs-0.6.3-202_g33b4de5.el6.x86_64
Feb 19 06:48:10 li349-79 kernel: SPL: Loaded module v0.6.3-71_g086476f
Feb 19 06:48:10 li349-79 kernel: zunicode: module license 'CDDL' taints kernel.
Feb 19 06:48:10 li349-79 kernel: Disabling lock debugging due to kernel taint
Feb 19 06:48:10 li349-79 kernel: ZFS: Loaded module v0.6.3-202_g33b4de5, ZFS pool version 5000, ZFS filesystem version 5
Feb 19 06:48:10 li349-79 kernel: SPL: using hostid 0x00000000

[root@li349-79 events]# uname -a
Linux li349-79 2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

[root@li349-79 events]# cat /etc/issue
CentOS release 6.6 (Final)
Kernel \r on an \m

[root@li349-79 events]# rpm -qa *zfs*
zfs-dkms-0.6.3-202_g33b4de5.el6.noarch
libzfs2-0.6.3-202_g33b4de5.el6.x86_64
zfs-release-1-4.el6.noarch
zfs-0.6.3-202_g33b4de5.el6.x86_64

[root@li349-79 events]# rpm -qa *spl*
spl-0.6.3-71_g086476f.el6.x86_64
spl-dkms-0.6.3-71_g086476f.el6.noarch

Thanks.

**Comment by kiranfractal** [comment]
[root@li349-79 debug]# find /sys -name zfs
/sys/devices/virtual/misc/zfs
/sys/class/misc/zfs
/sys/module/spl/holders/zfs
/sys/module/zunicode/holders/zfs
/sys/module/zavl/holders/zfs
/sys/module/znvpair/holders/zfs
/sys/module/zcommon/holders/zfs
/sys/module/zfs

**Comment by behlendorf** [comment]
@kiranfractal Unfortunately, there are a few caveats which prevent tracepoints from being enabled by default:
    
* Linux tracepoints appear to only be available to GPL licensed modules due to the way certain kernel functions are exported.   Thus, to actually make use of the tracepoints introduced by this patch, one might have to patch and re-compile the kernel; exporting the necessary functions to non-GPL modules.  
    
* Prior to upstream kernel version v3.14-rc6-30-g66cc69e, Linux tracepoints are not available for unsigned kernel modules (tracepoints will get disabled due to the module's 'F' taint).  Thus, one either has to sign the zfs kernel module prior to loading it, or use a kernel versioned v3.14-rc6-30-g66cc69e or newer.
