### ISSUE TITLE
[RFC] migration of ZoL mailing lists

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#3120]
@behlendorf , we've reached the limits with Google Groups once more and a few of us were discussing on IRC a possible migration from Google Apps to another service. 

Since I've got a few servers available with lots of space, bandwidth and a company policy that loves to give resources for ZFS development, I was offering one.

* The server is in Canada
* 100mbit throughput, 5TB monthly bandwidth
* ~200G disk space

I was initially considering configuring mailman as the software, because it is used for LKML and others on IRC called it the _de-facto_ standard. 

## Suggestion 1: Move entirely away from Gapps
It was brought to my attention that because the entire zfsonlinux.org website and email are hosted in Google Apps, it may be necessary to move all the email and websites from Google Apps to a comparable infrastructure on my network.

## Suggestion 2: Move only the mailing list
Instead of moving the entire zfsonlinux.org domain it could be more reasonable to just create a new @list.zfsonlinux.org and point an MX record for 'list.zfsonlinux.org' to my network and leave 'zfsonlinux.org' as it is... Then, create a Google Mail forward for zfs-discuss@zfsonlinux.org and other mailing list accounts to point to mailing-list@list.zfsonlinux.org and so on.

## What is set up:

* Horde for webmail / activesync
* Dovecot with sieve filtering for IMAP
* VimbAdmin for mailbox admin, so you can add / remove users and aliases or domains

There's effectively no limits to this setup and I can set up an independent FreeBSD jail to give ssh access to @behlendorf  and @FransUrbo or other trusted contributors who would like to administer the mailing list.

The steps to migrate would be:

1. Set up the list.zfsonlinux.org domain and accounts (zfs-discuss, zfs-devel), test it

2. Set up mailman with list.zfsonlinux.org

3. Import the subscriber list from Google Groups and send out new, temporary passwords

4. Forward the old list to the new list

There's a potential for importing old discussions from Google Groups but as far as I've been able to find, they do not provide simple export function for group data so there's no EASY way to get it without screen scraping or importing some Mbox / Maildir equivalent... I've heard from several users in #zfsonlinux that they would be perfectly happy leaving the group history on Google as an "archive", and not importing much at all.

Comments and suggestions are welcome, I'd like to help out but also do this in a seamless and reasonable way that requires the least effort from all participating parties, so hopefully it will result in the least disruption.

**Comment by dasjoe** [comment]
What about setting up a [discourse](http://www.discourse.org/) to replace the old mailing list?

It can be used by email just like a ML, if I'm not mistaken:
![email](https://meta-discourse.global.ssl.fastly.net/uploads/default/_optimized/a5e/f2c/cadd5612a4_690x187.PNG)

That way we'd have a usable web interface, too.

* [Install instructions](https://github.com/discourse/discourse/blob/master/docs/INSTALL.md)
* [Simple installation with Docker](https://github.com/discourse/discourse/blob/master/docs/INSTALL-digital-ocean.md)
* [Adding e-mail support](https://meta.discourse.org/t/set-up-reply-via-email-support/14003)

**Comment by snajpa** [comment]
vpsFree.cz (https://vpsfree.cz, nonprofit org, we're heavy ZFS users) would be happy to provide virtual servers for ZoL. They are OpenVZ containers, 4G RAM, 60G disk, IP4/6 on a gig uplink, with daily incremental backup.
The only gotcha here is that somebody from the community would need to manage the server(s), as we as a non-profit don't have enough resources (manhours) to take care of that.

**Comment by behlendorf** [comment]
I'm all for abandoning Google groups.  Early on it was a nice easy way to manage the mailing list but we've clearly out grown it.  Moving to a dedicated server running mailman would definitely be a step in the right direction.

@dasjoe I don't know much about discourse but I'm a little wary.  Using a service like that is how we ended up getting stuck in Google Groups originally.  I'd hate to end up tied to discourse, sticking with the De-facto standard mailman seems like the way to go.  And I think giving a couple trusted people access to that infrastructure is an excellent idea.

Personally I'm in favor of suggestion 1 and I don't think it will be too hard.  The only thing running as a gapp is the mailing list.  The website is hosted by Githib and while we could definitely move it as well I'm inclined not to unless we have a good reason.  Since the mailing list is already at a custom domain once the new lists are setup and the subscriber list imported my understanding is we just need to update the MX record.  Although managing this sort of thing isn't my strong suit!

I'd also suggest we take this opportunity to retire the zfs-devel list in favor of the OpenZFS developer list.  The only other caveat, which I'm OK with and was already mentioned, is that it's probably easiest to just abandon the archive at Google Groups.

@kpande if you can handle steps 1-3 and get everything ready to cut over then I can update the MX record when we're ready.  We need a zfs-discuss and zfs-announce list.  This _should_ be fairly seamless.  We should also make sure to update http://zfsonlinux.org/lists.html accordingly.

**Comment by tomposmiko** [comment]
In my opinion the best place for a list would be kernel.org. Why don't we use that?

**Comment by kpande** [comment]
I'm with Tom if we can get the ML set up using LKML, but seeing how there's disagreements with licensing that may not be the most appropriate place for ZFS discussions. After all, ZFS has to stay far away from Linus' kernel.

@behlendorf  I can do all the mailman configuration, I will just need the subscriber list.

**Comment by kpande** [comment]
Once it's up and available I won't ever pull the plug without giving 3 months' notice for migration efforts to another server - and mailman should be infinitely easier to move than Google Groups :+1:

**Comment by prakashsurya** [comment]
@kpande If it's set up on a ZFS dataset, that'd make it easy to use send/recv for backups! :)

**Comment by kpande** [comment]
I'm planning on setting this up on Sunday

**Comment by behlendorf** [comment]
Using the vger.kernel.org lists would be nice but I don't think it's appropriate.  Those lists are focused on developer issues and I think it's fair to say the ZoL ML are more user centric.

@kpande drop me an email at behlendorf1@llnl.gov and I'll send you the subscriber list.

**Comment by tomposmiko** [comment]
On 02/20/2015 04:11 PM, kpande wrote:
>
> I'm with Tom if we can get the ML set up using LKML, but seeing how 
> there's disagreements with licensing that may not be the most 
> appropriate place for ZFS discussions. After all, ZFS has to stay far 
> away from Linus' kernel.
>

@kpande, have you successfully created the list? Let me know, if I can help.

**Comment by kpande** [comment]
all done and set up! 

http://list.zfsonlinux.org

Just waiting for @behlendorf to set up the final MX records to redirect from Google Groups tomorrow

**Comment by prakashsurya** [comment]
Nice!!

So, what's the transition going to be for an end user?Does everybody need to sign up for the new list, or will that be handled automatically? And, will the old google group be marked read-only? (not sure if that's possible, but I'd hate to see fragmentation with some users still using the old list)

**Comment by behlendorf** [comment]
Hopefully it will be pretty seamless, I sent [this notice](https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-announce/9M5H3XtAem4) to the zfs-announce, zfs-discuss, and zfs-devel lists.  But just to be clear...

> Does everybody need to sign up for the new list, or will that be handled automatically?

Everybody who was subscribed to the Google Groups was automatically subscribed to the new lists.  They _shouldn't_ need to do anything.

> will the old google group be marked read-only?

Yes, they were set read-only when we cut over.  Since it wasn't trivial to export the archive and bring it over to mailman we abandoned it in place but it will still be available for reference.  It would be great to pull that archive over to mailman at some point, but that's going to take a little work and we needed want to have that hold up the migration.

**Comment by dasjoe** [comment]
As just discussed on #zfsonlinux, most if not all messages to the list now turn up in Gmail's spam folder.

To fix it mailman has to rewrite `From:` and list.zfsonlinux.org needs a DMARC record: https://support.google.com/a/answer/2466563?hl=en
