### ISSUE TITLE
New mailing list: long delay before mails get sent

### ISSUE THREAD

**Issue by dasjoe** [zfsonlinux/zfs#3149]
There's a large delay before mails are being processed, as seen in the headers:
```
Received: from megatron.tripleback.net (tripleback.net. [67.230.161.10])
        by mx.google.com with ESMTP id u7si624313qat.29.2015.03.03.05.55.09;
        Tue, 03 Mar 2015 05:55:11 -0800 (PST)
Received: from tripleback.net (localhost [127.0.0.1])
	by megatron.tripleback.net (Postfix) with ESMTP id D2DA87F871;
	Tue,  3 Mar 2015 08:54:47 -0500 (EST)
Received: from zeona.lv (roze.lv [213.175.74.1])
 by megatron.tripleback.net (Postfix) with ESMTP id 5F2DC7E96B
 for <zfs-discuss@list.zfsonlinux.org>; Tue,  3 Mar 2015 07:01:06 -0500 (EST)
Received: from MasterPC (unknown [194.19.225.226])
 by zeona.lv (Postfix) with SMTP id 22E5820055EB8
 for <zfs-discuss@list.zfsonlinux.org>; Tue,  3 Mar 2015 14:01:04 +0200 (EET)
```

So `megatron.tripleback.net` got the mail at 07:01:06 -0500 (EST) and processed it at 08:54:47 -0500 (EST), `mx.google.com` received it at 05:55:11 -0800 (PST), nearly two hours after it was originally sent.

The delay is variable, but seems to be longer than one hour most of the time.

**Comment by kpande** [comment]
There's been a lot of deferred mail from Google accounts that no longer exist, because Google does not expire old gmail accounts from the group user list (apparently)

When importing into a different system, the list had to deal with a ton of inactive addresses. It's been clogging up the queue and reattempting delivery so frequently that it prevents new mail from being delivered,as described here: http://www.postfix.org/TUNING_README.html#hammer

**Comment by kpande** [comment]
Oh, and Google is rate-limiting all the mail to valid addresses, too, because users haven't marked it as not being spam.

**Comment by kpande** [comment]
It's been fixed by switching to VERP mode in Mailman - this will send an individual message per recipient instead of one message with X number of recipients. It may be harder on the network but it's certainly been easier on the mailserver.
