### ISSUE TITLE
blk_unplug delay - high latency

### ISSUE THREAD

**Issue by hhhappe** [zfsonlinux/zfs#3398]
Hi,

OS: CentOS 6.6
ZFS: 0.6.4.1
SPL: 0.6.4.1

I found the latency of an ioping test to be higher than expected. This is a ZFS fs on one SSD disk:

ioping -WWW /zfs/file
4.0 KiB from /zfs/file (zfs zfs): request=1 time=2.4 ms
4.0 KiB from /zfs/file (zfs zfs): request=2 time=2.8 ms
4.0 KiB from /zfs/file (zfs zfs): request=3 time=2.9 ms

ioping directly to the device or on top of ext4 gives the expected ~100us latency.

I've investigated with btrace and found that blk_unplug is not triggered, until timeout:

  8,112  0      167     4.009409364  6309  A   W 41472 + 32 <- (8,113) 39424
  8,112  0      168     4.009410451  6309  Q   W 41472 + 32 [z_wr_iss/5]
  8,112  0      169     4.009411984  6309  G   W 41472 + 32 [z_wr_iss/5]
  8,112  0      170     4.009413594  6309  P   N [z_wr_iss/5]
  8,112  0      171     4.009414297  6309  I   W 41472 + 32 [z_wr_iss/5]
  8,112  0      172     4.011926785     0 UT   N [swapper] 1
  8,112  0      173     4.011931787   106  U   N [kblockd/0] 1
  8,112  0      174     4.011932297   106  D   W 41472 + 32 [kblockd/0]
  8,112  0      175     4.012571581     0  C   W 41472 + 32 [0]

This is output from ext4. Scheduler also noop:

  8,80   0        9     2.000339950  6488  Q  WS 274432 + 8 [ioping]
  8,80   0       10     2.000340643  6488  G  WS 274432 + 8 [ioping]
  8,80   0       11     2.000341204  6488  P   N [ioping]
  8,80   0       12     2.000341473  6488  I  WS 274432 + 8 [ioping]
  8,80   0       13     2.000342552  6488  U   N [ioping] 1
  8,80   0       14     2.000342991  6488  D  WS 274432 + 8 [ioping]
  8,80   0       15     2.000403533     0  C  WS 274432 + 8 [0]

Then I tried ZFS on top of an ext4 file, then I get ~300us. Not as good but close enough given the extra layer.

I'm far from an expert on blkdev queuing, but my understanding is that it should be unplugged if something is waiting for it.

OBSERVATION: If you give ioping a ZFS dir instead of a file it will create a file for the testing. However, it will unlink the file right after it has opened it. This makes ZFS disable sync to disk, which makes sense because it will not be available in case of a crash.

I'm just wondering if it is intentional and up to standards. One might argue that data could be found with a bit of forensics.

**Comment by hhhappe** [comment]
Probably belongs to SPL, so I moved it there.

**Comment by behlendorf** [comment]
@hhhappe thanks for digging in to this.  It does look like we might want to add some code to explicitly unplug the request queue.  This might be complicated a bit in ZFS since the IO won't be handled by the process which made the syscall, and that will likely break the kernel's IO tracking.

As a quick test I made the following tweak to vdev_disk_io_flush() which should unplug the queue immediately and flush the blocks to disk.  However, I saw no improvement in my testing so this clearly should be investigated further.

```diff
diff --git a/module/zfs/vdev_disk.c b/module/zfs/vdev_disk.c
index 0196f39..531f325 100644
--- a/module/zfs/vdev_disk.c
+++ b/module/zfs/vdev_disk.c
@@ -652,6 +652,11 @@ vdev_disk_io_flush(struct block_device *bdev, zio_t *zio)
        bio->bi_bdev = bdev;
        zio->io_delay = jiffies_64;
        submit_bio(VDEV_WRITE_FLUSH_FUA, bio);
+
+       spin_lock(q->queue_lock);
+       blk_run_queue_async(q);
+       spin_unlock(q->queue_lock);
+
        invalidate_bdev(bdev);
 
        return (0);
```

**Comment by hhhappe** [comment]
0.6.5-1 solved this for the single disk case and mirror. However, ext4 is still faster.

EXT4
single SSD: ~80us
MD mirror: ~80us

ZFS
single SSD: ~120us
mirror: ~180us
single rust: 8.5ms
18 disk raidz2: sometimes ~70ms, sometimes ~250ms.

So, multiple disk is not so good.

**Comment by behlendorf** [comment]
@hhhappe thank you for updating this issue, commit b39c22b73c0e8016381057c2240570f7af992def resolved the primary root cause.   You should be able to improve ZFS performance further by adding a fast SSD log device.  This is particularly valuable for the raidz2 configuration.

For a single disk head-to-head comparison I'd expect ext4 to do better since it has the advantage of only needing to update a single block on disk.  Due to ZFSs data-integrity guarantees we need to write a little more to disk.
