### ISSUE TITLE
Question: Anyone running Fedora 21 (kernel 4.0.4) or Fedora 22 with 0.6.4.1?

### ISSUE THREAD

**Issue by HeinzApfel** [zfsonlinux/zfs#3456]
Hi,

as it is not in the supported system list, I would like to ask if anyone is already running kernel 4 or Fedora 22 with 0.6.4.1 on a stable system?

Thanks,
Heinz

**Comment by tscholak** [comment]
I do. Works.
```
[root@poopmonger ~]# uname -a
Linux poopmonger.schofik.home 4.0.4-201.fc21.x86_64 #1 SMP Thu May 21 15:58:47 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@poopmonger ~]# yum list installed spl zfs
Loaded plugins: auto-update-debuginfo
Installed Packages
spl.x86_64                                                      0.6.4.1-1.fc21                                                      @zfs
zfs.x86_64                                                      0.6.4.1-1.fc21                                                      @zfs
```

**Comment by danielkza** [comment]
I'm running 4.0.4 and seemingly fine after upgrading from F21 to F22. The F22 repo isn't up yet though, so you have to manually edit the repo file after the upgrade to force the version to 21, or miss any possible updates.

**Comment by maci0** [comment]
runs fine here.
just the dkms stuff doesnt seem to automatically rebuild the modules when upgrading a kernel, so i do that manually invoking dkms install spl/xxxxxx etc...
havent had the time to track down the root cause tho

**Comment by jmpolom** [comment]
I also experienced what seem to be DKMS-related problems with spl and zfs 0.6.4.1-1.fc21 on Fedora Server 21 with kernel version 4.0.4-202.fc21, as previously reported. Running `dkms status` resulted in output saying DKMS could not find the dkms.conf. Re-installing the packages will temporarily fix this issue for me, until the next kernel update when DKMS will again fail to run and modules won't be built for the kernel. No modules obviously means zfs will fail to start.

I'm unsure exactly what causes this problem, but I'm able to provide more technical information if it will help solve the problem.

**Comment by danielkza** [comment]
@jmpolom I had that happen to me once when I accidentally interrupted the post-installation script during an upgrade. I reinstalled, as you mentioned, and had not have it happen again since. The only kernel upgrade I've gotten so far on F22 from `4.0.4-301` to `4.0.4-303.fc22.x86_64` worked correctly.

I still find it strange though, since the `dkms.conf` should be part of the package contents. I'd guess the file is actually present but something else confused DKMS after an aborted compilation.

**Comment by tscholak** [comment]
@jmpolom That happened to me too. I found that deleting broken symbolic links in `/var/lib/dkms/spl/` and `/var/lib/dkms/zfs/` can solve the problem.

**Comment by jmpolom** [comment]
There don't appear to be symlinks in either of those directories for kernel-4.0.4-202[...], but there are symlinks for kernel-3.18.7-200[...] and kernel-3.19.7-200[...]. These symlinks point to directories with kernel modules in them. They're definitely not broken links.

It looks like DKMS isn't running for kernel 4.0.4 based on this though? Deleting those other symlinks would seem to only remove references to the modules built for the respective kernels. If I use these older kernels, zfs loads/mounts fine so I'm assuming you're suggesting to delete these links.

In your experience has deleting the symlinks for older kernels forced DKMS to build the kernel modules on 4.0.4?

**Comment by tscholak** [comment]
This is indeed how I remember it. After deleting older or broken links, DKMS would not complain about missing config files anymore and proceed with building for the new kernel.

**Comment by maci0** [comment]
I just remove all of /var/lib/dkms/* and reinstalled the zfs/spl packages. That did fix the missing dkms.conf error message.
I still had some old stuff in there from F19 ...

**Comment by jmpolom** [comment]
Confirming that removing old pre-kernel 4.0.4 stuff in /var/lib/dkms for spl and zfs did the trick. A yum reinstall for spl-dkms and zfs-dkms results in modules built and correct links /var/lib/dkms. dkms status returns correct information about the spl and zfs versions installed/registered with DKMS.

**Comment by behlendorf** [comment]
Official release and testing repositories are now available for Fedora 22.

Regarding the DKMS issues it would be helpful if someone who's hit these problems could run them to ground so we could ensure things are always reliable.

**Comment by three3q** [comment]
can confirm problem after fedup 20->21 still exists. had to reinstall spl zfs and then manually yum reinstall for spl-dkms and zfs-dkms.

**Comment by sparksh** [comment]
After upgrading from Fedora 22 to Fedora 23, zfs modules were not rebuilt. In fact, I can't recall that dkms updates or upgrades ever worked for me. I've always had to re-install the packages and/or delete files in /var/lib/dkms.

I opened the associated rpms to look at the spec files. There is a section to clean up the /var/lib/dkms directories:

```   
%preun
echo -e "Uninstall of %{module} module (version %{version}) beginning:"
dkms remove -m %{module} -v %{version} --all --rpm_safe_upgrade
exit 0
```

If this actually happens, I don't see how all the old stuff we see remains in /var/lib/dkms.

**Comment by sparksh** [comment]
(Continuing from previous post)

Later the same day a bunch of updates came in for F23 that included a new kernel.
This time, I tried to pay attention.

Currently:
```
kernel-4.3.5-300.fc23.x86_64
zfs-dkms-0.6.5.4-1.fc23.noarch
```
Pending update:
```
kernel-4.3.5-300.fc23.x86_64
```
Directory /var/lib/dkms/zfs before update:
```
0.6.5.4/
kernel-4.3.5-300.fc23.x86_64-x86_64 -> ...
```
Now "dnf update"...

Directory /var/lib/dkms/zfs before reboot:

```
0.6.5.4
kernel-4.3.5-300.fc23.x86_64-x86_64 -> ...
kernel-4.4.2-301.fc23.x86_64-x86_64 -> ...
```

Directory /usr/src before reboot:

```
kmods/
debug/
kernels/
spl-0.6.5.4/
zfs-0.6.5.4/
```

The spl and zfs directories both contain dkms.conf files.

In previous situations, I found that dkms.conf was missing from older directories
in this location. (There was a theory prevailing then that old versions remaining
in /var/lib/dkms went after these sources and derailed when dkms.conf was missing.)

Now reboot...

_Everything works fine._
I checked the dkms logs and the actual module dates to make sure it really happend.

I only had one version of zfs in /var/lib/dkms because of past manual cleanups.
The next time zfs gets updated, I'll post the results. And then we have the case where
both the kernel and zfs get updated. That definitely didn't work for me a few days ago when
I went from F22 to F23.
