### ISSUE TITLE
Can't remove SA xattr when xattr=on

### ISSUE THREAD

**Issue by nedbass** [zfsonlinux/zfs#3472]
If a file has an SA-based xattr but the dataset has `xattr=on` set, the SA-based xattr cannot be removed.

```
$ zfs get xattr rpool/satest
NAME          PROPERTY  VALUE  SOURCE
rpool/satest  xattr     sa     local
$ touch /rpool/satest/ZZZ
$ setfattr -n user.foo -v ZZZ /rpool/satest/ZZZ
$ getfattr -n user.foo  /rpool/satest/ZZZ
getfattr: Removing leading '/' from absolute path names
# file: rpool/satest/ZZZ
user.foo="ZZZ"

$ zfs set xattr=on rpool/satest
$ setfattr -x user.foo /rpool/satest/ZZZ
setfattr: /rpool/satest/ZZZ: No such attribute           <--------- this should succeed
$ getfattr -n user.foo  /rpool/satest/ZZZ
getfattr: Removing leading '/' from absolute path names
# file: rpool/satest/ZZZ
user.foo="ZZZ"

$ zfs set xattr=sa rpool/satest
$ setfattr -x user.foo /rpool/satest/ZZZ
$ getfattr -n user.foo  /rpool/satest/ZZZ
/rpool/satest/ZZZ: user.foo: No such attribute
```

**Comment by lundman** [comment]
I noticed this when we added xattr=sa to OSX. It has some other situations as well (if I remember correctly, having the same xattr in both SA and "on" could lead to doubles when listing).

It felt like xattr=sa should be a creation-time setting, and going from xattr=sa to xattr=on is not supported. But since you bring it up here, perhaps that wasn't intentional.. ?

**Comment by nedbass** [comment]
I believe the intention is/was to support switching back and forth. There are situations where it will fall back to a directory-based xattr anyways. If the total size for all xattrs on a file gets too big (I think more than half the maximum block size?).

**Comment by dweeezil** [comment]
I've got a patch in one of my branches that starts trying to make it work more sensibly. I'll try to dig it up

On June 5, 2015 10:40:22 AM CDT, Ned Bass <notifications@github.com> wrote:
>I believe the intention is/was to support switching back and forth.
>There are situations where it will fall back to a directory-based xattr
>anyways. If the total size for all xattrs on a file gets too big (I
>think more than half the maximum block size?).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zfsonlinux/zfs/issues/3472#issuecomment-109333572

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dweeezil** [comment]
The patch I was working on is at https://github.com/dweeezil/zfs/tree/xattr-sa.  One of the first issues I was trying to address is the apparent duplicates seen when iterating the xattrs and when the same xattr exists as an SA xattr and a dir-style xattr.

**Comment by mmehnert** [comment]
@dweeezil  Have you tried that patch in production? 
I'm having troubles with a samba server with very intensive xattr-usage for the Windows-ACLs (I can no longer set permissions on directories with very high numbers of files since the icacls command fails with an "unexpected network error" after some hours.)
I've used xattr=sa some versions back but ran into problems (duplicate xattrs ...). 
If I read your patch correctly, it will replace xattrs according to the current xattr setting whenever they are changed / when zpl_xattr_set is called. That still does not seem to be the case in the current official code base...
So should I risk it? ;-)

**Comment by mmehnert** [comment]
0e085663605af25d41b0f48a9ba146aa368de9b1 looked straight forward enough to me so I just went with it. So far it works as advertised. Is there something missing that prevents it from inclusion?

**Comment by mmehnert** [comment]
@dweeezil I just saw that in #2686 you said "IIRC, the main issue I've got with this patch is that it doesn't clean up the xattr directory when transitioning from directory-style to SA-style." 
Is that something serious? ;-D Should I revert to a backup?

**Comment by dweeezil** [comment]
@mmehnert I've not exercised the patch very thoroughly and, quite honestly, it's been quite awhile since I wrote it.  AFAIK, it ought to be safe and leaving the empty xattr directory laying around should not cause any problems.  I think the main reason I didn't post a pull request as-is is because I wanted to make this patch part of a larger rationalization of sa-versus-dir xattrs, possibly including additional values of the xattr property to provide for more fine-grained control over the manner in which transitions between xattr=on and xattr=sa are handled.  At this point, I suspect you've given it more of a workout than I ever did :)

**Comment by mmehnert** [comment]
@dweeezil 
Ok. Then I'll continue using it. A windows client is currently constantly changing ACLs  for about 12 hours now without problems and manually checking the xattrs yields the expected result (no duplicates).
Thanks!
