### ISSUE TITLE
Use also /dev/mapper in init script to import pools

### ISSUE THREAD

**Issue by mkjorling** [zfsonlinux/zfs#3536]
This is about `/etc/init.d/zfs-mount` on Debian, as provided by the `zfsutils` package (package version 0.6.4-1.1-2-wheezy).

When USE_DISK_BY_ID = "yes", the directories searched for devices are `/dev/disk/by-vdev`, `/dev/disk/by-*` (as expanded) and `/dev`, in that order.

If specific vdev aliases are not set up through /etc/zfs/vdev_id.conf, this risks leading to unpredictable device name picking on import. This is particularly ugly when ZFS is backed by LUKS devices (as described for example at [\[1\]](http://serverfault.com/a/588056/58408), [\[2\]](https://help.ubuntu.com/community/encryptedZfs#ZFS_on_LUKS_Installation)), where (in my case) ZFS picked the name `dm-uuid-CRYPT-LUKS1-${LUKSUUID}-${CRYPTDEVICE}_unformatted` rather than the name I set up in /etc/crypttab, despite the latter being the name I used when setting up the pool with the devices.

**By adding `/dev/mapper` immediately after `/dev/disk/by-vdev` on line 57 of /etc/init.d/zfs-mount**, the cryptdevice names set up in /etc/crypttab are displayed in the pool status.

In my testing this does not appear to cause any problems even with pools with mixed LUKS and non-LUKS/non-DM devices, but caveat emptor.

Being configured by the administrator, it appears reasonable to treat the names in /dev/mapper the same as the names in /dev/disk/by-vdev (as preferential), and use other /dev/disk/by-\* and /dev as fallback.

**Comment by FransUrbo** [comment]
> This is about /etc/init.d/zfs-mount on Debian, as provided by the zfsutils package (package version 0.6.4-1.1-2-wheezy).
> 
Then this issue belong to the https://github.com/zfsonlinux/pkg-zfs/ repo.


The init scripts in ZoL (this repo) have been modified and slightly rewritten in comparation to the ones in the released package. The dailies have these new scripts though.

I'm a little unwilling to modify or do ANYTHING to the released packages, so I'm not (unfortunately) going to fix this in those packages. I will however submit a PR for the ZFS repo, so it can get integrated into ZoL correctly and then merge into the dailies. Thanx for the report and pointer, I DO appreciate it.

Once 0.6.5 is release, those released packages will contain all this new stuff.

Until then, I'm afraid you have to modify your own initscripts.
> In my testing this does not appear to cause any problems even with pools with mixed LUKS and non-LUKS/non-DM devices, but caveat emptor.
> 
… which is why I'm unwilling to do anything about the released packages :)

**Comment by mkjorling** [comment]
As for where this issue belongs, I looked for the most appropriate place but couldn't find anything specific about where to report this.
