### ISSUE TITLE
Initramfs script resets ZFS_RPOOL and ZFS_BOOTFS with nothing

### ISSUE THREAD

**Issue by zuloo** [zfsonlinux/zfs#3564]
hello in the scipt contrib/iniramfs/scripts/zfs lines 710 to 718 reset the RPOOL and BOOTFS variables

    if [ "$ROOT" = "zfs:AUTO" ]                                                   
    then                                                                          
       ...
    else                                                                          
        # No auto - use value from the command line option.                       
        ZFS_BOOTFS="${ROOT#*[:=]}"  # Strip 'zfs:' and 'ZFS='.                    
        ZFS_RPOOL="${ZFS_BOOTFS%%/*}"   # Stip everything after the first slash.  
    fi                                                                            
  
this is done regardles of the contents fo both variables. If they are set by the kernel cmd line they get assigned a little above:

    # ------------                                                                
    # Look for 'rpool' and 'bootfs' parameter                                     
    [ -n "$rpool" ] && ZFS_RPOOL="${rpool#rpool=}"                                
    [ -n "$bootfs" ] && ZFS_BOOTFS="${bootfs#bootfs=}"                            
 
then there is a check if they are set, which sets `ROOT=zfs:AUTO` otherwise

    # ------------                                                                
    # No root fs or pool specified - do auto detect.                              
    if [ -z "$ZFS_RPOOL" -a -z "$ZFS_BOOTFS" ]                                    
    then                                                                          
        # Do auto detect. Do this by 'cheating' - set 'root=zfs:AUTO' which       
        # will be caught later                                                    
        ROOT=zfs:AUTO                                                             
        echo "doing root on zfs auto lookup"                                      
    fi

this constuct makes it neccessary to have rpool=rpool, bootfs=rpool/ROOT/distro-1 and ROOT=zfs:rpool/ROOT/distro-1 on the kernel cmd line, while rpool and bootfs should be enough

can you please add checks so the variables are not resetted to notheing if ROOT is not set, or better do not touch them at all if they are specified on the commandline

**Comment by FransUrbo** [comment]
> this constuct makes it neccessary to have rpool=rpool, bootfs=rpool/ROOT/distro-1 and ROOT=zfs:rpool/ROOT/distro-1 on the kernel cmd line, while rpool and bootfs should be enough
> 
Then you have misunderstood the code.

It's perfectly legit to ONLY have 'root=…', ONLY 'rpool=…' _or_ ONLY 'bootfs=…'. I'm also reasonably sure I've taken any combination of the three into account as well. That's why there's so much code in that section to parse this. Try it and you'll see.


However, that being said. That part (using ZFS_SNAPSHOT_BOOT and ZFS_BOOTFS_ORIG) should probably need a rewrite. The functions mount_fs(), rollback_snap() and ask_user_snap() isn't as … 'freestanding' as one could have hoped for.

But I don't want to rock the boat just jet. The code works and have been quite thoroughly tested as it is, and I prefer to have code that's as stable as possible for the impending merge of the pull request.

**Comment by rlaager** [comment]
From @FransUrbo's response, it sounds like this is not an issue?
