### ISSUE TITLE
ZFS device contains corrupted data?

### ISSUE THREAD

**Issue by zhro** [zfsonlinux/zfs#3581]
Upon calling `zpool status` I had a pool which reported:

```
One or more devices contains corrupted data
```

`zpool import pool-name` then `zpool status` did not report any errors. Performing a `zpool export pool-name` and subsequent `zpool status` then yielded no errors.

Does the pool actually have an error on one of the devices?

**Comment by behlendorf** [comment]
It sounds as if ZFS initially had some trouble detecting the location of one of your drives.  Subsequently it was able to successly locate it during the import.  Did the drive names change perhaps?

**Comment by Zhro** [comment]
None of the drives in this array were modified physically or otherwise intentionally through software. 

Prior to this problem I peformed a reboot to the system after operating for 152 days which included a kernel update. ZFS also needed to coddled a bit to get working again on the new kernel: see https://github.com/zfsonlinux/zfs/issues/3580.

Other changes include the addition of an H200A RAID card which uses the same chipset as the onboard controller. While in the BIOS configuration they seemed to talk to each other by updating an adapter list. I don't know if this was responsible for the problem or not and I'm not entirely prepared to bring this system down to try and reproduce the error.

Also of note is that I'm now using a significantly different BIOS on the RAID card which would not provide an exact duplication of the process.

Any thoughts?

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.
