### ISSUE TITLE
Have to manually reinstall zfs after kernel update

### ISSUE THREAD

**Issue by CySlider** [zfsonlinux/zfs#3716]
I have the problem described in this issue: https://github.com/zfsonlinux/zfs/issues/1155

And the fix of  @dajhorn works for me, but I have to repeat it on EVERY kernel update.

Please help. Also see this "Ask Ubuntu" topic I created for this. They proposed to ask here instead.

https://askubuntu.com/questions/667092/how-to-avoid-manually-reinstalling-zfs-after-kernel-update

Please help, I am living with this since a year now. once every 1-2 weeks I have to do this after an system update to get access to my files (which also hold my user homes)

**Comment by Bronek** [comment]
The modules included in ZFS on Linux have to be compiled and built for the specific version of kernel they are intended to run on. This is normal, it is the same limitation as all kernel modules. The small difficulty here is that ZOL modules cannot be built together with kernel, because there are not included in kernel sources, due to incompatible licenses. This means that you need to build them after you have built your kernel. The process for building dependent binaries is specific to each distribution;

I have my process for updating kernel and/or ZOL in ArchLinux, but it does *not* apply to any other distribution. It is remotely possible that concepts that I rely on have their equivalent in Ubuntu. Which means that perhaps my process will be *marginally* useful to you. Here is what I do:
* update kernel package as required (e.g. new version or patches)
* update archzfs package as required (e.g. refer to new kernel; change ZOL version or patches)
* use clean-chroot-manager (`cd linux ; sudo ccm s ; cd -`) to build new kernel in chroot64
* then build ZOL `for i in spl-utils-git spl-git zfs-utils-git zfs-git ; do cd $i ; rm *.pkg.tar.xz ; sudo ccm s ; cd - ; done`
* sign packages `for i in *tar.xz ; do gpg --detach-sign --local-user xyxyxyxy $i ; done`
* replace packages in local repository with new ones and regenerate `repo-add repo-local.db.tar.gz *.pkg.tar.xz`
* under root, install in one go both kernel and ZOL `sudo pacman -Syy --noconfirm linux spl-utils-git spl-git zfs-utils-git zfs-git`

**Comment by dajhorn** [comment]
@CySlider,

The advice given by @Bronek here and by @Pilot6 at the ASK question page applies.

This kind of glitch often happens on `debootstrap`'d systems or super-lean cloud images that are missing a metapackage.  Things like `build-essential`, a `linux-*` set, `ubuntu-minimal` are a hard requirement for reliability.

And depending on what you already have installed when you try to fix the problem, dependencies can resolve differently.  The defaults used by the Ubuntu Installer get a good result.

**Comment by CySlider** [comment]
Hmm, so if I get you right, under normal circumstances dkms should solve the problem described by @Bornek automatically, right? Thats at least what I understand that DKMS is for.

So my system is somehow messed up? I installed standard Kubuntu Trusty 14.04 I have a root partition thats not on ZFS also my root and my admin account are on the NON-ZFS.

Most fancy thing I did, beside the encryption of all disks is ZFS itself and finding the right graphics drivers.

Any additional hint for me, in which direction I can go? Maybe a command that will tell me missing packets until I reinstalled them? Reinstalling would be quite painful as I am still quite new to Linux and it would take me several days to set everything up again.

Ah and then there is the issue of the boot partition running full at times because I also have to clean-up this one manually which feels quite odd, too.

**Comment by dajhorn** [comment]
> Ah and then there is the issue of the boot partition running full at times because I also have to clean-up this one manually which feels quite odd, too.

If the system is not configured to automatically rotate old kernels, then having gigabytes of stuff in `/boot` is normal and expected behavior for a long-running Ubuntu system.

But this also suggests that some kernel run-parts are missing or disabled.  Try this:
```
# dpkg -S /etc/kernel/prerm.d/dkms  /etc/kernel/postinst.d/apt-auto-removal  /etc/kernel/postinst.d/dkms
dkms: /etc/kernel/prerm.d/dkms
apt: /etc/kernel/postinst.d/apt-auto-removal
dkms: /etc/kernel/postinst.d/dkms
```
If any of these files are missing or orphaned, then the system will not automatically upgrade itself.

When an upgrade next fails, try to manually invoke `dkms` like the run-parts do.  Something like this:

```
#  /usr/lib/dkms/dkms_autoinstaller start 3.13.0-55-generic
 * dkms: running auto installation service for kernel 3.13.0-55-generic
```
```
# dkms autoinstall -m zfs -v 0.6.4.2 -k 3.13.0-61-generic
```

If this is a manually bootstrapped system, then try comparing its package manifest against a vanilla configuration that was created by the Ubuntu Installer.  Run `dpkg --get-selections` and  `diff` the result between two machines.

**Comment by CySlider** [comment]
Thank you for your support. Sounds promising.

> If the system is not configured to automatically rotate old kernels, then having gigabytes of stuff in  /boot is normal and expected behavior for a long-running Ubuntu system.

I wish it were gigabytes. For some reason the default installation only assigned a 237MB boot partition on my 128GB SSD. I run out of space with around 5 kernels. I feel still too much of a noob to try to repartition, since its a partly encrypted disk. I will tackle this another time:

    sde                               8:64   0 119,2G  0 disk  
    ├─sde1                            8:65   0   512M  0 part  /boot/efi
    ├─sde2                            8:66   0   244M  0 part  /boot
    └─sde3                            8:67   0 118,5G  0 part  
        └─sdb3_crypt (dm-0)           252:0    0 118,5G  0 crypt 
            ├─kubuntu--vg-root (dm-1)   252:1    0 102,5G  0 lvm   /
            └─kubuntu--vg-swap_1 (dm-2) 252:2    0    16G  0 lvm   [SWAP]


> \# dpkg -S /etc/kernel/prerm.d/dkms  /etc/kernel/postinst.d/apt-auto-removal  /etc/kernel/postinst.d/dkms
> dkms: /etc/kernel/prerm.d/dkms
> apt: /etc/kernel/postinst.d/apt-auto-removal
> dkms: /etc/kernel/postinst.d/dkms

All there

> When an upgrade next fails, try to manually invoke dkms like the run-parts do. Something like this:

I will do that and report here. Thanks.

> If this is a manually bootstrapped system, then try comparing its package manifest against a vanilla configuration that was created by the Ubuntu Installer. Run dpkg --get-selections and diff the result between two machines.

I am not sure what you mean by "manually bootstrapped" but I compared it to my laptop at least.
There are a ton of differences, but this are the more interesting findings:

Only on Laptop: 
  *  bbswitch-dkms
  *  grub-gfxpayload-lists
  *  grub-pc
  *  grub-pc-bin
  *  linux-generic

Only on PC: 
 *   aptoncd
 *   build-essential
 *   caffeine
 *   grub-efi-amd64
 *   grub-efi-amd64-bin
 *   grub-efi-amd64-signed
 *   linux-signed-image-generic
 *   ppa-purge
 *   spl
 *   spl-dkms
 *   zfs-auto-snapshot
 *   zfs-dkms
 *   zfs-dkms
 *   zfsutils

**Comment by dajhorn** [comment]
If these packages are in the diff:

> * spl
> * spl-dkms
> * zfs-auto-snapshot
> * zfs-dkms
> * zfs-dkms
> * zfsutils

Then the `ubuntu-zfs` package should be there too.

The `zfs-dkms` package appears twice.  Note that multi-arch and multi-version configurations are unsupported.

**Comment by CySlider** [comment]
Yes, you are right. ubuntu-zfs is also there. And the second zfs-dkms is zfs-doc sorry...

**Comment by Bronek** [comment]
I think this might indicate where you problems are
```
Please install the linux-headers-3.13.0-62-generic package,
or use the --kernelsourcedir option to tell DKMS where it's located
```

building of ZFS requires linux-headers matching to kernel package being built (or installed).

**Comment by sempervictus** [comment]
Generally when we upgrade kernels SPL rebuilds fine, but we manually have to do a dkms build and then a dkms install for ZFS.

**Comment by CySlider** [comment]
Hi again,
Sorry for staying silent so long. I couldn't make much of the last two comments, were they directed at me?

Anyhow, I wanted to wait until I can present you the exact error message I get when this happens next time. But to my supprise, the problem seems to be gone!!

So if anyone of you fixed this THANKS. I am now on a new kernel and a new zfs package and restart worked flawlessly. I really hope this is not just a fluke.

I'm closing this issue for now.

Thanks!
