### ISSUE TITLE
Allow null pointer as mount syscall options

### ISSUE THREAD

**Issue by bjin** [zfsonlinux/zfs#3771]
I find that `docker` is not working properly with `zfs 0.6.5` (See docker/docker#16258). The docker daemon log shows that `mount` failed with `EINVAL` for a newly created `mountpoint=legacy` dataset.

I write two simple program in `C` and `Go`, and it turns out that while `mount("zroot/test", "/tmp/test", "zfs", 0, "")` would succeed, `mount("zroot/test", "/tmp/test", "zfs", 0, NULL)` will trigger `EINTVAL`. The `syscall` Go package seems to [prefer null pointer as mount options](https://github.com/golang/sys/blob/master/unix/syscall_linux.go#L821).

Additional tracing lead me to https://github.com/zfsonlinux/zfs/commit/0282c4137e7409e6d85289f4955adf07fac834f5, in `zpl_parse_options()`. What do you think of the idea to allow null `mntopts` here?

**Comment by behlendorf** [comment]
@bjin this was done intentionally to ensure certain hints were passed via mount options to the kernel via the mount helper.  Assuming NULL was invalid was a convenient way to simplify the code.  I didn't expect this to be an issue because I wasn't aware of any applications which bypassed `mount.zfs`.  We can certainly allow a NULL here but I'm curious why docker is bypassing the helper.  Without it certain zfs properties will be ignored and some other functionally won't work properly.

**Comment by aderouineau** [comment]
@behlendorf, The following 2 points in docker/docker/issues/16258 should be of interest.

@Mic92 mentions that:
> zfs mount is not an option, because selinux labels have to passed with the mount.

@bjin referenced the following snippet from https://github.com/golang/sys/blob/master/unix/syscall_linux.go#L821
> // Certain file systems get rather angry and EINVAL if you give
	// them an empty string of data, rather than NULL.

**Comment by Mic92** [comment]
mount.zfs could be an option, since it supports selinux.
I will try this one. Do you know, if this is also part of other zfs distribution such as freebsd?

**Comment by behlendorf** [comment]
The bug here has been addressed in 0.6.5.1.  But just so you're aware you can pass selinux contexts as a mount option using `-o` with ZoL.  See `mount.zfs(8)`.  Alternately you can set this as dataset properties on Linux if that's more convenient.

```
zfs mount -o fscontext|defcontext|rootcontext tank/fs
```
