### ISSUE TITLE
zfs-import script does not honor the cachefile

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#3777]
A pool should not be imported unless it is already imported on the system in the cachefile to avoid issues with multipath. I had not scrutinized the zfs-import script too closely when @FransUrbo proposed it and unfortunately, this got by me. Another Gentoo developer who setup a system with a separate pool for /home has the boot process breaking on him because the script is not finding it, but if the cachefile's contents were properly obeyed, this would not be an issue. The scanning behavior should not be the default and the script should import when it knows an import is acceptable, rather than all the time. e.g. a pool on a USB key would be auto-imported by this, which is likely not what the system administrator would want.

**Comment by FransUrbo** [comment]
> A pool should not be imported unless it is already imported on the system in the cachefile

I'm not exactly sure I understand what you're saying… Are you saying that it imports the pool TWICE?!

**Comment by Bronek** [comment]
@ryao I think you meant to say "A pool should not be *auto* imported , unless it was imported previously and such fact has been persisted in cachefile" . At least, this is what your justification seem to point to. However, this would prevent auto importing of pools which are not configured to use cachefile, or are configured to use non-standard location of a cachefile.

**Comment by ryao** [comment]
@FransUrbo The import/export is not like mounting or RAID assembly. An import says "this pool belongs to this system, so do not touch it" while an export says "this pool no longer belongs to this system and is fair game". The way that the import persists across reboots is by something called a verbatim import, which reads the details of the imported pools from the cachefile.

@Bronek People have talked about getting rid of the cachefile in the past, but it is required for things like multipath to be done sanely and no alternative is able to properly handle the semantics of the import/export mechanism. I used to think this way, but I found that the rationale for eliminating the cachefile to be invalid upon actually trying to make it work.

Rather than getting rid of the cachefile, we should be modifying our systems to better integrate with it. For instance, initramfs archives could read the cachefile from the bootfs by doing a readonly forced import, mounting the bootfs, grabbing the cachefile, unmounting, exporting and then doing the verbatim import from the cachefile. This would eliminate the need to have the cachefile in the initramfs and make things behave like they should. initramfs generators such as Gentoo's genkernel do not currently do this, but they should in the future.

**Comment by FransUrbo** [comment]
> @FransUrbo The import/export is not like mounting or RAID assembly. An import says "this pool belongs to this system, so do not touch it" while an export says "this pool no longer belongs to this system and is fair game". The way that the import persists across reboots is by something called a verbatim import, which reads the details of the imported pools from the cachefile.
> 
Still don't get it…
> For instance, initramfs archives could read the cachefile from the bootfs by doing a readonly forced import, mounting the bootfs, grabbing the cachefile, unmounting, exporting and then doing the verbatim import from the cachefile.
> 
That require the first cache file to be accurate. AND up to date! Which is the problem, they seldom are, which is why people are having problem with this. And why we want to remove it...

If the first cache file is accurate enough to import the pool, there's no NEED to get a second cache file and import it again. If the import was successful the first time, there's no need to do it again..
> This would eliminate the need to have the cachefile in the initramfs and make things behave like they should.
> 
Ok, so NOT using a cache file for the first import. Ok. But how do you import (or get to the bootfs) without one, if a import without cache file doesn't work? If it can be imported without one, then there's no point in having the cache file in the first place, which (again) negate the need to get the cache file.

**Comment by Bronek** [comment]
@ryao I do not have cachefile, and yet it works:

```
root@gdansk ~ # zpool get cachefile
NAME   PROPERTY   VALUE      SOURCE
zdata  cachefile  -          default
zpkgs  cachefile  -          default
zroot  cachefile  -          default
root@gdansk ~ # ls -al /etc/zfs
total 57
drwxr-xr-x  3 root root    9 Sep 12 16:40 .
drwxr-xr-x 59 root root  143 Sep 13 12:46 ..
-rw-r--r--  1 root root  165 Sep 12 16:17 vdev_id.conf.alias.example
-rw-r--r--  1 root root  166 Sep 12 16:17 vdev_id.conf.multipath.example
-rw-r--r--  1 root root  520 Sep 12 16:17 vdev_id.conf.sas_direct.example
-rw-r--r--  1 root root  152 Sep 12 16:17 vdev_id.conf.sas_switch.example
drwxr-xr-x  2 root root   12 Sep 12 16:40 zed.d
-rwxr-xr-x  1 root root 9355 Sep 12 16:17 zfs-functions
-rw-r--r--  1 root root 6516 Apr  6 22:58 zpool.cache.bak

root@gdansk ~ # journalctl -b -u zed
-- Logs begin at Mon 2015-04-06 19:17:21 BST, end at Tue 2015-09-15 19:35:45 BST. --
Sep 15 16:39:39 gdansk systemd[1]: Started ZFS Event Daemon (zed).
Sep 15 16:39:39 gdansk zed[3354]: ZFS Event Daemon 0.6.5-1 (PID 3354)
Sep 15 16:39:39 gdansk zed[3354]: Processing events since eid=0
Sep 15 16:39:39 gdansk zed[3357]: eid=2 class=statechange
Sep 15 16:39:39 gdansk zed[3361]: eid=1 class=statechange
Sep 15 16:39:39 gdansk zed[3364]: eid=3 class=config.sync pool=zroot
Sep 15 16:39:39 gdansk zed[3370]: eid=4 class=config.sync pool=zroot
Sep 15 16:39:39 gdansk zed[3373]: eid=5 class=statechange
Sep 15 16:39:39 gdansk zed[3375]: eid=6 class=statechange
Sep 15 16:39:39 gdansk zed[3377]: eid=7 class=config.sync pool=zpkgs
Sep 15 16:39:39 gdansk zed[3379]: eid=8 class=config.sync pool=zpkgs
Sep 15 16:39:39 gdansk zed[3383]: eid=9 class=statechange
Sep 15 16:39:39 gdansk zed[3385]: eid=10 class=statechange
Sep 15 16:39:39 gdansk zed[3388]: eid=12 class=statechange
Sep 15 16:39:39 gdansk zed[3391]: eid=11 class=statechange
Sep 15 16:39:39 gdansk zed[3394]: eid=13 class=statechange
Sep 15 16:39:39 gdansk zed[3396]: eid=14 class=statechange
Sep 15 16:39:39 gdansk zed[3398]: eid=15 class=statechange
Sep 15 16:39:39 gdansk zed[3400]: eid=16 class=statechange
Sep 15 16:39:39 gdansk zed[3402]: eid=17 class=statechange
Sep 15 16:39:39 gdansk zed[3404]: eid=18 class=config.sync pool=zdata
Sep 15 16:39:39 gdansk zed[3406]: eid=19 class=config.sync pool=zdata

```

**Comment by MrStaticVoid** [comment]
I agree with @ryao.  This is of particular important when you consider a SAN environment, where a pool may be visible to multiple hosts (this is very common in virtualization environments, and for certain high-availability setups).  You do not necessarily want the first system to boot to grab all of the visible pools.  Hosts should consult the cache to determine which pools should be imported at boot.  This is the way Solaris works, and Linux should follow.

**Comment by Bronek** [comment]
it makes sense, I was thinking about using hostid (you could mount read-only, compare hostid stored in the pool and then mount if its yours) but then it occurred to me that, I'd rather get rid of hostid and keep cachefile than other way around.

**Comment by FransUrbo** [comment]
if all you want to do is ignore ("not import") certain pools, use <code>ZFS_POOL_EXCEPTIONS</code>. That currently takes the name(s) of the pool(s), but it could very easily be extended to account for <code>*</code>.

**Comment by FransUrbo** [comment]
I still have no idea what this ticket is about! Nothing in the comments by @ryao makes any sense… !

**Comment by MrStaticVoid** [comment]
Everything @ryao has made sense, and he's right. I can see how it doesn't make sense when your plan (https://github.com/zfsonlinux/zfs/pull/3526) involves getting rid of the cachefile completely.  I wish I had seen that earlier, because it is, in my opinion, a very bad idea.  Let me explain why:

The cache file as a concept has existed since the beginning of ZFS.  From the manpage, zpool(1M), we learn that:

    Discovering all pools on system startup requires
    a cached copy of the configuration data that  is  stored
    on  the  root  file  system. All pools in this cache are
    automatically  imported  when  the  system  boots.

The contents of the cachefile are effectively controlled by which pools you import and export.  When you import a pool, its details are saved in the cache and the system will reimport the pool every time the system boots, until you export it.  There is never a need to export a pool until you are ready to import it on another system.  It was simple, and beautiful, and all of your previously imported pools could be imported with one command:

```
zpool import -c /etc/zfs/zpool.cache -a
```

This is compared to your new code which takes:

```
awk '/^do_import/ { flag=1 }; /^}/ { flag=0 }; flag { print }' /etc/init.d/zfs-import | wc -l
185
```

185 lines.

And your code is incorrect.  It tries to import all available pools.  You say you you can ignore pools by setting `ZFS_POOL_EXCEPTIONS` (funny, I don't remember that on my Solaris certification exam)--but that is neither user nor system administrator friendly.  For users: are they supposed to set the `ZFS_POOL_EXCEPTIONS` variable for every USB zpool they might insert, so that it doesn't automatically get imported at boot?

For system administrators: are they supposed to update that variable every time a new pool appears on their SAN?

So you say the variable can be modified to accept wildcards, but that just gives you the same situation in reverse.  Now I have to ask, is the user supposed to update the variable every time they plug in a USB zpool that they want mounted at boot?  Is a system administrator supposed to update that variable every time they attach a new pool to their SAN that they want automatically imported at boot?

These are exactly the sort of challenges ZFS was designed to eliminate.  It's the same reason we don't have to update `/etc/fstab` for every new ZFS filesystem we want to mount.

I say to you: we already had a solution to this problem, a cache file.  Do not eliminate it.  And let's fix the `zfs-import` service to maintain the way ZFS has always worked:  import pools based on the cache file, and **do not export pools at shutdown**.  Only the user or system administrator should export pools.

**Comment by FransUrbo** [comment]
As I said in https://github.com/zfsonlinux/zfs/pull/3800#issuecomment-141643856, the correct fix is to set:

```
ZPOOL_IMPORT_OPTS="-c /etc/zfs/zpool.cache"
ZPOOL_CACHE=""
```

in the defaults config file (<code>/etc/defaults/zfs</code> or corresponding location on Redhat/Fedora etc).

That setup will *enforce* the use of cache file, and ONLY use the cache file (i.e., try once with that ONLY).

**Comment by MrStaticVoid** [comment]
And as I said in https://github.com/zfsonlinux/zfs/pull/3800#issuecomment-141687925, @FransUrbo's suggested fix doesn't work because:

1. The current infrastructure exports pools at shutdown, which completely negates the point of the cache.
1. Unless made the default, the current infrastructure is still vulnerable to https://github.com/zfsonlinux/zfs/pull/3526#issuecomment-141617698 and the number of issues raised by @ryao in this issue.

**Comment by ryao** [comment]
The following patch to make genkernel load from the cachefile in the pool will be merged  to genkernel after review has been completed:

https://gitweb.gentoo.org/proj/genkernel.git/commit/?h=zfs&id=00e8b41e573acbebd60275792eb6b4a89b834882

There are some edge cases that need to be addressed (like multiple pools with the same name), but at the moment, I am not aware of anyone handling those and it will not block merging the new code.

For systems where an initramfs is not used to load the pool, the boot scripts should just load from the cachefile. It should be a fairly simple matter since they already have access to the cachefile. I am fairly confident that the cachefile issues that people have had are caused by the initramfs have its own copy of the cachefile.

**Comment by FransUrbo** [comment]
I don't see the point of doing it this way! If the root pool could be imported read only, why bother with all this??

**Comment by FransUrbo** [comment]
Also, it doesn't take that fact into account - there's no check for a failed import!

**Comment by FransUrbo** [comment]
Oh, and the third problem is that if the ro import succeeded, but there is no cache file in there (because user have elected not to have one), everything fails… Even though the pool could be imported!

**Comment by Bronek** [comment]
@ryao I like this approach.

> I don't see the point of doing it this way! 

... the pool might be unusable for read-write, e.g. because it is SAN and is accessed by a different node at this time. I can think of other reasons. This does should not prevent reading one file in well known location, though.

> Also, it doesn't take that fact into account - there's no check for a failed import!

good point

> Oh, and the third problem is that if the ro import succeeded, but there is no cache file in there

also good point, but this probably calls for a different boot switch. There are basically two approaches and I like one presented by @ryao better than what ZOL is doing now, i.e. trying to import all available pools (including those in ZVOLs)

**Comment by FransUrbo** [comment]
If you don't want _any_ pools to auto import at boot up (other than the root pool), just don't enable the <code>zfs-import</code> script!

If you want a subset of all available pools to import and you don't want to (or can't) setup exceptions, ok, that is a problem.

But there's a much better way to do this than to rewrite the whole shebang (which works for the large majority as it is).

BTW, Most (all?) distributions have (not Gentoo??) have always required <code>root=ZFS=\<dataset\></code> (or something to that effect). That is nothing new. Granted, Debian GNU/Linux (and deviated distributions) also require a <code>boot=zfs</code>, but that's only to avoid putting absolutly every single conceivable option into ONE, humongous script (which I personally find retarded! :).

**Comment by Bronek** [comment]
> If you want a subset of all available pools to import and you don't want to (or can't) setup exceptions, ok, that is a problem.

there you go. My /boot is ext2, my root and few selected filesystems are ZFS and, unfortunately, I often at the time of startup have other ZFS pool attached which I am not comfortable importing (e.g. because they are in ZVOLs , or because I left USB attached when starting etc.). It might be unusual scenario (but I think that it's not, naiively perhaps) and one which, apparently, cachefile is designed to serve best. I am not saying that other use cases are not better server by auto-import. FWIW my distribution is ArchLinux, and the active maintainer of ZFS modules there is not very active on this list, so I will probably have to massage the scripts myself. For this I really, *really* need to understand what I'm doing.

**Comment by FransUrbo** [comment]
If there's only a few, known, pools (which it sounds like) that you don't want imported, use <code>ZFS_POOL_EXCEPTIONS</code>.

In #3559, I've now added a <code>ZFS_POOL_IMPORT</code> variable which does exactly what you want - it is a list of pools to auto-import.

**Comment by ryao** [comment]
@fransurbo The check for a failed import will be added among other changes.

As for editing configuration files, it should not be necessary. The zpool import command should make all the changes to ensure a persistently imported pool. That is how it works on Illumos, FreeBSD and systems systems. Gentoo is going back to this soon. It should not work any other way by default.

**Comment by ryao** [comment]
@FransUrbo There is code in genkernel that will allow people to drop to a shell and execute a manual import of the pool if the import process fails due to the root pool being absent from the cachefile. I am looking into including instructions to handle the missing cachefile case as that is a real concern. In particular, telling the user to execute `zpool import -N $pool` in the shell, press Cntl+D and execute `zpool set cachefile= $pool` (space after =) as root after the system has booted.
