### ISSUE TITLE
Question regarding updating zfs and concurrent kernel updates

### ISSUE THREAD

**Issue by Zhro** [zfsonlinux/zfs#3790]
When updating zfsonlinux for CentOS 7 from a yum update, do I have to worry about pools going offline during this process? Should I export all pools before performing an update?

If I peform a yum update from 6.4 to 6.5 which also includes a kernel update, zfs will build for the currently loaded kernel. When I reboot do I then have to then reinstall zfs for it to recompile the LKM?

**Comment by siebenmann** [comment]
The following is based on my experience on Fedora, but I believe it should work the same on CentOS 7.

If you use DKMS-based ZoL packages, the *current* ZFS and SPL modules will be automatically rebuilt for the new kernel when you install a kernel update. This assumes that all goes well; you should watch the yum output during the update for any indication of problems (such as error messages from dkms).

Installing a new version of the ZoL packages will rebuild the kernel modules for the current kernel (but not for any other ones, including a new kernel update that you just installed). It does not and cannot activate those new modules immediately, because the old/currently loaded modules are in use to support your mounted pools. Generally rebooting is the best way to activate the new modules. My habit is to reboot immediately after updating ZoL modules but I don't think this is absolutely required; on the other hand, I don't see any reason to apply a ZoL update much before you're going to reboot a machine to activate the update.

This means that if you want to update both the ZoL packages and the kernel packages, you should update ZoL first, then update the kernel. If you do it the other way around, you will wind up with your new kernel using old ZoL modules. You can fix this with manual dkms commands to force module rebuilds and reinstalls for the new kernel.

**Comment by DeHackEd** [comment]
Note that this is a bug tracker, not a support forum. This question is better suited for the mailing list. Please close this issue.
