### ISSUE TITLE
Mimic BSD behavior when importing pools

### ISSUE THREAD

**Issue by FireDrunk** [zfsonlinux/zfs#3892]
Recently i've helped out some guys that had problems with a pool that was imported in a corrupt state.
It looked like the pool was imported with the wrong device links because the user had swapped out cables with different disks that belonged to different ZFS pools.

In BSD this action (swapping cables) doesn't result in a corrupt imported pool, but it rather falls back on the /dev/diskid/ device links. It looks like it doesn't use the zpool.cache as 'strictly'  as ZoL does.
After import/export the zpool.cache still contains the old /dev/ada0 links but it still imports the pool thrue the /dev/diskid/ links.

Is it possible to mimic this behavior in ZoL?

I don't know where to look exactly in the code to find the spot where the exact 'recognition' code is for this behaviour, otherwise i would have looked deeper into the issue.

**Comment by ryao** [comment]
This is something that I expect to do later this year.

**Comment by FireDrunk** [comment]
Is it something i can help with? I would gladly help out.

**Comment by FransUrbo** [comment]
Using <code>/dev/disk/by-id</code> and probe devices instead of using the cache file is/have been what we've told users to do on Linux in the past.

**Comment by FireDrunk** [comment]
But can a user force ZoL to disregard the zpool.cache file?

**Comment by FransUrbo** [comment]
Yes. The current versions (since <code>0.6.5</code> of ZoL usually ships with SYSV init scripts and a config file for those as <code>/etc/{default,sysconfig}/zfs</code>. In that, you can set <code>ZPOOL_IMPORT_PATH</code> and set <code>ZPOOL_CACHE</code> to an empty value.

If you're using <code>systemd</code>, then disable the <code>zfs-import-cache.service</code> service and it will instead use the <code>zfs-import-scan.service</code>.

**Comment by FireDrunk** [comment]
Is it a good idea to propose those changes as being the default for the next version?

**Comment by ryao** [comment]
@FransUrbo That behavior is only present on Debian. It has been removed from Gentoo and its derivatives because it caused regressions. The systemd unit files do not use it either. I am not aware of any other distributions that use that behavior.

@FireDrunk My plan is to make the zpool command search for symlinks in /dev/disk/by-id and use those instead of the short names when given short names. Then when the pool is loaded from the cachefile, the symlinks will be used. In terms of helping out, you could export your pool, import it with `-d /dev/disk/by-id` and report any instances in which the cachefile reverts to using the short names. My understanding is that this only happens with initramfs archives that attempt to import the pool rather than load the in-kernel state from the cachefile.

**Comment by ryao** [comment]
@FireDrunk If you want to tackle this yourself, the relevant code is in `lib/libzfs/` and `cmd/zpool/`. At a glance, `make_leaf_vdev()` in `cmd/zpool/zpool_vdev.c` and `zpool_find_import_impl` in `lib/libzfs/libzfs_import.c` look relevant. You will want to handle using the symlinks when they exist in the import, create, add and replace cases. This probably should also implement an environment variable to allow the original behavior to be restored.
