### ISSUE TITLE
performance regression from 0.6.4.2 to 0.6.5.2

### ISSUE THREAD

**Issue by jcst** [zfsonlinux/zfs#3902]
disks : 4x6 spinning drives raidz2
memory : 96GB
cpu: dual E5

concurrent gzip on big files (50GB) takes 3x longer, processes are now limited by IO and not CPU.
write speed appears to be unbalanced with read speed 

each line is 10 minutes : 

```
----total-cpu-usage---- -dsk/total- -net/total- ---paging-- ---system--
usr sys idl wai hiq siq| read  writ| recv  send|  in   out | int   csw 
 11   9  71   9   0   0| 189M   73M|   0     0 |   0     0 |  11k   35k
  6   4  35  56   0   0| 457M   43M|2330B   58k|   0     0 |9914    17k
  5   4  36  55   0   0| 437M   43M|6102B   36k|   0     0 |9766    17k
  7   4  35  54   0   0| 458M   43M|2633B   14k|   0     0 |  10k   16k
  6   4  37  53   0   0| 437M   52M| 535B   16k|   0     0 |  11k   21k
  5   4  37  54   0   0| 447M   40M|  12k  301k|   0     0 |  10k   18k
  5   4  39  52   0   0| 456M   43M|8469B  341k|   0     0 |  10k   17k
  3   5  40  53   0   0| 456M   30M| 262B 6395B|   0     0 |9861    20k
  6   3  39  52   0   0| 455M   47M|  24k 1111k|   0     0 |  10k   15k
  5   4  36  55   0   0| 464M   52M|3834B   42k|   0     0 |9952    16k
  7   4  34  56   0   0| 477M   42M|  23k  854k|   0     0 |  11k   16k


also, with multiple zfs send, the first one will use 10x more bandwidth than the following ones.
```

**Comment by dweeezil** [comment]
@jcst I'm running some comprehensive tests this weekend on a large-scale testing system to see whether the scheduler/priority changes in 1229323 and zfsonlinux/spl@9dc5ffb may be behind this change in behavior or may have caused any other similarly-reported potential regressions.  Could you please tell me whether you've changed any default tuning and also how many concurrent gzip operations you've been running.  I've currently got a 4x6rz2 test pool set up and have been running between 16 and 32 concurrent ```gzip -3``` operations for testing.

I'll be opening another issue if I can put my finger on anything.

**Comment by dweeezil** [comment]
@jcst One other thing, please make sure you don't have a bad drive which is holding up writes.  I've seen SAS drives with max reallocated sectors cause exactly this problem.

**Comment by dweeezil** [comment]
@jcst I've not been able to duplicate the level of read/write imbalance you've shown.  If anything,  the I/O is more responsive in 0.6.5 than 0.6.4 because the rationale behind 1229323 seems to be totally correct.  In fact, I'm surprised there weren't more problems in the past due to the weird task priorities.  In particular, prior to 0.6.5, all the zio threads actually ran at a lower priority than normal user tasks which is exactly the opposite of what we want.  I would still be interested to know how many concurrent gzip processes you're running and how many threads your dual E5 system has.

**Comment by jcst** [comment]
2xE5 total 24 threads and about 32 gzip -1 processes

**Comment by jcst** [comment]
same backup task with 0.6.4 and 0.6.5
![load 0 6 5 2](https://cloud.githubusercontent.com/assets/7390430/10419191/e2599f7e-70cb-11e5-984a-54833f9a42f0.png)
![load 0 6 4 2](https://cloud.githubusercontent.com/assets/7390430/10419192/e25c2f50-70cb-11e5-9b9b-76e4ea651149.png)

**Comment by dweeezil** [comment]
@jcst Presumably you're not using any ```nice``` on your gzip processes? You've got a highly CPU-intensive workload which is also generating a lot of reads and writes and is also oversubscribing the number of available threads.  In 0.6.4, the priorities would be (these are raw priority values: lower values have more priority):

    100 spl system task, metaslab_group
    120 gzip (higher priority than the write issue threads)
    138 z_wr_iss
    139 other zio threads

but in 0.6.5 it is:

    100 most zfs threads including zio
    101 z_wr_iss
    120 gzip (lower priority than the write issue threads) and also a handful of non-intensive zfs threads

Could you try running your gzip processes with ```nice -n 20``` under 0.6.5.  That will drop them down to 100 which will give them more priority than the write issue threads and be more equivalent to the ranking under 0.6.4.  You could also try setting ```spl_taskq_thread_priority=0``` when loading the spl module.  That will cause all the zfs threads to run at 120 (normal user priority) and then you could run your gzip with any negative nice.

For my part, I'll try some more tests with ```maxcpus=24``` and an oversubscribed workload to see whether I can duplicate your behavior.

NOTE: If you're interested in seeing the raw priorities with ```ps``` on your own system, you must use the undocumented ```pri_baz``` output format as in, for example, ```ps -eL -o pid,pri_baz,cmd```.

**Comment by jcst** [comment]
will try that in 2 days

**Comment by jcst** [comment]
any idea on what to check next ?

**Comment by spamn** [comment]
I think I have a similar or maybe related issue though I seem to have CPU performance issue rather than IO performance issue. Going from 0.6.4.2 to 0.6.5.x everything else remaining equal.

I got a i7-4471 cpu, 5 x 3TB raidz2 pool with a l2arc on ssd and 32GB of RAM.

I use this computer for virtualisation with vfio-vga and kvm (http://vfio.blogspot.fr/), my VM disks are zvols. Upgrading from 0.6.4.2 to 0.6.5.x causes my Windows 7 virtual machine to have sluttering and audio glitches when there are disks IO (the windows start sound is very glitchy and the videogame Sleeping Dogs have freezes that last for hundreds of ms). I will try to provide measurements with http://www.thesycon.de/deu/latency_check.shtml . Do you believe I should open another ticket ?

**Comment by xalxd** [comment]
What are you using for that graphs draw?

**Comment by jcst** [comment]
the graphing is done with collectd

**Comment by behlendorf** [comment]
@jcst is the same regression observed in 0.6.5.3 or the master ZFS branch?

**Comment by jcst** [comment]
@behlendorf yes same issue with 0.6.5.3 but I can't test the master branch as it's a production server.

**Comment by yetao** [comment]
Hello guys, 

Do any of you have any 'good news' about this on last versions? Or maybe some kind of parametrization which solves it? I have experimented this same problem on a bunch of backup servers with all 0.6.5.x tried versions (I have not tried the last two: 0.6.5.5 and 0.6.5.6).

So we are stuck at 0.6.4.2 version on all of our systems.

Thanks!
