### ISSUE TITLE
Build bots can't handle dependencies

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#3935]
Just looked at #3656 and it occurred to me that the build-bots can't handle dependencies. This happen every now and then, especially to SPL (don't know if we have/need other dependencies than that).

We've talked about adding dependency info in the commit log before (last one I think was 6e9710f7c33a7440904b39fb4e6b68b3325cfeca). I don't know exactly how the build-bots are setup, but shouldn't it be possible to gather the information we/the build-bots need from the commit log?.

Maybe duplicate what we have for <code>Signed-off-by: …</code> and make it more standardized. Something like <code>Depend-on: …</code>? Then the build-bots would just build the dependency + PR/patch first, then zfs…

Should be fairly straight forward… ?

**Comment by behlendorf** [comment]
The buildbot tests the zfs commits by checking out that exact commit from the pull request.  That can result in build failures because it always tries to build against the latest spl source.  We could definitely extend the buildbot to accept a hint in the commit message, I like the 'Depends-on:' tag.  Longer term we can pull the spl in-tree to prevent the issue entirely.

The good news here is we're working to make all of the configuration, scripts, and infrastructure behind the zfs buildbot available. This should come together over the next few months and then it will be possible for the community to help customize it to do things like this.

**Comment by FransUrbo** [comment]
Considering that there's quite a lot of duplication of code between spl and zfs, merging spl into zfs and clean it up is probably a good idea. We're not the only ones that need something like the "Solaris Porting Layer" either, right so if we do that, it would/could benefit others as well.

**Comment by behlendorf** [comment]
One of the reasons they were originally kept separate was so that other projects could use it.   However,  I don't know if any other projects using it so that's not a big reason in practice.  There aren't many compelling reason to keep them separate anymore.

**Comment by chrisrd** [comment]
+1 on combining

**Comment by tuxoko** [comment]
Yeah, I'd really like to see it merged.

**Comment by behlendorf** [comment]
Replaced by zfsonlinux/zfs-buildbot#5.
