### ISSUE TITLE
Ability to add more levels of storage tiers

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#4045]
Currently we got RAM, we got L2ARC and we got a Permanent Storage.

Since everything is heading to SSDs it would be nice to add different levels of SSDs for a Level 3 ARC or say an array of very slow very large archiv HDDs for a nearly cold-storage. This would lower the cost of the overall system while increasing the effetivity of the hardware which is in use.

Are such features currently planned?

**Comment by DeHackEd** [comment]
The issue comes down to block pointer rewrites. While tiered storage (or some variant thereof) is planned, ZFS can't migrate data on the fly. It needs to know that data will be hot or cold at the time it's first written to disk and then it can't be so easily moved. So that means that the tier of data needs to be decided at the time of creation.

The current strategy is to implement a high-tier for essentials like metadata and maybe mark a dataset as being intended for high-tier use. You could have an SSD vdev just for metadata and very hot content, then spinning disks for the bulk of the file data.

That's the closest we have at the moment.

**Comment by RubenKelevra** [comment]
Thanks for your fast reply. :)

Actually zfs is often used as backend for something like ceph or as backend for virtualization its actually used for a mixed content (files) of very hot, hot, cold and very cold data. So auto tiering would be very great. 

Is there any chance to modify the current arc-approach to support multi tier storage to organize them automatically? :)

**Comment by pashford** [comment]
I'm just brainstorming here, but I believe this might be handled by the Persistent L2ARC feature.  While the initial access might be a bit slow (like pulling the data off the secondary storage), subsequent access would be fast (pulling the cached copies from the L2ARC).  Is this close enough to the original request to do the job?

Now if only we could get the Persistent L2ARC feature moving forward.

https://github.com/zfsonlinux/zfs/issues/3744

**Comment by kpande** [comment]
#5182
