### ISSUE TITLE
ZFS 0.6.5.3-r1. Low speed read again.

### ISSUE THREAD

**Issue by OverLocker** [zfsonlinux/zfs#4064]
Hello,
After update situation is the same as 0.6.5.3 
Read from pool from the network is about 60MB/s
On lower versions it was 112MB/s.
When it wil be fixed?

**Comment by OverLocker** [comment]
In a addition: Seems that copy from pool cause very high load IO from disks.
It cat be shown by atop program

**Comment by kernelOfTruth** [comment]
@OverLocker please provide much more information what the system is doing,

information on the system (hardware), on the software (kernel, distribution ...), etc. etc.

**Comment by OverLocker** [comment]
Linux NAS01 4.1.12-gentoo #1 SMP Thu Nov 5 21:14:34 MSK 2015 x86_64 Intel(R) Pentium(R) CPU G630 @ 2.70GHz GenuineIntel GNU/Linux

Mem 16GB

 cat /etc/modprobe.d/zfs.conf
options zfs zfs_arc_max=2147483648
options zfs zfs_arc_min=536870912

zpool status
  pool: ZFS01
 state: ONLINE
  scan: scrub repaired 16K in 23h4m with 0 errors on Tue Dec  1 23:04:51 2015
config:

        NAME                                          STATE     READ WRITE CKSUM
        ZFS01                                         ONLINE       0     0     0
          raidz2-0                                    ONLINE       0     0     0
            ata-WDC_WD30EFRX-68AX9N0_WD-WCC1T1103105  ONLINE       0     0     0
            ata-WDC_WD30EFRX-68AX9N0_WD-WCC1T1172243  ONLINE       0     0     0
            ata-WDC_WD30EZRX-00SPEB0_WD-WCC4E0315648  ONLINE       0     0     0
            ata-WDC_WD30EZRX-00DC0B0_WD-WMC1T2084454  ONLINE       0     0     0
            ata-WDC_WD30EZRX-00D8PB0_WD-WCC4N0103047  ONLINE       0     0     0
            ata-WDC_WD30EZRX-00DC0B0_WD-WMC1T0438502  ONLINE       0     0     0
            ata-WDC_WD30EZRX-00MMMB0_WD-WCAWZ0412403  ONLINE       0     0     0
            ata-WDC_WD30EZRX-00MMMB0_WD-WMAWZ0327093  ONLINE       0     0     0
            ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N0962266  ONLINE       0     0     0

errors: No known data errors

**Comment by AndCycle** [comment]
I got even worst situation, it failed to list all ZFS,

http://imgur.com/0Q4y5gF

here is the screenshot of failed boot.

**Comment by behlendorf** [comment]
There's a lot which could be going on here.  Are you able to see good performance when not coping over the network?  Have you verified that rolling back to and older version improves performance?

**Comment by ryao** [comment]
@AndCycle Your kernel modules likely fell out of sync with the userland tools. I have been trying to stabilize the /dev/zfs API starting with 0.6.5.3-r1 so that this is the last time something like this happens. Unfortunately, mixing the old tools and kernel modules was not working in -r1. As of 0.6.5.3-r2, you can use the old tools with the new modules, but not the new tools with the old modules.

@OverLocker I suggest joining #zfsonlinux on freenode to ask for help debugging. It is very hard to get an idea of what is going wrong here. That said, information on the amount of free space in the pool (e.g. `zpool list` and `zfs list`) and the metaslabs (e.g. `zdb -mmm ZFS01`) would be helpful. The latter command makes quite a bit of output, so you would want to attach it as a file or do something like `zdb -mmm ZFS01 |& curl -F 'sprunge=<-' http://sprunge.us` to send it to a pastebin.
