### ISSUE TITLE
ZFS from VM?

### ISSUE THREAD

**Issue by gregfr** [zfsonlinux/zfs#4071]
Hello Community

I was wondering if it would be possible to access a ZFS volume from inside an OpenVZ container?

My goal is to have a dedicated "backup" VM on a host using ZFS volume for its VMs.

Thanks in advance

**Comment by lnxbil** [comment]
Hi gregfr,

Sorry, this is not a real answer, but another question:
What recent kernel does support both OpenVZ and ZFS? Most OpenVZ-based distributions changed to LXC and abandoned OpenVZ.

Best

**Comment by gregfr** [comment]
Yes I know, but my server are VZ containers right now and I don't plan to migrate now, anyway not before having a reliable backup.

**Comment by ryao** [comment]
@gregfr Do you mean a zvol? It should be configurable just like anything else in OpenVZ.

**Comment by chani** [comment]
@gregfr: not sure for volumes, but working fine for filesystems:

    VE_ROOT="/var/lib/vz/root/12"
    VE_PRIVATE="/storage/containers/12/private/12"

where storage is my zfs pool and 12 is an OpenVZ container. Basically just create a dataset pool/whatever/VEID and create the folder private/VEID within that. Now modify the above parameters in your configuration file for the container (in this case /etc/vz/conf/12.conf).

Now OpenVZ also offers another special functionality which isn't very well documentated imo:

    root@janice:~# cat /etc/vz/conf/100.mount 
    #!/bin/bash
    source /etc/vz/vz.conf
    source /etc/vz/conf/100.conf
    mount -n --bind /storage/databases/myisam-data /var/lib/vz/root/100/var/mysql/myisam-data
    mount -n --bind /storage/databases/innodb-logs /var/lib/vz/root/100/var/mysql/innodb-logs
    mount -n --bind /storage/databases/innodb-data /var/lib/vz/root/100/var/mysql/innodb-data

I do use this due to different dataset settings for myisam/innodb data and logs. Probably adaptable to zvols. However, within OpenVZ it will always be shown as simfs. I haven't found a way to do that with ploop, yet.

**Comment by gregfr** [comment]
Thanks for your answers. I already have my CTs based on zfs volumes.

My question is about a process inside a CT using the "zfs" command to manage the server's disk. I know it seems a security problem, I'm trying to build a secure backup solution.

**Comment by lnxbil** [comment]
I do not think that the ZFS management interface is available inside a container, but I could be wrong. This would be a huge security risk.

Yet, simply install the zfs tools and try yourself.

**Comment by kpande** [comment]
This seems to be better suited discussion for [the zfsonlinux mailing list](http://list.zfsonlinux.org) :-)
