### ISSUE TITLE
Wonder about how many bytes can exceed the quota 

### ISSUE THREAD

**Issue by GeLiXin** [zfsonlinux/zfs#4255]
Hi,
    I can understand that quota isn't a strict restraint in ZFS, because the precise used space is calculate after the spa_sync, and the  inflight ZPL request was counted by a extimate size in dmu_tx_assign.
    The key here is what's the max overflow size will happen? Can we prognosis it in percent or a  absolute value?  I will be deeply grateful for your answer, or if some relative infomation can be given to me to dig into the details.

**Comment by behlendorf** [comment]
@GeLiXin the quota can be exceeded by at most one transaction group worth of data.  How large a transaction group can be is bounded by `zfs_dirty_data_max_percent` module option which is set to 10% of system memory by default.  That's going to be your worst case, although in practice you shouldn't get anywhere need that because a TXG group will be scheduled roughly every 64M of dirty data, controlled by `zfs_dirty_data_sync`.

**Comment by adilger** [comment]
@behlendorf this issue could probably be closed?

**Comment by behlendorf** [comment]
@adilger yes, thanks!  Closing.
