### ISSUE TITLE
IO accounting available in /proc/*/io, but not cgroup-level blkio accounting

### ISSUE THREAD

**Issue by charles-dyfis-net** [zfsonlinux/zfs#4275]
As of ZFS 0.6.2 on Linux 3.9.10, cgroup-level accounting included read/write counters for block devices backing zpools. On a system where /dev/sda (8:0) is a raw partition and /dev/sdb (8:16) is a block device backing a zpool, `/sys/fs/cgroup/blkio/system.slice/*.service/blkio.io_service_bytes` would contain content akin to the following (for a service interacting with both root and ZFS filesystems):

```
8:16 Read 15140447744
8:16 Write 0
8:16 Sync 0
8:16 Async 15140447744
8:16 Total 15140447744
8:0 Read 26947584
8:0 Write 0
8:0 Sync 0
8:0 Async 26947584
8:0 Total 26947584
Total 15167395328
```

As of ZFS 0.6.5.4 on Linux 3.19.3, only data on the non-ZFS filesystem is present:

```
8:0 Read 24272896
8:0 Write 0
8:0 Sync 0
8:0 Async 24272896
8:0 Total 24272896
Total 24272896
```

It's worth noting that my copy of ZFS was compiled with `HAVE_GENERIC_IO_ACCT`, and accurate data (which includes reads and writes from ZFS) is included at the individual process level in `/proc/*/io`:

```
rchar: 1397220692
wchar: 1290199651
syscr: 1451540
syscw: 257620
read_bytes: 123129979352
write_bytes: 1277279545
cancelled_write_bytes: 0
```

With the newer interfaces provided by the upstream kernel, does using ZFS preclude accurate cgroup-level accounting?

**Comment by charles-dyfis-net** [comment]
End-user tools using this (cgroup) data include `systemd-cgtop`. If a better alternative is available for cgroup-level IO accounting, I would be happy to submit an appropriate patch to systemd.

**Comment by ryao** [comment]
Were the numbers on the older release and kernel the same for all processes or different?

I had been under the impression that this had always been unsupported because there is nothing in the code at present to keep track of which IOs were issued on behalf of specific processes. I am surprised to hear that it worked. This would probably be useful to implement and would probably require us to tag things being submitted to the ZIO pipeline so that it accounts for them properly.

**Comment by charles-dyfis-net** [comment]
@ryao, the numbers on the old kernel were realistic enough that we had them plumbed into our monitoring system and they looked reasonable enough to work with. (Lots of writes accounted to the database, smaller numbers to other processes, etc).

**Comment by snajpa** [comment]
As far as I understand it, only some of process-induced IO is accounted with blkio. The txg sync itself (which is the bulk of the data with non-database workloads) is not accounted for. I've just played with this on OpenVZ patched RHEL6 kernel to find out, that we can't use standard openvz IO limiting precisely because blkio doesn't work reliably with ZFS.

I don't think this can be solved in any other way, than having ZFS account for & enforce IO limits on per dataset basis - which sounds like something which could be benefited from across the OpenZFS community. Sadly I'm not in a position to help with the implementation - I don't think we'll be able to get a full-time ZFS developer this year, hopefully the next one.

**Comment by kernelOfTruth** [comment]
@snajpa is the following what you meant ?

https://github.com/illumos/illumos-gate/commit/97e81309571898df9fdd94aab1216dfcf23e060b
https://www.illumos.org/issues/6531
https://github.com/openzfs/openzfs/pull/39

so there's already some groundwork

**Comment by fcicq** [comment]
if I remembered right, blkio.io_service_bytes is updated by cfq, so if you use noop you cant see that.
blkio.throttle.io_service_bytes always works if you enabled, but it can only be used on zvol.
see also #1952

**Comment by shodanshok** [comment]
I have the same issue on Ubuntu 22.04 with the latest 5.15.0-33-generic kernel and stock 2.1.2-1ubuntu3 ZFS.

When doing IO on the root ext4 partition, `systemd-cgtop -i` shows the following:
```
Control Group                      Tasks   %CPU   Memory  Input/s Output/s
/                                    912   51,7     3.4G     1.1G   369.9K
user.slice                           534   42,8     2.3G     1.1G       0B
...
```
Please notice how the IO is correctly accounted under the user.slice

When doing IO on a zfs dataset, `systemd-cgtop -i` only shows the following:
```
Control Group                      Tasks   %CPU   Memory  Input/s Output/s
/                                    927  164,4     3.5G   787.3M       0B
dev-hugepages.mount                    -      -     4.0K        -        -
...
```
Now the IO is only accounted against the root control group, with any other slice (or scope) reporting no IO.

The issue affect any tools relying on cgroups for IO monitorig. For example, `netdata` shows empy graphs for qemu and libvirt virtual machines (each associated to a dedicated systemd scope).

Any suggestions?
