### ISSUE TITLE
Support fast builds by coalescing all autotools checks against known kernel versions

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#4375]
It occurs to me that we could save a copy of the autotools results for each supported mainline kernel, have a generic file that is equivalent to simultaneously running all checks based on the contents, try compiling it and if it builds, skip the kernel checks entirely. This should dramatically speed up the build process.

**Comment by rlaager** [comment]
How much time do you estimate this could save, best case?

This seems like a fair amount of work to implement and maintain, and may be fragile (e.g. if some autotools test depends on a kernel configuration option).

**Comment by behlendorf** [comment]
Best case we could skip all the `kernel-*` checks which can take a few minutes.

However, I don't think this would be practical because we can't use one generic file for each mainline kernel.  Depending on exactly what CONFIG_* options were used when the kernel was built certain interfaces may or may not be available.  Conceivably this could be done by a distribution for their provided kernel(s) if they shipped a `spl_config.h` and `zfs_config.h` for each kernel.

Otherwise the only safe way to do this reliably is the run the configure checks.  Now in theory those could be done in parallel which would speed things up considerably but autotools doesn't support this.

Closing.  We shouldn't do this.
