### ISSUE TITLE
The changes for case insensitive mode are not completely correct

### ISSUE THREAD

**Issue by RichardSharpe** [zfsonlinux/zfs#4431]
We discovered recently that there is a problem in the following sense:
1. You create a file called 'Fred'. This installs an entry in the dcache for the name Fred.
2. You stat on 'fred'. This fails because the hash does not match so it goes to the file system and finds Fred but does not install a dcache entry for 'fred' (which is good) but all future lookups on the same case will bypass the name.

What I think needs to be done is that if we are in CI mode, add something like a zpl_ci_hash function to zpl_dir_inode_operations in zpl_inode.c and set the flag DCACHE_OP_HASH when registering these ops.

Then the hash function must call u8_textprep_str with U8_TEXTPREP_TOUPPER along with other flags and then call the normal dcache hashing function.

This might avoid relatively expensive calls into the file system.

Does this sound reasonable?

**Comment by behlendorf** [comment]
I'm not sure what you mean by 'bypass the name' in point 2 above.  Does this result in incorrect behavior or just less than ideal performance?

As for registering our own hash function this is definitely possible although it's part of the dentry_operations and not the inode_operations structure.  It looks like we could even do this unconditionally and by default leave it as a no-op unless CI is set according to the comments in `d_hash_and_lookup()`.  On the surface it sounds like a approach worth investigating, but again I'm not 100% clear on the exact problem here.

Related to case normalization I wanted to mention that we now have all of the ZFS Test Suite's test cases for this in the master branch.  Most of these tests appear to currently fail because they depend on a helper utility called [zlook](https://github.com/illumos/illumos-gate/blob/master/usr/src/cmd/zlook/zlook.c) which was never added to ZoL.  Getting that helper added and these test cases passing would probably be the best way to get this functionality working 100% correctly.

```
Test: ./tests/functional/casenorm/setup (run as root) [00:00] [PASS]
Test: ./tests/functional/casenorm/case_all_values (run as root) [00:00] [PASS]
Test: ./tests/functional/casenorm/norm_all_values (run as root) [00:01] [PASS]
Test: ./tests/functional/casenorm/sensitive_none_lookup (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/sensitive_none_delete (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/sensitive_formd_lookup (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/sensitive_formd_delete (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/insensitive_none_lookup (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/insensitive_none_delete (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/insensitive_formd_lookup (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/insensitive_formd_delete (run as root) [00:01] [PASS]
Test: ./tests/functional/casenorm/mixed_none_lookup (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/mixed_none_lookup_ci (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/mixed_none_delete (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/mixed_formd_lookup (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/mixed_formd_lookup_ci (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/mixed_formd_delete (run as root) [00:00] [FAIL]
Test: ./tests/functional/casenorm/cleanup (run as root) [00:00] [PASS]
```

**Comment by RichardSharpe** [comment]
Sorry, it is a performance problem only. By bypass the name, I mean that if the name is not an exact case match of the name as stored in the FS, it will always go to the file system.

Let me see if I can find time over the weekend to look into this.

**Comment by behlendorf** [comment]
Closing, CI handing was improved by 9d36cdb65089954baf649a8963f2129654c0b0b2 and c5d0287011679d76288c2617c409252245172a32.  However, some work still needs to be done to enable these test cases.
