### ISSUE TITLE
Huge reported space usage difference using ZVOLs

### ISSUE THREAD

**Issue by francoisstark** [zfsonlinux/zfs#4436]
We have a large pool on ubuntu 14.04, zfs, 0.6.4.2, on kernel 3.13.0-83-generic.

Problem:  We created ZVOLS that we share over LIO over fibre and iSCSI.  
The reported space use in 'zfs list' is aprox. 2.5 x larger than expected.  
We host large video files for editing.  Compression ratio 1.07%.  ashift = 12

'zfs list' shows total space use 106T, free space 4.6T; 
'zpool list' shows space used 69.8T, free space 77.2TB;

Question:  Even if we take into account that the zpool figures include raidz2 redundancy overhead, we still see free space of 47%, while we are already overusing the free space according to the zfs list. What should be believe?  If we look at the data actually loaded on the SAN volumes from the clients view, the space usage we see on 'zpool list' looks approximately right.

```
zfs list
NAME               USED  AVAIL  REFER  MOUNTPOINT
titanpool          106T  4,64T   219K  /titanpool
titanpool/Edit2   15,7T  12,7T  7,59T  -
titanpool/Edit3   17,1T  12,9T  6,91T  -
titanpool/Edit9   20,4T  15,0T  9,66T  -
titanpool/Edit4   30,7T  20,1T  14,2T  -
titanpool/Edit5   21,8T  14,9T  9,14T  -
```
```
zpool list
NAME        SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
titanpool   147T  69,8T  77,2T         -    13%    47%  1.00x  ONLINE  -

```
 ```
zpool status
  pool: titanpool
 state: ONLINE
  scan: scrub repaired 0 in 25h16m with 0 errors on Sun Mar 20 02:16:32 2016
config:

	NAME                                            STATE     READ WRITE CKSUM
	titanpool                                       ONLINE       0     0     0
	  raidz2-0                                      ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX11DB4H8FUA    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX11DC4FK24L    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX11DC4FK6TY    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX21D74KVL9X    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX21D74KVT7D    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX21D74KVZAP    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX21DC4D52P8    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX31DB44KCZV    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX61DA4F0UTZ    ONLINE       0     0     0
	  raidz2-1                                      ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX61DA4F0V0D    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX61DA4F0YDJ    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WX71DA4A0SUH    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXK1H642MW73    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXL1H840MMFX    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXL1H845A9JK    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXL1H84DDY5T    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXL1H84DPKEY    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXL1H84E555N    ONLINE       0     0     0
	  raidz2-2                                      ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXL1H84E60PH    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXL1H84E6JHH    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXL1H84FA4EF    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXP1H640CJ7R    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXP1H641S42M    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXP1H642TF01    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXP1H645L3YW    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXT1H640YMN3    ONLINE       0     0     0
	    ata-WDC_WD60EZRX-00MVLB1_WD-WXT1H645CZUV    ONLINE       0     0     0
	logs
	  mirror-3                                      ONLINE       0     0     0
	    ata-INTEL_SSDSC2BW240A4_CVDA445304B02403GN  ONLINE       0     0     0
	    ata-INTEL_SSDSC2BW240A4_CVDA445402J62403GN  ONLINE       0     0     0
	    ata-INTEL_SSDSC2BW240A4_CVDA445401A62403GN  ONLINE       0     0     0

```

**Comment by DeHackEd** [comment]
RAID-Z geometry is weird. You have 9 data disks, but your default `volblocksize=8k` means only 2 data disks are needed per zvol block. In raidz2 you need 2 parity blocks <b>for each data block</b>. That's 2 parity blocks per 4 disks rather than the 9 you expect. With 9 disk stripes and a rounding operation that RAID-Z does on block sizes you have some pretty poor efficiency.

Both size reports are correct in different ways. `zfs list` tells you how much data was written by applications, `zpool list` shows how much of the disks' surface is claimed.

This is one of several reasons why ZVOL usage strongly encourages the use of mirrors instead of RAID-Z.

(This is an issue tracker, not a support forum. Please close any issues that are not bugs, feature requests, etc)

**Comment by francoisstark** [comment]
After reading your comment, I immediately thought "but I write large files - running over many blocks - and the parity should be 2 blocks in every 9" but then I realised that the host operating system shares this out as a bock device and doesn't even see the files. 
So what you are saying is that every block where we write data needs two parity blocks? 

And what you are further saying is that the "free space" that zpool reports is not usable free space, but "unusable" free space.
I would think that that constitutes a bug, since "free space" should, by definition, be usable. Otherwise, why report it as "free space"?

**Comment by dasjoe** [comment]
This belongs to [zfs-discuss](http://list.zfsonlinux.org/mailman/listinfo/zfs-discuss), it's not an issue.
As @DeHackEd already said, `zpool list` shows unused disk capacity, which may not be usable.

`zfs list` shows usable free space.

**Comment by b333z** [comment]
http://nex7.blogspot.com.au/2013/03/reservation-ref-reservation-explanation.html?m=1

**Comment by DeHackEd** [comment]
This is how RAID-Z works. Stripe sizes are variable. It's how ZFS deals with the write hole that can occur in RAID-5+ without non-volatile storage buffers (eg: battery backup on a RAID card).

`zpool list` reports space as raw disk space in RAID-Z. How much parity will be required is unknown since it varies by block sizes so it is reported in the context that parity is part of the overall used space. Similarly `zfs list` output is merely an estimate since the block sizes can vary.

And finally as b333z points out "free space" varies because all volumes have space reservations. They've all claimed some amount of free space as set aside for themselves which is reflected in the output - each volume has a variable amount of free space according to how large the volume is, and then the top-level filesystem gets whatever is unclaimed.

Everything is working as expected.
