### ISSUE TITLE
CPU cache miss is very high for RAID-Z1/2/3 parity computation 

### ISSUE THREAD

**Issue by fshh520** [zfsonlinux/zfs#4497]
# problem

about "NEON vectorized RAID-Z1/2/3 parity computation for ARM64"

I found that when the amount of data written to each disk is relatively small, NEON algorithm to improve the speed of operation is very obvious, about 60% of the increase. But when the amount of data written to each disk is relatively large, NEON algorithm to improve the speed of operation is very small, only about 10% to 20% of the increase.

I further test found it's relate to cache miss. At the time of RAID-Z1/2/3 parity computation, if cpu cache miss is very high, There will be a great influence on the improvement of NEON algorithm. and I believe the same is true for "SSE, AVX-128 & AVX2 vectorized RAID-Z1/2/3 parity computation".

Cache miss test examples are given below :
The test program is as follows:

COPY8P_NEON8..... is here:  Pull requests,  NEON vectorized RAID-Z1/2/3 parity computation for ARM64. #4488 

``` c
void test_p_n( uint64_t *p, uint64_t *srcsrc[7], int num )
{
    uint64_t ccount, i;
    int c;
    uint64_t *src;

    for( c = 0; c < 7; c++ ){
        src = srcsrc[c];
        i = 0;
        ccount = num;
        if ( c == 0 ){
            if( ccount > 7 )
            for (; i < ccount-7; i += 8, src += 8, p += 8) 
                COPY8P_NEON8;
            for (; i < ccount; i++, src++, p++)
                *p = *src;
        }else{
            if( ccount > 7 )
            for(; i < ccount-7; i+=8, src+=8, p+=8 ) {
                LOAD8_SRC_NEON8;
                COMPUTE8_P_NEON8;
            }

            for(; i < ccount; i++, src++, p++ )
                *p ^= *src;
        }
    }
}

int main( int argc, char *argv[] )
{
    uint64_t i = 0;
    uint64_t *srcsrc[7];
    int num, count;

    uint64_t *p = (uint64_t *)malloc(5000000*(sizeof(uint64_t)));

    num = atoi(argv[1] );
    count = atoi( argv[2] );

    //* Simulation of 7 pieces of hard disk data 
    for( i = 0; i < 7; i++ )
        srcsrc[i] = (uint64_t *)malloc(5000000*(sizeof(uint64_t)));

    i = 0;
    while( i++ < count )
        test_p_n(p, srcsrc, num);
}
```

compile: `gcc -O1 zfs_cache.c -o main_test_git`
run: `valgrind --tool=cachegrind ./main_test_git 20000 1`
result:  
![cache_miss](https://cloud.githubusercontent.com/assets/2967853/14346202/aac51b7a-fce3-11e5-846e-3e283511f325.jpeg)
As you can see:
D1 miss rate and LLD miss rate is very high.
# proposed solution
### change:

``` c
for (c = rm->rm_firstdatacol; c < rm->rm_cols; c++) {
    ......
    for (i = 0; i < ccount; i++, src++, p++) {
        .....
    }
}
```
### to:

``` c
for (i = 0; i < ccount; i++, src++, p++)
    ......
    for (c = rm->rm_firstdatacol; c < rm->rm_cols; c++)  {
        .....
    }
}
```

The objective is to avoid traversing multiple relatively large data buffer, and improve the cache hit.

**Comment by ironMann** [comment]
I would like to see numbers you get for proposed solution. `rm_col[].rc_data` buffers are actually offseted pointers to the same zio buffer, see [here](https://github.com/zfsonlinux/zfs/blob/master/module/zfs/vdev_raidz.c#L541-L543). While you would not have to save/reload intermediate results in parity buffers, you would introduce multiple data streams to the CPU, and if you already have large cache miss rate, that should make things even worse. Your solution actually works better for x86, only because CPUs have larger L2 data cache and more advanced hardware prefetcher. I've seed it in #4328. Finally, with the upcoming scatter/gather buffers, (abd work), you will not be able to efficiently access multiple data pages at the same time (limitations of `kmap_atomic()` interface). I have adapted my x86 vectorized code in #4439 accordingly.

Here are my explanations of your observations, and maybe things to try out:

- Weak hw prefetcher. I have seen some ARM CPUs with prefetcher disabled because of errata. Adding explicit prefetching instructions increased performance by factor of 2.

- You are reaching memory bandwidth limit of a single CPU core. Note that scalar version of parity generation is fairly optimized, it can produce 8 bytes of parity in a single step. So if you're also hitting memory wall you may not see large speedup. If you plot your results with different data sizes you should see different speeds, one for each cache level you have. ([example](http://fias.uni-frankfurt.de/~neskovic/zfs/zfs_vect.pdf)).

**Comment by fshh520** [comment]
Hi, 
I just change test_p_n like this:
```c
void test_p_n( uint64_t *p, uint64_t *srcsrc[7], int num )
{
	uint64_t *src, pcount, ccount, i;
	int c;
	uint64_t *p_tmp;
	uint64_t src_p = 0;

	p_tmp = p;

	if ( num  > 63 ){
		for ( i = 0; i < num-63; i += 64, p_tmp += 64, src_p += 64) {
			for ( c = 0; c < 7; c++ ) {
				src = srcsrc[c] + src_p;
				p = p_tmp;
				if ( c == 0 ) {
					COPY8P_NEON8;
					src+=8;
					p+=8;
					COPY8P_NEON8;
					src+=8;
					p+=8;
					COPY8P_NEON8;
					src+=8;
					p+=8;
					COPY8P_NEON8;
					src+=8;
					p+=8;
					COPY8P_NEON8;
					src+=8;
					p+=8;
					COPY8P_NEON8;
					src+=8;
					p+=8;
					COPY8P_NEON8;
					src+=8;
					p+=8;
					COPY8P_NEON8;
				} else {
					LOAD8_SRC_NEON8;
					COMPUTE8_P_NEON8;
					src+=8;
					p+=8;
					LOAD8_SRC_NEON8;
					COMPUTE8_P_NEON8;
					src+=8;
					p+=8;
					LOAD8_SRC_NEON8;
					COMPUTE8_P_NEON8;
					src+=8;
					p+=8;
					LOAD8_SRC_NEON8;
					COMPUTE8_P_NEON8;
					src+=8;
					p+=8;
					LOAD8_SRC_NEON8;
					COMPUTE8_P_NEON8;
					src+=8;
					p+=8;
					LOAD8_SRC_NEON8;
					COMPUTE8_P_NEON8;
					src+=8;
					p+=8;
					LOAD8_SRC_NEON8;
					COMPUTE8_P_NEON8;
					src+=8;
					p+=8;
					LOAD8_SRC_NEON8;
					COMPUTE8_P_NEON8;
				}
			}
		}
	}

	for ( ; i < num; i++, src_p++, p_tmp++ ){
		for ( c = 0; c < 7; c++ ) {
			src = srcsrc[c] + src_p;
            p = p_tmp;
			if ( c == 0 ) {
				*p = *src;
			}else{
				*p ^= *src;
			}
		}
	}
}
```
and you can see the cache hit rate improved a lot, especially LLD. 
![cache_miss2](https://cloud.githubusercontent.com/assets/2967853/14414221/e52a2b6c-ffc1-11e5-9322-947d7ff1a43c.jpeg)
Of course, this code can be optimized again, What I'm trying to say is 
change:
```c
for (c = rm->rm_firstdatacol; c < rm->rm_cols; c++) {
    ......
    for (i = 0; i < ccount; i++, src++, p++) {
        .....
    }
}
```
to:
```c
for (i = 0; i < ccount; i++, src++, p++)
    ......
    for (c = rm->rm_firstdatacol; c < rm->rm_cols; c++)  {
        .....
    }
}
```
and it will improve the cache hit. and you can see the RAID algorithm of Linux kernel(lib/raid6), and it did that too:
```c
for ( d = 0 ; d < bytes ; d += NSIZE*4 ) {
    ......
    for ( z = z0-1 ; z >= 0 ; z-- ) {
        ......
    }
}
```
Later, I will use ironMann's code for reference to test the speed upgrade.
Or,  is there a good way to test the speed in master branch?

**Comment by ironMann** [comment]
Hi,
Cachegrind is not the right tool for this problem. The streaming nature of parity computation will simulate nicely in cachegrind because you are always accessing the consecutive memory addresses, and this will show up as a LLd miss once per cache line. This is what you see here: `D refs/LLd misses ~ 32B cache line`.

As I said, the case is simple: you load data from memory to register, compute the parity and save the register value to the parity buffer. Let say the data is not present in the CPU caches before parity calculation. Why would you expect to see improved cache hit rate with your proposed solution?

There's no need to unroll more than 4x the register size. This can only hurt instruction caches, especially with CPUs with µop I caches.

**Comment by behlendorf** [comment]
Closing, the master branchs RAIDZ implementation has been optimized to take advantage of the following instructions when available sse2, ssse3, avx2, avx512f, avx512bw, neon, and neonx2.
