### ISSUE TITLE
Wiki: partition 1 is missing in a partitioning step of Ubuntu 16.04 Root on ZFS

### ISSUE THREAD

**Issue by eviweb** [zfsonlinux/zfs#4629]
Hi,
in the recently updated howto [Ubuntu 16.04 Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.04-Root-on-ZFS), partition 1 is missing in the `sgdisk` command call of the step _2.2 Partition your disk:_:
```
For legacy (MBR) booting:
# sgdisk -a1 -n2:34:2047  -t2:EF02 /dev/disk/by-id/scsi-SATA_disk1
```
It only creates the boot partition.    
It could be something like: `# sgdisk -a1 -n2:34:2047  -t2:EF02 -n1:0:0 -t1:bf01 -c1:ZFS /dev/disk/by-id/scsi-SATA_disk1`

Best regards

Eric

**Comment by kpande** [comment]
isn't it publicly editable?

**Comment by rlaager** [comment]
@eviweb Partition 1 is not missing. There are multiple sgdisk commands. The last one creates partition 1. The order is intentional, to get proper auto-expanding behavior. The numbering is also intentional, to match the ZFS wholedisk layout. Granted, that's not required, so I'm open to discussion if that's presenting a problem. For now, I'll close this bug report, but please re-open (or comment if you can't reopen) if I'm missing something.

@kpande The ZFS wiki is not publicly editable.

**Comment by eviweb** [comment]
@rlaager, thanks for the precision.
I think I've missed something...
Are these two commands:
```
# sgdisk     -n9:-8M:0    -t9:BF07 /dev/disk/by-id/scsi-SATA_disk1
# sgdisk     -n1:0:0      -t1:BF01 /dev/disk/by-id/scsi-SATA_disk1
```
common to both legacy and uefi partitioning ?
Because if so, it's a little bit confusing. Maybe should it be explicitly specified with a comment line that they belong to the two partioning modes.

Best regards

Eric

**Comment by rlaager** [comment]
Sure, changed.

**Comment by eviweb** [comment]
thanks
