### ISSUE TITLE
`/bin/sync` does nothing when datasets have sync=disabled

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#4992]
This one could be argued both ways. ext4 flushes asynchronous data to disk immediately when you run `sync`, but "ZFS doesn't sync when sync is disabled" sounds like exactly what you'd expect.

Tested using:
<pre>$ while true; do
  dd if=/dev/urandom bs=1M count=1 of=somefile
  sync
done</pre>

While in another terminal I switched between `sync=standard` and `sync=disabled` on the dataset in question.

I'm running my so-called bleedingedge7 branch (master at 9baaa7deae45c8556dfd79b2011234da5cb37b3a + ABD 3441) on a 4.5.x kernel custom built.

**Comment by behlendorf** [comment]
Yes, this is exactly by design and how it has always been.  Is this a problem for some use case?

**Comment by DeHackEd** [comment]
Just thinking about consistency with non-ZFS filesystems and the possibility of data not being flushed during shutdown. Most systems invoke `sync` during shutdown and if I can't export the pool, will it be safe?

**Comment by behlendorf** [comment]
Since the default behavior is `sync=standard`, which does respect sync, users will have to opt in to use.  As for the shutdown case everything will always get flushed as long as the filesystem gets unmounted.  That should just leave the root filesystem which may not get unmounted as part of shutdown.
