### ISSUE TITLE
Resilver going past 100%

### ISSUE THREAD

**Issue by TheOneTrueMitch** [zfsonlinux/zfs#5066]
Using Ubuntu 16.04 LTS, one of my drives stopped showing up in bios so I replaced it with the same drive size and type.  Resilver has been running for a while now and has gone past 100%.

```
pool: vault_0
 state: DEGRADED
status: One or more devices is currently being resilvered.  The pool will
    continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Sat Sep  3 10:44:46 2016
    26.3T scanned out of 5.59T at 236M/s, (scan is slow, no estimated time)
    6.36T resilvered, 470.20% done
config:

    NAME                                            STATE     READ WRITE CKSUM
    vault_0                                         DEGRADED     0     0     0
      raidz2-0                                      DEGRADED     0     0     0
        ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M0RT69DA    ONLINE       0     0     0
        ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M0HJVS39    ONLINE       0     0     0
        replacing-2                                 DEGRADED     0     0     0
          15492525564993373685                      OFFLINE      0     0     0  was /dev/sdb2
          ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M0PXR7C2  ONLINE       0     0     0  (resilvering)
        ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M0RT6UXC    ONLINE       0     0     0

errors: No known data errors
```

**Comment by fuzzykiller** [comment]
Not only the percentage is wrong, the absolute values are suspicious, too: 4*2 TB in RAIDZ2 = 4 TB usable space. Could you perhaps also provide the output of `zpool list vault_0` and `zfs get compressratio vault_0`?

**Comment by TheOneTrueMitch** [comment]
It is quite strange, like you said 4*2TB in Z2, up until this point I have had no issues with it... This pool has been running for almost a year.

```
zpool list vault_0
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
vault_0  7.25T  5.59T  1.66T         -     8%    77%  1.00x  DEGRADED  -
```
```
zfs get compressratio vault_0
NAME     PROPERTY       VALUE  SOURCE
vault_0  compressratio  1.00x  -
```

**Comment by GeLiXin** [comment]
Did you delete snapshots, rollback, send/receive manually or automatically while resilvering? 
If you delete snapshot which is being scanned, resilver may have to scan some data twice, which makes the data resilvered bigger than your disk.

@behlendorf Should we limit the resilver percent up to 100% to avoid confusion?

**Comment by darrenfreeman** [comment]
I have seen this too, on Debian. A mirror of SSDs that recently moved from a pair of not very reliable SATA controllers, to an LSI 2008 SAS controller, running P19 firmware.

Going from a git version of zfs that was roughly in line with 0.7.2, to the release tarball of 0.7.5. Since Debian is still broken with zfs compiled from tarball, and it won't import pools on startup, I have to boot and then zpool import.

At this time it began a resilver, and after checking /var/log/messages, I found there were some errors reported by the LSI driver a couple of hours earlier, for the drive now resilvering on import. But the amount that got resilvered is quite a lot more than what would have been written in this time, so I hope it doesn't indicate a screwed SSD, or even worse, a lurking filesystem bug.

--------8<--------8<--------8<--------

  pool: ssd
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Thu Jan 18 14:40:28 2018
        377G scanned out of 377G at 120M/s, (scan is slow, no estimated time)
        94.8G resilvered, 100.11% done
config:

        NAME        STATE     READ WRITE CKSUM
        ssd         ONLINE       0     0     0
          mirror-0  ONLINE       0     0     0
            ssd1    ONLINE       0     0     1  (resilvering)
            ssd0    ONLINE       0     0     0

errors: No known data errors

--------8<--------8<--------8<--------

Then after this, it gave an impossible duration and zero starting time:

--------8<--------8<--------8<--------

  pool: ssd
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
        attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
        using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: resilvered 94.8G in 307445734561404680h36m with 0 errors on Thu Jan  1 10:00:00 1970
config:

        NAME        STATE     READ WRITE CKSUM
        ssd         ONLINE       0     0     0
          mirror-0  ONLINE       0     0     0
            ssd1    ONLINE       0     0     1
            ssd0    ONLINE       0     0     0

errors: No known data errors

--------8<--------8<--------8<--------

Also worth noting that it spent most of that resilver stuck on 0h1m from completion, which is not really helpful. It said it was scanning at over 1 GB/s for the bulk of the capacity of the disc, then it slowed down when it started copying that last 94.8 GB of data.

Again I don't understand how it managed to fall that far behind on writes, unless the drive dropped out many days earlier, and it never told me anything was wrong. Daily scrubs also found nothing wrong, but then I expect a scrub would succeed with a failed drive, as long as the drive is clearly not being used at the time.

**Comment by dioni21** [comment]
This has happened to me twice, at least.  Could not found a reason.
