### ISSUE TITLE
zfs rescue /etc

### ISSUE THREAD

**Issue by wamba2016** [zfsonlinux/zfs#5192]
Hi,
my server  boot on zfs.
Recently i change some pam.d file ( common-auth, common-password...) after that i can not use my ubuntu os.
I try to rescue with xubuntu live cd, and using zfs mount -a to rebuild my dataset zpool, but i can not find the original /etc folder
I see all other dataset bunt not /etc/pam.d

Please help

**Comment by deajan** [comment]
This is probably more a question for an ubuntu forum than here. You might also ask this on zfs discussion list.
Consider closing this issue as it's not directly developpment related.

**Comment by rlaager** [comment]
You installed Ubuntu on a ZFS root using some variant of the official HOWTO (or my fork before it was merged), right? https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.04-Root-on-ZFS

`zfs mount -a` will not mount the root dataset, as it has `canmount=noauto` set. This is done because there may be multiple clones (in the future, if you were using something like `beadm`).

Here's what you want in the Live CD (where rpool is the name of your pool):
apt install zfsutils-linux
zpool import -N -R /mnt rpool
zfs mount rpool/ROOT/ubuntu
zfs mount -a
