### ISSUE TITLE
[feature] reporting dataset and files affected by arbitrary data corruption

### ISSUE THREAD

**Issue by CDLuminate** [zfsonlinux/zfs#5210]
Hi,

I've played around with a raidz1 which is laying on 3 disk image files. I copied some files into the zpool and then (hex)edited one of my disk images without exporting the zpool, emulating sort of arbitrary data corruption. After that, `zpool status -v` just reported as follows.
```
  pool: ztest
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: scrub repaired 64K in 0h0m with 0 errors on Sat Oct  1 10:40:57 2016
config:

	NAME                           STATE     READ WRITE CKSUM
	ztest                          ONLINE       0     0     0
	  raidz1-0                     ONLINE       0     0     0
	    /hdd/junk/zfstest/vda.img  ONLINE       0     0     1
	    /hdd/junk/zfstest/vdb.img  ONLINE       0     0     0
	    /hdd/junk/zfstest/vdc.img  ONLINE       0     0     0
```

Then I'm wondering how can I know which file and dataset was affected by that data corruption -- This is meaningful for single-disk zpool, from which corrupted data cannot be repaird but will be reported. If `zpool scrub -v` dumps the list of affected files, then single-disk zpool users can check the files by hand and replace those broken files with backup if any.

How do you like it?

**Comment by rincebrain** [comment]
zpool status -v will already tell you what files are affected, in the case of irreparable corruption.

**Comment by CDLuminate** [comment]
I still cannot dump the list of corrupted files with it. Any example?

**Comment by DeHackEd** [comment]
<pre># zpool create testpool mirror /tmp/file2 /tmp/file2
# cd /testpool
# echo "This is a test # 1" > f1
# echo "This is a test # 2" > f2
# cd /
# zpool export testpool
</pre>Corrupt f1 both mirror components, corrupt f2 only one mirror compontent.
<pre># zpool import -d /tmp testpool
# cd /testpool
# ls -l
total 2
-rw-r--r-- 1 root root 19 Oct  7 12:00 f1
-rw-r--r-- 1 root root 19 Oct  7 12:00 f2
# cat f1
cat: f1: Input/output error
# cat f2
This is a test # 2
# zpool status
  pool: testpool
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: none requested
config:

	NAME            STATE     READ WRITE CKSUM
	testpool        ONLINE       0     0     1
	  mirror-0      ONLINE       0     0     2
	    /tmp/file1  ONLINE       0     0     2
	    /tmp/file2  ONLINE       0     0     2

errors: 1 data errors, use '-v' for a list

# zpool status -v
  pool: testpool
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: none requested
config:

	NAME            STATE     READ WRITE CKSUM
	testpool        ONLINE       0     0     1
	  mirror-0      ONLINE       0     0     2
	    /tmp/file1  ONLINE       0     0     2
	    /tmp/file2  ONLINE       0     0     2

errors: Permanent errors have been detected in the following files:

        /mnt/testpool/f1
</pre>

ZFS works fine, no bug here.

**Comment by CDLuminate** [comment]
@DeHackEd Thank you very much, that's exactly what I want to know ;-)

**Comment by CDLuminate** [comment]
problem is solved, closing this issue.
