### ISSUE TITLE
zfs destroy : device is busy and dataset is busy.

### ISSUE THREAD

**Issue by ltz3317** [zfsonlinux/zfs#5327]
I want to destroy a clone.But prompt failure "device is busy",I use lsof and the fuser command cannot be used to find the progress of the directory or file. I try to use "umount -l " unmounted,success.But when I perform destroyed still failed,Tip me "dataset is busy". The clone has no labels and so no. My version is 0.6.3。

**Comment by behlendorf** [comment]
The clone cannot be destroyed because some process is still using it.  This might be a normal application although in that case I would have expected it to be listed by `lsof`.  It may also be that another filesystem is mounted on top of the clone prevent it from being unmounted.  In any case you need to identify what is using the clone before it can be destroyed.

As for the lazy unmount that simply removes the mount point from the namespace.  Any application still using the filesystem is allowed to keep the files open until they no longer need them.  When those files are closed it will be completely unmounted in the kernel.  From `umount(8)`.

```
       -l, --lazy
              Lazy unmount.  Detach the filesystem  from  the  file  hierarchy
              now,  and  clean up all references to this filesystem as soon as
              it is not busy anymore.  (Requires kernel 2.4.11 or later.)
```

**Comment by ltz3317** [comment]
But how can I be sure is that the process is using the clone? I have closed all of my application, but it cannot be destroyed。
