### ISSUE TITLE
install location of python scripts

### ISSUE THREAD

**Issue by Fabian-Gruenbichler** [zfsonlinux/zfs#5344]
Currently, the three python scripts arcstat.py , arc_summary.py and dbufstat.py get installed to `bin_dir` (an autoconf/automake macro), while all the other binaries like zfs and zpool are installed to `sbin_dir`. The `bin_dir` macro is also referenced in the zfs-share.service.in file in the ExecStartPre directive for removing the /etc/dfs/sharetab file.

In practice this means that bin_dir must be set to /bin in a lot of cases (because that is where rm is on most distributions that don't yet have a merged /usr). Debian (and Ubuntu?) decided to put the scripts into /usr/sbin by setting bin_dir accordingly, which broke the zfs-share service file. While this is rather trivial to fix, in the Debian bug report the question arose whether putting the python scripts into bin_dir by upstream is intentional, or whether the three automake files for the scripts should be adapted to install into sbin_dir instead (which would allow reverting the bin_dir macro to point to /bin again).

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842237 for discussion and (potential) patches, any feedback/input welcome.

**Comment by behlendorf** [comment]
The `zfs` and `zpool` commands require root privileges and may be needed prior to `/usr/` being mounted.    For this reason they are intentionally installed under `/sbin/` as described in the [system binaries](http://www.pathname.com/fhs/pub/fhs-2.3.html#SBINSYSTEMBINARIES) section of the FHS.

The python scripts on the other hand require no escalated privileges and will never be needed as part of booting the system and therefore are installed under `/usr/bin/` by default.

If Debian/Ubuntu want to install these commands in a different location in order to conform with their packaging policy that's fine.  But I'd suggest we go about it by extending the autoconf/automake build to take the needed options to specify the desired install path.  This way each distribution can easily do what's right for them.

The project already contains several options like for installing things like udev helpers and rules, systemd units and presets, etc.

**Comment by kpande** [comment]
> this has been fixed in 0.6.5.11-1, which is available in stretch-backports and jessie-backports as well.
