### ISSUE TITLE
kmod 0.7.0rc2 fails to load with Ubuntu Mainline Kernel PPA 4.9rc4

### ISSUE THREAD

**Issue by BenBE** [zfsonlinux/zfs#5388]
Trying to get ZFS on Linux to run with Kernel 4.9rc4[1] results in the following errors when loading the kmod:

> [23798.267897] Disabling lock debugging due to kernel taint
> [23798.579264] zfs: Unknown symbol SHA2Final (err 0)
> [23798.579301] zfs: Unknown symbol SHA2Update (err 0)
> [23798.579324] zfs: Unknown symbol SHA2Init (err 0)
> [23798.579366] zfs: Unknown symbol EdonRInit (err 0)
> [23798.579460] zfs: Unknown symbol Skein_512_Update (err 0)
> [23798.579594] zfs: Unknown symbol EdonRHash (err 0)
> [23798.579760] zfs: Unknown symbol EdonRUpdate (err 0)
> [23798.579959] zfs: Unknown symbol Skein_512_InitExt (err 0)
> [23798.580024] zfs: Unknown symbol Skein_512_Final (err 0)
> [23798.580037] zfs: Unknown symbol EdonRFinal (err 0)

Running with tagged 0.7.0rc2 versions of spl[2] and zfs[3] repos (replacing all source in Ubuntu Source packages with version from git).

Would be nice if this error could be detected while building the kmod with DKMS.

[1] Ubuntu Mainline Kernel PPA: http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9-rc4/
[2] https://github.com/zfsonlinux/spl/
[3] https://github.com/zfsonlinux/zfs/

**Comment by behlendorf** [comment]
@BenBE a very similar issue for DKMS builds was was address by af322de.  The icp.ko mdule which includes these symbols wasn't getting packaged.

**Comment by MyPod** [comment]
I'm looking into this issue as I am facing it in a similar environment - Ubuntu Yakkety with manually built spl and zfs from git master. Despite updating zfs-initramfs from the official one to the one resulting in the build of the zfs repository, initramfs-tools do not include the icp module and thus the system fails to boot afterwards.

It should be noted that currently /usr/share/initramfs-tools/hooks/zfs states that modules should all be specified for inclusion, but it doesn't state icp among these, and even when appending it to the strings of the modules to be included in the initrd, it is still missing, as proven by a broken boot/lsinitramfs.

I should also add - and this is perhaps an issue with Ubuntu - the kmod*.deb packages install in /lib/modules/<kernel-version>/extra, which is not picked up in the initramfs, whereas /lib/modules/<kernel-version>/kernel/zfs (which is packaged along the kernel) is preferred. When the latter is removed, the extras folder is not picked up, and initramfs ends up not having any modules from spl/zfs.

**Comment by MyPod** [comment]
The issue I was facing seems to come from the particular setup I was using - I had not yet rebooted after installing a kernel update, and I built the modules against the new kernel. This setup prevented me from issuing a depmod, and update the dependencies on zfs.ko (which doesn't ship icp.ko).
In my testing depmod/update-initramfs also seems to prefer Ubuntu's version of zfs whenever present rather than the one I built, so the folder under kernel has to be removed along with its content to generate an initramfs with the updated kernel module.
Also, to be true to [this statement](https://github.com/zfsonlinux/zfs/blob/master/contrib/initramfs/hooks/zfs#L20) the icp module should be included in the list.

I would also like to ask to anybody more experienced what is the proper procedure to follow in case of a kernel update, after having rebuilt the custom zfs modules.

I'd like to ask to more experienced users what would the recommended strategy be
