### ISSUE TITLE
Debian ZFS Root Instructions

### ISSUE THREAD

**Issue by dave-fl** [zfsonlinux/zfs#5566]
@gmelikov and @rlaager.  Any reason why /var is not being set to its own file system.  This seems a bit different from other distributions.

**Comment by gmelikov** [comment]
Additional datasets structure is only recommended, you can create them as you need.
These datasets were copied from Ubuntu instruction.

Please, use mailing lists for support questions.

**Comment by rlaager** [comment]
Since it was asked here, I will answer here. The reason I don't have /var itself separate is because /var is a mix of OS data and user data. The design goal is that we could have something similar to beadm that manages "boot environments". If I install software updates and my system stops working, I want to be able to roll back. But when I do the roll back, I do not want to lose my (user) data. So the data that is part of the OS (e.g. /var/lib) should be rolled back, but data that is mine (e.g. /var/spool) should not. Granted, maybe /var/lib isn't a perfect example, as that could be yet another level of mixed stuff. But the general idea here is to keep everything together in the root filesystem _except_ user data that we specifically separate out: /home, /root (which is just a special home directory), and some stuff in /var.
