### ISSUE TITLE
Feature request: Detection of low performance devices

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#5569]
I'm using the latest version of ZFS on Linux under CentOS 7 as hypervisor. This machine runs nearly a dozend systems and had run fine for 3 years.

The monitoring yesterday had yelled at me because of continuous timeouts on one of the web services, so I took a look on the hypervisor graphs from Munin.

I've discovered that there is an issue with the HDDs - they run on two partitions of two disks as mirroring ZFS-pool.

![diskstats_utilization-week](https://cloud.githubusercontent.com/assets/614929/21743816/7624bff6-d50a-11e6-9454-be8e7c10048b.png)

It's pretty easy to see, that the second disk have some troubles or have a heavy workload. I took a look at atop, the disk in question was at 100% while only doing write, all reads are served by the other disk, which did nearly no writes.

So there was a huge disparity between those two disks, one was nearly not capable of handling those writes and the other one was serving only the reads.

So my feature request is, to wrote a simple detection for this issue and send it via zed to the administrator. It should be easy to detect if read-workloads move complete away from a disk because it is completely busy.

Well, in case someone is interested in smart values, they are all fine. I had also started the long offline test, this returned also as "fine". Currently. the disk is working normally again, but I have no clue how long.

The ambient temperature in this datacenter seems to be fairly low at the moment - disks reporting self-temperature between 6°C and 8°C, I guess they cool the systems with outside air which is currently around 0°C.

**Comment by gmelikov** [comment]
Offtopic, but i think 6-8C temperature is not normal for HDD...

**Comment by richardelling** [comment]
> On Jan 7, 2017, at 10:00 AM, @RubenKelevra <notifications@github.com> wrote:
> 
> I'm using the latest version of ZFS on Linux under CentOS 7 as hypervisor. This machine runs nearly a dozend systems and had run fine for 3 years.
> 
> The monitoring yesterday had yelled at me because of continuous timeouts on one of the web services, so I took a look on the hypervisor graphs from Munin.
> 
> I've discovered that there is an issue with the HDDs - they run on two partitions of two disks as mirroring ZFS-pool.
> 
>  <https://cloud.githubusercontent.com/assets/614929/21743816/7624bff6-d50a-11e6-9454-be8e7c10048b.png>
> It's pretty easy to see, that the second disk have some troubles or have a heavy workload. I took a look at atop, the disk in question was at 100% while only doing write, all reads are served by the other disk, which did nearly no writes.
> 
> 

A disk that is 100% busy deserves more detailed analysis. However, the definition of %busy doesn’t 
help very much beyond identifying candidates for more detailed analysis. What matters for performance
is response time and the best, generally available measurement in Linux is iostat’s await or more detailed
await_[rw]. Let’s take a HDD failure mode for an example…

Consider a HDD that has difficulty with an area on one surface. The causes could be prior head strike,
flaky actuator, or media defects. When accessing that area or LBA range, the drive can go into extra
error recovery mode that can require additional rotations, thus increasing latency. Applications like ZFS
don’t have visibility into why the accesses at those LBAs are slow and as long as they ultimately succeed,
data is good, so life is good.

There is an important aspect of this type of fault to remember: only some LBAs are affected. The rest of
the disk can operate just fine. So detecting this isn’t a matter of detecting the “disk is slow” it is a much 
more difficult problem of “some (perhaps one) LBAs on the disk are slow”  Also, various drivers in the 
stack below ZFS can timeout/retry accesses in addition to any retry/recovery in the drive. The net-net
of this is that accessing some data could take much longer, perhaps seconds longer, than data right next
to the affected LBAs. So the next metric to look at is await. Ideally, for HDDs await is well below 100ms.
If not, then consider replacing the drive.
> So there was a huge disparity between those two disks, one was nearly not capable of handling those writes and the other one was serving only the reads.
> 
> So my feature request is, to wrote a simple detection for this issue and send it via zed to the administrator. It should be easy to detect if read-workloads move complete away from a disk because it is completely busy.
> 
> 

The difficulty is not in detecting high latency, it is in avoiding false positives. Latency can occur in many
parts of the datapath between the CPU and drives, you don’t want to fail a drive because the HBA
got busy or, using a more common high-latency case, the ethernet switch between the initiator and iSCSI
target rebooted.
> Well, in case someone is interested in smart values, they are all fine. I had also started the long offline test, this returned also as "fine". Currently. the disk is working normally again, but I have no clue how long.
> 
> 

This is a common symptom of the failure mode described above: everything looks fine, because you
aren’t looking at every single LBA on the drive.
> The ambient temperature in this datacenter seems to be fairly low at the moment - disks reporting self-temperature between 6°C and 8°C, I guess they cool the systems with outside air which is currently around 0°C.
> 
> 

This is at the bottom of the specified operating range for some HDDs, typically 5C. When you get towards the margins,
the failure modes described above can become more prevalent.

More modern versions of ZFSonLinux keep a histogram of latency for each device. This information is available
until the next reboot or the pool is exported. But it is invaluable for detecting if one or a group of devices (eg iSCSI
example above) see abnormally high latency. See zpool iostat -w
 — richard


--

Richard.Elling@RichardElling.com
+1-760-896-4422

**Comment by kpande** [comment]
this is not the forum for such requests, try the OpenZFS mailing list.
