### ISSUE TITLE
Modules Load Late on Debian/Stretch

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [zfsonlinux/zfs#5607]
Hello. I'm trying to get ZFS working on Debian/Stretch, but the modulle seems to load very late at the boot stage.

Case 1: Root on rpool/ROOT/debian9 - dorps to busybox, "stating cannot find root". ""lsmod shows no zfs modules, "modprobe zfs" shows modules being loaded after this command. Modifying grub.cfg to include "modules-load=zfs" on the linux line has no effect.

Case 2: I have a second root on ext4 to boot from there as option, and have /usr and /var are on separate rpool/dataset. I renamed /usr and /var on the ext4 root and created empty folders. I modified /etc/fstab to mount /usr and /var from their respective datasets (mountpoint=legacy). When I reboot into the ext4 root, I get kernel panic, most likely because the ZFS datasets don't get mounted.

There were also new erorrs with update-grub after sytem was updated today. Running update-grub inside chroot of rpool/ROOT/debian9, I got "there's no /dev/null" as well as no /dev/zfs errors. I'll try and document that issue better after I rescue the ext4 root.

Regards.

**Comment by Beeblebrox-BSD** [comment]
The error was probably due to not using Dracut. I could not test unfortunately, as a system upgrade brought kernel up to 4.9.0-1-amd64. While upgrading, compile for SPL failed, so I now have no ZFS as of this upgrade.
Compile error log attached.

https://drive.google.com/file/d/0Bxs_eepbMt6qQnBCZlM1b1plQzA/view?usp=sharing

**Comment by scotte** [comment]
I have ZFS rootfs (100% ZFS) working fine on Debian stretch (4.8 kernel), as long as I generate the grub config with:

GRUB_CMDLINE_LINUX="boot=zfs \$bootfs"

4.9 is a problem, likely due to aio_fsync removal - see https://github.com/zfsonlinux/zfs/commit/7ca25051b6470e8471b4ed454d8c66ff21338de3 - I have not tried the patch myself and don't know if setxattr/getxattr/removexattr errors are related.

**Comment by gmelikov** [comment]
Please use mailing lists for support.

We have the [actual instruction for Debian Jessie](https://github.com/zfsonlinux/zfs/wiki/Debian%20Jessie%20Root%20on%20ZFS).

**Comment by scotte** [comment]
I know this was closed, but I'll comment anyway - "actual instruction for Debian Jessie" - this issue was about Debian Stretch, not Jessie. But, given that Stretch freezes today (in UTC), ZFS has missed the boat anyway, since the version of ZFS in Stretch won't work for kernels >4.8. Too bad - it would be really nice if ZFS was a first-class citizen in Debian. :-(

**Comment by behlendorf** [comment]
Debian Stretch can use the [0.6.5.9 release](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.9) which was tagged a few days ago and supports 4.9 kernels.
