### ISSUE TITLE
du doesn't report the correct size immediately

### ISSUE THREAD

**Issue by RJVB** [zfsonlinux/zfs#5617]
Git-eradicate is a script I have that prunes and reorganises a .git directory, printing on-disk size before and after:
```
#> git-eradicate
> 12M   .git/
Counting objects: 21565, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (20038/20038), done.
Writing objects: 100% (21565/21565), done.
Total 21565 (delta 12293), reused 9072 (delta 0)
< 471K  .git/
```

Nice gain, eh? Now I wait a bit and call `du -hcs .git`:

```
#> du -hcs .git
8.1M    .git
8.1M    total
```

Adding `sync ; sleep 1 ; sync ; sleep 1` before the final du in the git-eradicate script reduces the discrepancy but doesn't always make it disappear completely.

This is on a single-device dataset with copies=1 and compression=lz4 .

Is this is an actual issue or a harmless side-effect?

**Comment by kpande** [comment]
please use the [mailing list](http://list.zfsonlinux.org) for support questions like this unless you've verified an actual bug.

**Comment by DeHackEd** [comment]
Duplicate of #2134

This is expected behaviour. Btrfs does the same thing. Not a bug.

**Comment by nh2** [comment]
Just for completeness and ease of linking:

`du` without `--apparent-size` uses the underlying storage's used size, which can _vary over time_ in some implementations (like ZFS and Btrfs).

So, unless you're interested in the numbers from the underlying storage implementation:

Never use `du` without `--apparent-size`, or else results may change any second.

**Comment by DeHackEd** [comment]
`du` without `--apparent-size` is useful for determining the compression ratio for a file on disk. However you have to wait for the file to be compressed and committed to disk which may take upwards of 5-10 seconds typically as these are background operations.

When I use `du` the question is usually "where is all my disk space going?" which is a different question from "where are the biggest files?" Even on ext4 you wouldn't use `--apparent-size` most of the time because sparse files will still give smaller file sizes which is still relevant to the question of usage.

**Comment by RJVB** [comment]
>When I use `du` the question is usually "where is all my disk space going?" which is a different question from "where are the biggest files?" Even on ext4 you wouldn't use `--apparent-size` most of the time because sparse files will still give smaller file sizes which is still relevant to the question of usage.

Exactly, and remember, `du` stands for `disk use` (or usage). For that reason I even started an exchange with the maintainers about the name of the `--apparent-size` option because it isn't the most happy choice (you have to think too much about it...)
