### ISSUE TITLE
ZFS allows unmounting filesystem that is still in use

### ISSUE THREAD

**Issue by brauner** [zfsonlinux/zfs#5796]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    |  Xenial (16.04)
Linux Kernel                 |  4.4 - 4.9 (occurs on multiple versions)
Architecture                 | x86_64
ZFS Version                  | 0.6.5.8-0ubuntu7
SPL Version                  |  0.6.5.8-2ubuntu1

### Describe the problem you're observing

- create a zfs dataset and mount it
- mount the mountpoint of the dataset somewhere else
- unmount the zfs dataset
- the zfs mountpoint will be empty (as expected)
- the second mountpoint will still reference all files
- the zfs dataset cannot be remounted with zfs mount

### Describe how to reproduce the problem

    zfs create tank/test
    zfs set mountpoint=/tank-test tank/test
    touch /tank-test/tank-test-file
    mount -B /tank-test /mnt
    zfs umount tank/test
    ls -al /tank-test/ (filesystem unmounted, file not found)
    ls -al /mnt (filesystem still referenced and file still found)
    zfs mount tank/test (will complain about dataset being mounted)

### Include any warning/errors/backtraces from the system logs

Example:
```
this is an example how log text should be marked (wrap it with ```)
```
-->

**Comment by stgraber** [comment]
@brauner what's the expected behavior here?

I seem to recall other filesystems would similarly let you unmount the source path since that path isn't actually used (no open fds) but you'd be able to mount it again too.

**Comment by brauner** [comment]
Yes, I'd expect that you'd be able to remount the filesystem. The fact that someone else (e.g. another namespace) is holding a reference to it shouldn't matter.

**Comment by ddstreet** [comment]
Has there been any progress on this?

**Comment by kpande** [comment]
you can manually unmount the extra mount point, and then it allows remount. doesn't seem like a bug here.

if you are writing to the /tank-test directory, zfs will not allow unmount.

if you are writing to the bind mount, it allows unmount of /tank-test, but not /mnt.

basically, the mount point you were writing to was not actually in use and neither was the bind mount.

for my test, I used `dd if=/dev/urandom of=/tank-test/file bs=512b &` to put a writer into the background (or /mnt/file).

**Comment by brauner** [comment]
I didn't see that you were responding here. Sorry for the late reply. This has nothing to do with someone writing to the mount point. If you umount the original mountpoint but there's still bind-mount somewhere there's no reason not to allow to mount to the original mountpoint again. Consider the same test with btrfs which works fine:

    truncate -s 10GB random.btrfs
    mkfs.btrfs -L random random.btrfs
    mount -t btrfs btrfs.random /mnt
    # assume we have been given /dev/loop5
    btrfs subvolume create /mnt/bla
    umount /mnt
    mount -t btrfs -o subvol=bla /dev/loop5 /test
    touch /test/blabla
    mount -t bind /test /test2
    umount /test
    mount -t btrfs -o subvol=bla /dev/loop5 /test

works fine. Same with lvm.

**Comment by sforshee** [comment]
The problem here is in the way the zfs kernel module implements mount. Normally a test callback is passed to sget() to check whether the filesystem is already mounted, then sget() returns the existing super block and a new mount is created for that super block. But zfs calls mount_nodev() which does not pass a test callback, assuring every mount gets a new super block. Then zpl_fill_super() is called and finds that the dataset is already mounted, and the mount fails.

Instead zfs should call sget() directly with its own test callback, something along the lines of this (note that I implemented it against an Ubuntu kernel tree with the zfs source included):

https://paste.ubuntu.com/26505860/

I'm not sure whether that's the best way to check if the dataset is already mounted, and the patch could be improved, but it does demonstrate how the problem can be fixed.

**Comment by behlendorf** [comment]
@sforshee nice analysis, thanks for taking the time to run this one to ground!  That nearly explains the root cause of this issue.   Would you mind opening a PR with your proposed fix?  That'll make it easier for us to provide review feedback so we get this polished up (works for a range of kernels, a test case, style, etc).  The core approach you took looks solid.  If you'd rather not just let us know and we can round up someone to take over.  Thanks!
