### ISSUE TITLE
How to install on NVME Raid-10?

### ISSUE THREAD

**Issue by ivoryblade** [zfsonlinux/zfs#5838]
Hello! I'm trying to install Debian Jessie on ZFS Raid-10 root (6 NVME SSDs). I followed the guide but first boot always fail. 

```
error: unknown device 2
```
Grub successfully installed on all drives. But it doesn't boot from my zfs pool. 
I thought the problem is in SSDs so I tried to install Debian on SATA SSD and create pool from there and everything went ok.

**Comment by gmelikov** [comment]
Looks like Grub doesn't support your NVME, please check it.   27.02.2017, 14:23, "ivoryblade" <notifications@github.com>:Hello! I'm trying to install Debian Jessie on ZFS Raid-10 root (6 NVME SSDs). I followed the guide but first boot always fail.error: unknown device 2
Grub successfully installed on all drives. But it doesn't boot from my zfs pool.I thought the problem is in SSDs so I tried to install Debian on SATA SSD and create pool from there and everything went ok.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ivoryblade** [comment]
Thanks for reply! But how can i check if grub supports this kind of disks?
