### ISSUE TITLE
Fix some issues on Debian-Jessie-Root-on-ZFS wiki page

### ISSUE THREAD

**Issue by RichieB2B** [zfsonlinux/zfs#5851]
### Describe the problem you're observing

The  Debian-Jessie-Root-on-ZFS.md contains some errors:
- mentions ubuntu in several places
- the Debian Jessie Live CD does not support UEFI

Since GitHub does not allow pull requests for a wiki, I've attached the patch.
[Debian-Jessie-Root-on-ZFS.patch.txt](https://github.com/zfsonlinux/zfs/files/811543/Debian-Jessie-Root-on-ZFS.patch.txt)

**Comment by jwittlincohen** [comment]
The link to the Debian Live DVD is also dead.

**Comment by KwadroNaut** [comment]
The GRUB from testing should be sufficient these days: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824974 So the unstable pieces can be removed.
Ping @gmelikov and @rlaager.

**Comment by gmelikov** [comment]
@RichieB2B @jwittlincohen thank you, I updated the wiki.

But I have to add that this instruction is for experienced users, so it's not the best case to make an install script for now.

If you have something more to add or change - just send me a patch.

**Comment by jwittlincohen** [comment]
@gmelikov 

Thanks for making the requested changes.  I have two more changes I would like to add to the Wiki.  The first resolves a package dependency failure caused by installing Grub's dependencies from Testing rather than Stable.  The Howto instructs users to install grub-pc from Testing, but the command used also installs all of its dependencies from Testing, even though they can be satisfied from Stable.  One of the consequences of this is that a version of libfuse2 is installed which is incompatible with Gnome and even the more limited Gnome-Core.  I'm sure there are other package management issues but this is the only one I ran into.  The solution is to install Grub's dependencies from Stable first, and then install grub-pc.  I tested this and it resolves the problem.

The second change is really just a reminder.  ZFS generally recommends passing whole disks to ZFS to ensure optimal performance (proper partition alignment for one).  As a result, I kept using whole disks when entering the zpool create command, which of course repartitioned the disks, eliminating the BIOS partition.  I just added a reminder to refer to the partition "part1" and not the whole disk.  

Please find the above changes in this patch:  [http://pastebin.com/SU4Am9A0](url)

**Comment by rlaager** [comment]
Does this work? Specifically, does GRUB from Stable fail to install? If so, is that something we can ignore?
```
apt install --yes grub-pc
apt install --yes -t testing grub-pc
```

**Comment by jwittlincohen** [comment]
@rlaager 

Installing from stable and then upgrading grub-pc from unstable works fine, and resolves the dependency issue I was having.  Tested in a VM.

**Comment by rlaager** [comment]
Thanks. I've made that change to the HOWTO.

I used this language for the partition warning, for both Debian and Ubuntu:
Make sure to include the `-part1` portion of the drive path. If you forget that, you are specifying the whole disk, which ZFS will then re-partition, and you will lose the bootloader partition(s).

**Comment by jwittlincohen** [comment]
Looks good, thanks for making these changes.
