### ISSUE TITLE
[Feature Request] Add support for building DKMS ZFS and SPL binaries for Debian/Ubuntu

### ISSUE THREAD

**Issue by jwittlincohen** [zfsonlinux/zfs#6044]
### Describe the problem you're observing

Feature Request:  Currently, the build scripts for ZFS/SPL only allow building kmod packages for Debian and Ubuntu.  In contrast, it is possible to build DKMS packges for CentOS/RHEL and Fedora.  It would be very useful to have DKMS packages for Debian and Ubuntu so that the ZFS and SPL modules can be automatically rebuilt after a kernel upgrade.  This is described [here](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages).

### Describe how to reproduce the problem

Upgrading the kernel with the kmod package requires rebuilding the ZFS and SPL packages for the new kernel.

**Comment by Conan-Kudo** [comment]
@jwittlincohen The ZFS build system will produce dkms packages that work on Debian/Ubuntu if the prerequisites are installed. In addition, that distribution family has taken over maintenance and development of packaging officially as `zfs-linux` downstream.

Is there something else you wanted?

**Comment by zrav** [comment]
Also note that Ubuntu does not provide up-to-date packages for 16.04 LTS so a documented way of building DKMS packages for it would be welcome.

**Comment by jwittlincohen** [comment]
I checked the Makefile in the ZFS 0.7.0-rc3 source package.  All references to DKMS relate to the script rpm-dkms build script.  As the name suggests, this only produces RPMs. :)

**Comment by kpande** [comment]
https://launchpad.net/ubuntu/+source/zfs-linux/0.6.5.9-5ubuntu4

you can use the ubuntu src packages to build your own dkms.

**Comment by MasterCATZ** [comment]
but how do we build deb for 0.7 ? 
trying to get something working with kernel 4.11 on ubuntu 

the 0.7 spl built and installed fine 
but zfs, not much luck so far 
also trying to work out how to get the latest spl-dkms

Unpacking zfs-dkms (0.6.5.9-5ubuntu4) over (0.6.5.9-5ubuntu4) ...
Setting up zfs-dkms (0.6.5.9-5ubuntu4) ...
Loading new zfs-0.6.5.9 DKMS files...
Building for 4.11.0-041100-generic
Building initial module for 4.11.0-041100-generic
configure: error: 
	*** Please make sure the kmod spl devel <kernel> package for your
	*** distribution is installed then try again.  If that fails you
	*** can specify the location of the spl objects with the
	*** '--with-spl-obj=PATH' option.
ERROR (dkms apport): kernel package linux-headers-4.11.0-041100-generic is not supported
Error! Bad return status for module build on kernel: 4.11.0-041100-generic (x86_64)

**Comment by gmelikov** [comment]
@MasterCATZ v0.6.5.9 doesn't support 4.11 kernel, next time please read package description. Build beta 0.7.0 or wait for 0.6.5.10.

**Comment by Trucido** [comment]
There's multiple issues with this issue.  
1. Both Debian and Ubuntu already have zfs-dkms packages, last I checked.
2. Ubuntu kernels (and forks like proxmox) provide zfs/spl in-tree (this requires extra work if wanting to use your own) 
3. Debian definitely does have dkms packages for zfs via the zfs-dkms package (and zfs-initramfs if needing zfs on boot)  
4. This is a downstream issue, zfsonlinux doesn't mean "provide easy access to the latest bleeding edge versions for every distro", especially when the distro(s) in question maintain their own zfs. One or more of the RPM-based distros likely contributed code for the upstream dkms stuff, I don't think it's being treated special or anything but it /is/ kind of a special case due to zfs being intended moreso for large scale server and many servers run on RPM based distros. Upstream also probably has a headache remaining compatible with older system libraries and kernels.  
  
Regarding the issue though, If using an Ubuntu kernel and wanting to use a different zfs/spl, dkms actually is a blocker because it detects an existing zfs/spl and doesn't automatically build out of tree versions and as far as I know there's no way to globally override dkms to --force it to use your own (it checks version number only, and version != version across all debian variants).  
  
When I was testing some Ubuntu kernels on Debian I ran into this issue with dkms. You kinda have to do some variant of this;  
`dkms build --force -m spl -v $SPLVER -k $KVER`
`dkms build --force -m zfs -v $SPLVER -k $KVER`
`dkms install --force -m spl -v $ZFSVER -k $KVER`
`dkms install --force -m zfs -v $ZFSVER -k $KVER`  
This is, of course, assuming that your zfs/spl packages HAVE dkms config files and source trees (usually in /usr/src). Back when I was using ubuntu-based kernels I had an ugly hackjob script to auto rebuild my modules, if anyone finds it useful it's here (updated slightly today to support multiple kernels and zfs source trees, but not well tested. original code is in the top comments): [https://gist.github.com/Trucido/17481dfecd01a8befa5a2308f4b45569](https://gist.github.com/Trucido/17481dfecd01a8befa5a2308f4b45569)  
  
  
If wanting to use a newer version of zfs, the existing dkms files in from the package repos would likely work but may need some slight modification.
HOWEVER, this also presents another issue of mismatched zfsutils-linux and friends. (libzfs2linux, libzpool2linux, zfs-zed, etc). All of this stuff is tightly integrated, and even moreso on Ubuntu than Debian.  
  
This is more of a downstream issue though and I don't believe it belongs here. You could check some of the downstream repos though (like unstable/experimental has 4.11 kernels, so their zfs source repository may have newer versions as well). Likewise for Ubuntu you could check their testing/unstable repos (usually the next distribution release codename). However, this requires advanced apt pinning of packages and repos if you want upgrades to work properly.

**Comment by MasterCATZ** [comment]
Thanks Trucido  
I will give that script a go tomorrow 

still, no idea where to find "beta 0.7.0" for Ubuntu

**Comment by kernelOfTruth** [comment]
https://launchpad.net/~zfs-native/+archive/ubuntu/daily

**Comment by MasterCATZ** [comment]
thanks when I last looked that was last updated 162 weeks ago

**Comment by kernelOfTruth** [comment]
@MasterCATZ yeah, not sure why it isn't updated daily when it clearly notes that it is updated daily "Native ZFS for Linux daily builds"

**Comment by MasterCATZ** [comment]
W: The repository 'http://ppa.launchpad.net/zfs-native/daily/ubuntu zesty Release' does not have a Release file.

looks like I still have to wait for Ubuntu to do the zfs update on their end 
any other idea's 

spl, 0.6.5.9, 4.10.0-22-generic, x86_64: installed
spl, 0.6.5.9, 4.10.12-041012-generic, x86_64: installed
spl, 0.6.5.9, 4.10.6-041006-generic, x86_64: installed
spl, 0.6.5.9, 4.10.8-041008-generic, x86_64: installed
zfs, 0.6.5.9, 4.10.0-22-generic, x86_64: installed
zfs, 0.6.5.9, 4.10.12-041012-generic, x86_64: installed
zfs, 0.6.5.9, 4.10.6-041006-generic, x86_64: installed
zfs, 0.6.5.9, 4.10.8-041008-generic, x86_64: installed


downside being I need kernel 4.11 for my AMD ryzen CPU to work ...

**Comment by yuqingdeng** [comment]
I build rpm first and use alien to convert dkms noarch.rpm to deb.  That works.

**Comment by satmandu** [comment]
Do running commands like "zpool status" from installs of alien converted rpms of 0.7.x on a debian system still give you errors like this:

```
:~$ zpool status
Permission denied the ZFS utilities must be run as root.
```

**Comment by jwittlincohen** [comment]
Does the RPM --> DEB method install working systemd unit files?  When I build the kmod packages for Stretch, I have to manually mount my /home partition because systemd zfs.target service doesn't start.  See https://github.com/zfsonlinux/zfs/issues/6435.

**Comment by yuqingdeng** [comment]
I only converted dkms rpm to deb.  Same problem, I have to import zfs by hand after 0.7 upgrade.

**Comment by tristan-k** [comment]
This is so annoying. I'm using Kernel with help of the [Ukuu Kernel Update Utility]() on Ubuntu 16.04 and I'm unable to use ZFS. The PPA https://launchpad.net/~zfs-native/+archive/ubuntu/daily only supports Trusty. Right now I dont know how to get ZFS to play well with Ubtuntu 16.04 and a newer Kernel.

```
Loading new zfs-0.6.5.6 DKMS files...
First Installation: checking all kernels...
Building only for 4.11.2-041102-generic
Building initial module for 4.11.2-041102-generic
configure: error: 
	*** Please make sure the kmod spl devel <kernel> package for your
	*** distribution is installed then try again.  If that fails you
	*** can specify the location of the spl objects with the
	*** '--with-spl-obj=PATH' option.
ERROR (dkms apport): kernel package linux-headers-4.11.2-041102-generic is not supported
Error! Bad return status for module build on kernel: 4.11.2-041102-generic (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.6/build/make.log for more information.
```

**Comment by satmandu** [comment]
You need to make the change in the spl source mentioned here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836578

in the spl debian/dkms:

```
-POST_INSTALL="cp
+POST_BUILD="cp
   ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/spl_config.h
   ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/module/Module.symvers
   ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/${kernelver}/${arch}/
```

**Comment by jwittlincohen** [comment]
I was able to successfully build and install SPL and ZFS 0.7.3 DKMS packages.  DKMS built the kernel modules for both SPL and ZFS on installation.  However, something is wrong because when I run `update-initramfs -u -k all` the resulting initrd does not contain the ZFS modules, even if I run `depmod -a` first.  As a result, I can't use the resulting initrd to boot my ZFS root pool.  If I compile with kmod packaging, the initrd contains the necessary modules.

It's possible I'm just doing something wrong since the custom build guide was not updated for DKMS on Debian.  Here were the steps I took:

SPL:
1) autoreconf --force --install
2) ./configure
3) make pkg-utils deb-dkms
4) for file in *.deb; do sudo gdebi -q --non-interactive $file; done

ZFS:
1) autoreconf --force --install
3) ./configure --with-config=srpm
4) make pkg-utils deb-dkms
4) for file in *.deb; do sudo gdebi -q --non-interactive $file; done
5) sudo depmod -a 4.13.0-amd64
6) sudo update-initramfs -u -k all
7) lsinitramfs initrd.img-4.13.0-1-amd64 | grep zfs (to verify that ZFS modules are in the initrd)

**Comment by MyPod** [comment]
@jwittlincohen could you try to check what update-initramfs is doing verbosely and also whether you have `/usr/share/initramfs-tools/hooks/zfs` properly importing the needed modules?

**Comment by sjau** [comment]
So, I managed to build an encrypted root zfs on debian. I created according bash scripts for qemu if anyone wants to try.

What I basically did is:

1. Boot Debian Live CD (I just used xfce because it's smallest)
2. Add sources list and install dependencies for building zfs
3. Building zfs from git-master using jwittlincohen instructions here: https://github.com/zfsonlinux/zfs/issues/6044#issuecomment-338484555
4. Then use sgdisk to auto partition /dev/sda
5. Create pool, encrypted data set and then a subdata set for root, mostly following instructions here: https://github.com/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS
6. Then chroot into the new system to run the chroot-install script which will bascially redo adding sources.list, get dependencies, build zfs from master again....

However there are a few issues:

The initrd contains a zfs script which works nice in general but it does not unlock encrypted datasets becuase `zfs load-key -a` is missing.

So I did unpack the created initrd:
```
mkdir /tmp/initrd
cd /tmp/initrd
gzip -cd /boot/initrd.img-4.9.0-4-amd64 | cpio -i
```
I went to the script folder and edited the `zfs` script.
Before the secion 
```
	# ----------------------------------------------------------------
	# P R E P A R E   R O O T   F I L E S Y S T E M
```
I just added the zfs load-key -a command:
```
        zfs load-key -a
	
        # ----------------------------------------------------------------
	# P R E P A R E   R O O T   F I L E S Y S T E M
```
Saved it and created initrd again (but named it different so that I still ahve the original one:
`find . | cpio --dereference -o -H newc | gzip > /boot/initrd.new`

However grub still has two issues with the boot entry; upon reboot you need to edit the entries. The linux line looks by default for me like this: `linux        /vmlinuz-4.9.0-amd64 root=ZFS=/encZFS/Root ro  quiet`

Two things are missing there:
you need to add `boot=zfs` so that the zfs script is actually executed and also for some reason it did not add the zpool name properly to the root= entry.

In the end I needed to change it manually to: `linux        /vmlinuz-4.9.0-amd64 boot=zfs root=ZFS=tankie/encZFS/Root ro  quiet`

Also, since I altered the zfs script in the original initrd and renamed the initrd, I had to adjust that entry as well to the new initrd: `initrd        /initrd.new`

A video can be found here:  https://youtu.be/JrT9dQFTtFA

The scripts used for creating the VM are here:  https://github.com/sjau/bash-stuff/tree/master/ZFS-Debian

`qemuSetup`:  This script just creates the qemu disk and also two bash launchers for the vm - one with live dvd, one without

`install` & `chroot-install`: Both scripts need to go into the booted live dvd session into the /root folder

After that run run first the `install` script, it will ask for a few things but should be easy to answer... at the end copies the `chroot-install` script to `/mnt/root/` and it will chroot into /mnt.

Just change dir to `/root` then and run the `chroot-install` script.

Once done, you need to unpack the generated intitrd and make the above mentioned change to the zfs script inside - I haven't automated this yet. Repack it and reboot.

Upon reboot, edit the grub entries as explained above and shown in the video.

**Comment by pstch** [comment]
@jwittlincohen I spent a bit of time reading the build scripts, and from what I've gathered, you want to use `--with-config=user` to build proper DKMS packages. `--with-config=srpm` expects all of the configuration to come from the source package, removing the ZFS_AC_CONFIG_USER function from the configuration.

When I build with `--with-config=user`, I get proper DKMS packages with systemd unit files and `modules-load.d` preset.
