### ISSUE TITLE
What is the purpose of 8MB Solaris reserved 1 partition?

### ISSUE THREAD

**Issue by niksfirefly** [zfsonlinux/zfs#6110]
When i create zfs pool - disk is partitioned with scheme
1 partition - type: Solaris /usr & Apple ZFS for  data
2 partition - type: Solaris reserved 1

I wonder what is the purpose of 8MB Solaris reserved 1 partition?

**Comment by kpande** [comment]
as described in the template you completely ignored when posting this issue, please use [the mailing list](http://list.zfsonlinux.org) for general discussion, this is the development issue tracker.

**Comment by bernstein82** [comment]
it's another one of those legacy things... completely redundant if you just use modern linux/freebsd systems. see https://serverfault.com/questions/847513/zfs-on-linux-deleting-the-solaris-reserved-1-partition-did-i-break-anything

**Comment by misterbigstuff** [comment]
dear god this post is >3 years old, and it was already closed. and your answer was wrong. this is to prevent differently sized hdd from different vendors from preventing disk replacement due to being 'off' in size by a few MiB.

**Comment by bernstein82** [comment]
sorry for digging it up; thanks for taking the time to provide an answer!

as for why i dug it up :
- this issue is the first google search result for the query "Solaris reserved 1 partition" which is what one searches for if looking after `lsblk` output and wondering about that partition.
- since the issue was missing an answer and the another google result seemed to provide an anwser, i thought i might might be good to crosslink that...

**Comment by rieje** [comment]
Are there any references? AFAIK the initial answer is correct--besides the answer in the thread there's:

* https://www.reddit.com/r/zfs/comments/g1rtca/automatic_vs_manual_creation_of_reserved_space/fnikk9h/
* https://www.reddit.com/r/zfs/comments/vuagd1/mirror_size_differ/ifdgtgq/

**Comment by ouonline** [comment]
Are there any options can be passed to `zpool create` to use the whole disk? `-o compatibility=off` seems to be useless.

**Comment by GogoFC** [comment]
> dear god this post is >3 years old, and it was already closed. and your answer was wrong. this is to prevent differently sized hdd from different vendors from preventing disk replacement due to being 'off' in size by a few MiB.

Two more years later and now I'm here :) 

If the two disks are different is size ZFS won't let you add them to a mirror vdev anyway. Cutting off 8MB from each disk will still leave those disks different in size.

**Comment by ranisalt** [comment]
8MB might be too little. I have disks from the same brand, but of different series, and they differ by more than 8 MiB:

Seagate Ironwolf 12TB:
```
Disk /dev/sda: 10.91 TiB, 12000138625024 bytes, 23437770752 sectors
Disk model: ST12000VN0008-2Y
```

Seagate Enterprise Capacity 12TB:
```
Disk /dev/sdc: 10.92 TiB, 12001339219968 bytes, 23440115664 sectors
Disk model: ST12000NM0127
```

They differ by ~1145 MiB or ~1.12 GiB, quite a lot more than the reserved 8 MiB. Would be nice if the reserved size was a percentage instead, so that it allows for larger variance on larger disks. For my specific scenario, reserving 0.1% of the disk size would work, or maybe being smart and rounding the capacity to exactly 12 trillion bytes and reserving the rest.

> Cutting off 8MB from each disk will still leave those disks different in size.

I think the idea is not to cut exactly 8 MiB from each disk, but cut it from the first disk added and then match the size to the other disks such that the data partition has the same size.
