### ISSUE TITLE
zpool_add_005_pos writing to live disk

### ISSUE THREAD

**Issue by bunder2015** [zfsonlinux/zfs#6267]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | gentoo
Distribution Version    | n/a
Linux Kernel                 | 4.9.16
Architecture                 | amd64
ZFS Version                  | git head
SPL Version                  | git head

### Describe the problem you're observing
After running tests on VM a couple weeks ago, I found myself unable to boot due to a corrupted /boot partition.  An e2fsck was able to fix me up, but it appears that the `zpool_add_005_pos` test is writing to a live disk instead of using the loop devices.

### Describe how to reproduce the problem
Run the tests
Reboot
Grub won't run because /boot got screwed up eg: http://i.imgur.com/f3YEy0U.png
### Include any warning/errors/backtraces from the system logs
```
zpool_add_005_pos/stdout:SUCCESS: zpool add -f testpool /dev/sda2 exited 1
zpool_add_005_pos/stdout:SUCCESS: zpool add -f testpool /dev/sda3 /dev/sda2 /dev/sda1 exited 1
```

It might say exited 1, but corruption of my /boot partition still occurs.

**Comment by bunder2015** [comment]
Looks like I can avoid this by mounting /boot if I understand https://github.com/zfsonlinux/zfs/commit/8c54ddd33af92e5defc587a10914493ca85ad60c correctly.  I don't normally leave /boot mounted on my legacy ext systems, but I still don't like the idea of playing with live disks.

**Comment by behlendorf** [comment]
These tests are somewhat dangerous since they're are designed to operate on devices other than the provided loopback devices.  And is this case it looks like they did uncover a problem, this test should not have damaged the ext filesystem.  It would be very helpful to know the exact reason `zpool add -f testpool /dev/sda2` failed, was it for the expected reason?  Also do you have any logs for exactly what damage was done to the ext filesystem?

**Comment by bunder2015** [comment]
sda2 is the root filesystem, sda1 is /boot and sda3 is swap.  Sorry I should have mentioned that in my initial report.

It does appear that mounting boot prevents further corruption to the /boot partition though.

**Comment by behlendorf** [comment]
Got it.  While this test was taken directly from OpenZFS I'm not sure it's exactly what we want.  I see that it's using the `-f` option which means it will use the disk even if it has an ext filesystem on it as long as it's not actively in use.

**Comment by bunder2015** [comment]
https://gist.github.com/bunder2015/3fb2c05aab134c2cb22e1d8d77653aaa

full zpool_add_005_pos/merged log and the e2fsck of the damaged /boot ext3

**Comment by behlendorf** [comment]
Right, so a zfs label was written to the ext3 fs since it was forced with `-f` by the test case.  That stomped on the superblock and needed to be repaired with a backup superblock.  On Illumos this kind of thing is supposed to be prevented by some code which disables `-f` for any device which appears in your `/etc/vfstab` file.

With systemd in the mix on Linux for mounting filesystem this doesn't seem like a restriction we want to enforce.  When the user provides the `-f` option we need to honor it unless it's clearly actively in-use (i.e. mounted).

I think it'd be reasonable to modify the test case to drop the `-f` option.  Or simply disable the specific test entirely on Linux as was done for the dump devices.

```diff
diff --git a/tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_005_pos.ksh b/tests/zfs-tests
index a7c7bc0..0af8c3e 100755
--- a/tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_005_pos.ksh
+++ b/tests/zfs-tests/tests/functional/cli_root/zpool_add/zpool_add_005_pos.ksh
@@ -80,7 +80,11 @@ log_must poolexists "$TESTPOOL1"
 unset NOINUSE_CHECK
 log_mustnot zpool add -f "$TESTPOOL" ${disk}${SLICE_PREFIX}${SLICE1}
 log_mustnot zpool add -f "$TESTPOOL" $mnttab_dev
-log_mustnot zpool add -f "$TESTPOOL" $vfstab_dev
+if is_linux; then
+       log_mustnot zpool add "$TESTPOOL" $vfstab_dev
+else
+       log_mustnot zpool add -f "$TESTPOOL" $vfstab_dev
+fi
 
 if ! is_linux; then
        log_must echo "y" | newfs ${DEV_DSKDIR}/$dump_dev > /dev/null 2>&1
```

**Comment by bunder2015** [comment]
That tests good here, thanks for looking into this.

**Comment by bunder2015** [comment]
We should probably add that to mnttab as well, as it also evaluates to sda2

**Comment by behlendorf** [comment]
The mnttab case should be safe since those are actively mounted filesystems and we expect that to fail even with `-f`.  It would be great if you could open a PR which disabled the vfstab case.
