### ISSUE TITLE
Shared spares do not honor multihost parameter

### ISSUE THREAD

**Issue by omgold** [zfsonlinux/zfs#6473]
### System information
ZFS Version                  | 0.7.0
SPL Version                  | 0.7.0

### Describe the problem you're observing

When using hotspares which are shared between pool, and both pools have set multihost=on, it is still possible to activate the hotspare on both pools at the same time.

### Describe how to reproduce the problem

- use a system with disks shared between two servers.
- create 2 zpools
- set multihost=on on both zpools
- add a hotspare to both pools (the same disk for both pools)
- import pool 1 on server A and pool 2 on server B
- on server A, replace a disk in pool 1 with the hotspare with 'zpool replace'
- on server B, replace a disk in pool 2 with the hotspare with 'zpool replace -f'

Remark: for this test, it only works when giving the '-f' option on 'zpool replace', when trying to use the active hotspare again, but I assume there is a race condition, if one would do the 'zpool replace' on both hosts at the same time.

**Comment by thewacokid** [comment]
This seems like expected behavior; "-f" forces the safety checks to be ignored.

If you can cause a simultaneous replacement that ends up with the disk imported into both pools that would indeed be a bug, but this very much feels like expected behavior unless I've completely misread the problem.

**Comment by ofaaland** [comment]
@omgold, you are correct that multihost does not provide protection in this scenario.  It provides protection only during attempted import.  Import was chosen because it is such a frequent operation, and because we know of actual cases where users destroyed their pools in failover scenarios, where their fencing mechanism failed.

There are several other operations that risk the same device being used by two different servers at the same time, including at least the following:
* a spare used in the manner you described
* zpool create with the same devices[1]
* zpool add with the same devices[1]
* zpool labelcear -f on a device that is actually in use
[1] If these are performed at the same time, ZFS may not even require the '-f' flag

ZFS could attempt to detect these scenarios, but we chose to leave those for future work in order to get at least some protection in place for the 0.7.0 release.

It looks like the man pages do not explain these cases are not covered by multihost.  I'm not sure where such issues are discussed in the documentation; they are not new to 0.7.0.
