### ISSUE TITLE
Coverity prematurely exits loop

### ISSUE THREAD

**Issue by tcharding** [zfsonlinux/zfs#6744]
### Describe the problem you're observing

This is not really ZFS' fault but I do not know where else to discuss it. Web searches for 'report coverity bugs' are _unsurprisingly_ not helpful.

Coverity reports (CID 147534) function returns a negative number. This seems like a bug in coverity

a) There are four other call sites the same that do not trigger an issue.
b) It sure looks like the code is right and coverity is wrong.

The loop looks like this

```
for (i = 0; i < USFIELD_LAST; i++) {
	if (strcmp(field, us_field_names[i]) == 0)
		return (i);
}
```
The function call in question passes in "type" as the `field` argument. Strangely, "type" should match on the first iteration through the loop but it does not according to coverity. Also coverity exits the loop early (after 3 iterations, even though it correctly has `USFIELD_LAST` as 6).

So the questions are 
a) Should I be reporting this somewhere? 
b) Do ZFS project members have coverity features that I don't have access to that can mark this as a bug    (or at least false positive).
c) Does this mean a loss of faith in coverity?

Thanks for your time

**Comment by behlendorf** [comment]
> There are four other call sites the same that do not trigger an issue.

It looks like the other call sites have code which correctly handles the case where `us_field_index` returns `-1`.  See a few lines down where there is a `nameidx >= 0` check before it is used.  We're missing a similar check for `typeidx >= 0` here and should add one.

You're right that this should never happen since it will always match.  But because the arrays defined above aren't defined as constants and therefore could be modified at run time Coverify considers the `return (-1);` to be a entirely possible patch for its static analysis.

> Do ZFS project members have coverity features that I don't have access to that can mark this as a bug (or at least false positive).

Yes.  There is the ability to classify bugs as false positives.

> Does this mean a loss of faith in coverity?

It's just a tool which is by no means infallible.  Coverity can definitely be wrong, so it's good to be skeptical.  It can also be a little confusing trying to interpret exactly what it's reporting.  But in this case it looks right.

**Comment by tcharding** [comment]
> It looks like the other call sites have code which correctly handles the case where us_field_index returns -1. See a few lines down where there is a nameidx >= 0 check before it is used. We're missing a similar check for typeidx >= 0 here and should add one.

Would an ASSERT be better here since we can only get a -1 return if something odd has gone wrong?

> You're right that this should never happen since it will always match. But because the arrays defined above aren't defined as constants and therefore could be modified at run time Coverify considers the return (-1); to be a entirely possible patch for its static analysis.

Awesome, thanks for clarifying.

> Yes. There is the ability to classify bugs as false positives.

I am [slowly] working my way through the coverity issues. Obviously I'm too new to be totally trusted but do you want my list of false positive issues? I am constructing two lists, one I'm 100% sure of and the other less than 100%.

**Comment by behlendorf** [comment]
> Would an ASSERT be better here since we can only get a -1 return if something odd has gone wrong?

We could, but I don't think it's critical in this case.  Let's just add the error handling.

> I am [slowly] working my way through the coverity issues. 

That's great!  It's definitely appreciated, we've been slowly chipping away at them.  For the moment what you're doing sounds fine, then we can go over your lists and get another assessment.

**Comment by tcharding** [comment]
PR to come. thanks.
