### ISSUE TITLE
zfs on boot partition how-to doesn't use zfs

### ISSUE THREAD

**Issue by UnConundrum** [zfsonlinux/zfs#6798]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.10
Linux Kernel                 | 4.8.0-59-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.8-0ubuntu4.2
SPL Version                  | 0.6.5.8-2

### Describe the problem you're observing

I'm following https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.10-Root-on-ZFS for an unencrypted UDFI boot.  After a successful install, I added a drive to mirror the install.  
At section 2.2 we create the boot partition.  
At section 4.8b we install set the partition to fat32 and install grub.  
At section 6.8 we copy the boot partition from the first drive to the 2nd and tell efi about it.  

I can't see where a pool is created for the boot partition, or where the boot partition of disk1 is mirrored to the boot partition of disk2.  df lists the partition, but not as part of a pool:
`/dev/sdc3            511M  256K  511M   1% /boot/efi`
Nothing in zfs list indicates a boot pool or any dataset including /boot/efi

 I realize that establishing the duplicate boot partition on drive2 at seciton 6.8 makes it bootable, but I can't see where any changes to grub will be mirrored to it.  Am I missing something?

**Comment by MyPod** [comment]
In the UEFI setup you create a partition for the UEFI bootloader. Changes to the GRUB configuration are instead kept in /boot, /boot/efi containing only the non-changing first stage part of GRUB.

The sense of mirroring the partition scheme from the first disk to the second imho is only to give ZFS a partition of the same size as the original one, however, as UEFI doesn't support mirrors, you won't be able to use the fat32 partition - on which you don't re-install the first stage GRUB loader - in the second drive for booting. You technically could set that up to create a fallback in case your first drive dies, and you could register the first stage bootloader with UEFI through efibootmgr, but I don't see much of a gain, considering you could, should the first drive die/be removed, just boot into recovery, mount your setup, re-execute grub-install and reboot.

**Comment by rlaager** [comment]
I didn't see this until now. This is out of date. I took a quick look at the current (18.04) HOWTO and everything seems to be correct.

There are two types of "changes to grub". The GRUB configuration is on the boot pool, so it is mirrored via ZFS. The ESP only has the early stage GRUB code. If that changes, you are correct that nothing updates the mirrored copies. In practice, that's fine, especially within a given distro version, because GRUB is not changing much. This is not a ZFS issue, though. The GRUB packaging supports installing to multiple disks in a legacy world, and presumably should update them all on upgrade, but does not support a similar concept for UEFI.
