### ISSUE TITLE
Doc: possibility to prepare root fs, and then to continue with default installer method?

### ISSUE THREAD

**Issue by testbird** [zfsonlinux/zfs#6804]
It's rather a question.

I had somehow hoped the "root on ZFS" howtos like
https://github.com/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS
would simply show how to open a terminal after booting some regular distribution install media, then download packages and setup the target filesystem and then just explain how to go on using the normal installer to put the system onto the ZFS.

Shouldn't that be a prefererable ZFS introduction method? The wiki only explaining how to add ZFS to the regular, well documented install procedures?

**Comment by testbird** [comment]
Installers usually offer to drop to a shell. Otherwise `Ctrl-Alt-F2` /  `Ctrl-Alt-F7` for example should allow switching to a virtual text console and back.

**Comment by testbird** [comment]
Hello @gmelikov, for Debian I am having a hard time figuring out at which step one may start or switch back to the debian-installer (Ctrl-Alt-Fx), and let it do the install on zfs exept the bootloader and final reboot, which would be a final manual step. Would you have some recommendations?

Here are raid install examples following this approach, where the installer does not support it:
https://superuser.com/a/458831
https://www.sidorenko.io/post/2013/12/how-to-install-linux-mint-on-encrypted-raid-1-with-lvm/

**Comment by gmelikov** [comment]
@testbird i didn't look at Debian graphical (or dialog) installer.

If i understand the case correctly, the main problem is that we need zfs packages inside installed system, so it's not only manipulations before installer. And the install process through debootstrap is not much longer.

Feel free to dig it, if you want.

**Comment by skalteis** [comment]
@testbird I think using the standard Debian installer is not possible without custom installation media which already include prebuilt kernel modules and zfs utilities (or loading as udeb). There is no build environment while the installer is running so installing the dkms-packages in order to set up the root fs definitely won't work. 
If I remember correctly, the installer runs up to after the partioning and file system creation step, then mounts the new root at /target and the base system is installed there. You would have to have your pool imported and mounted at /target before installing the base system and then afterwards in theory could chroot to /target and install kernel+headers, bootloader and the standard ZFS packages manually (dpkg/apt is already there at this point).

The debootstrap method is definitively easier at the moment.

**Comment by gmelikov** [comment]
I prefer to close this issue, there is no easier way to install via GUI for now, compared to debootstrap.
