### ISSUE TITLE
arc_summary | head often prints out a Python error on 0.7.X

### ISSUE THREAD

**Issue by rincebrain** [zfsonlinux/zfs#6965]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | 9.3
Linux Kernel                 | 4.9.0-4-amd64
Architecture                 | x86_64
ZFS Version                  | 0.7.3-3
SPL Version                  | 0.7.3-1

### Describe the problem you're observing
I often use arc_summary | head when I just want to see the first few lines, and starting when I installed 0.7.3 (I was on 0.6.5.11 prior), arc_summary sometimes prints to stderr at the end like so:
```
# arc_summary |head -n 20

------------------------------------------------------------------------
ZFS Subsystem Report                            Fri Dec 15 00:39:00 2017
ARC Summary: (HEALTHY)
        Memory Throttle Count:                  0

ARC Misc:
        Deleted:                                76.91m
        Mutex Misses:                           8.67m
        Evict Skips:                            8.67m

ARC Size:                               24.17%  5.80    GiB
        Target Size: (Adaptive)         24.30%  5.83    GiB
        Min Size (Hard Limit):          4.06%   998.37  MiB
        Max Size (High Water):          24:1    24.00   GiB

ARC Size Breakdown:
        Recently Used Cache Size:       5.60%   334.10  MiB
        Frequently Used Cache Size:     94.40%  5.50    GiB

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
It seems to occur more frequently with smaller -n to head, but it's not guaranteed at any -n (head -n 1 produces it 10 out of 11 times when I tried it).

This never occurred in 0.6.5.X, to my recollection, so I would guess this came with the arc_summary move to Python3.

### Describe how to reproduce the problem
Pipe arc_summary into head, or presumably anything else that might truncate its output before it's finished writing (tail or less do not ever produce this, for example)

**Comment by dswartz** [comment]
I've seen this as well.

On December 15, 2017, at 12:44 AM, Rich Ercolani <notifications@github.com> wrote:

System information

TypeVersion/NameDistribution NameDebianDistribution Version9.3Linux Kernel4.9.0-4-amd64Architecturex86_64ZFS Version0.7.3-3SPL Version0.7.3-1 

Describe the problem you're observing

I often use arc_summary | head when I just want to see the first few lines, and starting when I installed 0.7.3 (I was on 0.6.5.11 prior), arc_summary sometimes prints to stderr at the end like so:

# arc_summary |head -n 20 ------------------------------------------------------------------------ ZFS Subsystem Report Fri Dec 15 00:39:00 2017 ARC Summary: (HEALTHY) Memory Throttle Count: 0 ARC Misc: Deleted: 76.91m Mutex Misses: 8.67m Evict Skips: 8.67m ARC Size: 24.17% 5.80 GiB Target Size: (Adaptive) 24.30% 5.83 GiB Min Size (Hard Limit): 4.06% 998.37 MiB Max Size (High Water): 24:1 24.00 GiB ARC Size Breakdown: Recently Used Cache Size: 5.60% 334.10 MiB Frequently Used Cache Size: 94.40% 5.50 GiB Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'> BrokenPipeError: [Errno 32] Broken pipe 

It seems to occur more frequently with smaller -n to head, but it's not guaranteed at any -n (head -n 1 produces it 10 out of 11 times when I tried it).

This never occurred in 0.6.5.X, to my recollection, so I would guess this came with the arc_summary move to Python3.

Describe how to reproduce the problem

Pipe arc_summary into head, or presumably anything else that might truncate its output before it's finished writing (tail or less do not ever produce this, for example)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zfsonlinux/zfs","title":"zfsonlinux/zfs","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/zfsonlinux/zfs">https://github.com/zfsonlinux/zfs</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"arc_summary | head often prints out a Python error on 0.7.X (#6965)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/zfsonlinux/zfs/issues/6965">https://github.com/zfsonlinux/zfs/issues/6965</a>"}}}
