### ISSUE TITLE
ZFS build fails with kernel 4.15.9

### ISSUE THREAD

**Issue by niusmallnan** [zfsonlinux/zfs#7349]
ZFS version: v0.7.7

Build logs:
```
zfs_1 | checking linux distribution... debian
zfs_1 | checking default package type... deb
zfs_1 | checking whether rpm is available... no
zfs_1 | checking whether rpmbuild is available... no
zfs_1 | checking whether spec files are available... yes (rpm/generic/*.spec.in)
zfs_1 | checking whether dpkg is available... yes (1.18.24)
zfs_1 | checking whether dpkg-buildpackage is available... no
zfs_1 | checking whether alien is available... no
zfs_1 | checking spl config... all
zfs_1 | checking kernel source directory... /lib/modules/4.15.9-rancher/build
zfs_1 | checking kernel build directory... /lib/modules/4.15.9-rancher/build
zfs_1 | checking kernel source version... 4.15.9-rancher
zfs_1 | checking kernel file name for module symbols... Module.symvers
zfs_1 | checking whether debugging is enabled... no
zfs_1 | checking whether basic kmem accounting is enabled... no
zfs_1 | checking whether detailed kmem tracking is enabled... no
zfs_1 | checking whether modules can be built... no
zfs_1 | configure: error: *** Unable to build an empty module.
```

**Comment by bunder2015** [comment]
Please do not remove the issue template when filing issues.

Unfortunately, this is not a zfs problem, but rather a distribution problem.  This error occurs because you are missing things like kernel headers, or possibly because you haven't built a kernel with this version of the kernel sources.

**Comment by kpande** [comment]
use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests. also, deleting the template is rather insulting to those who put the hard work in to manage the project. please be more considerate.

**Comment by behlendorf** [comment]
For future reference:

This is caused by upstream kernel bug https://bugzilla.redhat.com/show_bug.cgi?id=1550152#c6 which effectively breaks all external kernel module builds starting with the 4.15.9-1 kernel.

Users will need to rollback to an earlier kernel from your distribution until the distribution resolves the issue.  The fedora developers are [rolling back this change](https://src.fedoraproject.org/rpms/kernel/c/0ff2afdbe0501525ee2d5b53fdc20a320b29bc8c?branch=master) but it'll be up to each distribution as how they want to handle it.
