### ISSUE TITLE
Exec format error on arm, unsupported interworking call (Thumb -> ARM)

### ISSUE THREAD

**Issue by mrvn** [zfsonlinux/zfs#7408]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Debian
Distribution Version    |  9
Linux Kernel                 |  4.14.18-mvebu
Architecture                 | arm, armv7l, Helios4
ZFS Version                  |  0.7.0-411_g6c9af9e8f
SPL Version                  |  0.7.0-32_g581bc01

### Describe the problem you're observing
Loading zfs module fail:

modprobe: ERROR: could not insert 'zfs': Exec format error

### Describe how to reproduce the problem

Checkout git and build deb packages for the running kernel as described on the wiki. Running modprobe zfs then gives the error.

### Include any warning/errors/backtraces from the system logs

dmesg shows:

```
[11390.901971] zlua: section 3 reloc 43 sym 'longjmp': unsupported interworking call (Thumb -> ARM)
```

**Comment by bunder2015** [comment]
exec format error means you used the wrong arch, ie: 32bit on a 64bit only kernel.

**Comment by mrvn** [comment]
No it doesn't. As the dmesg output shows the problem is the "unsupported interworking call". Which as far as I can tell an unpatched kernel does simply not allow. Thumb mode is a personality, not a bit-ness issue.

I didn't use any arch but simply run ./configure as recommended in the wiki. This should do the right thing[tm]. I don't see any configure option to enable/disable thumb support so I'm stumped.

**Comment by kpande** [comment]
please use [the zfs-discuss mailing list](http://list.zfsonlinux.org) for support requests, this is a configuration issue and not a problem in ZFS.

**Comment by jsrlabs** [comment]
I had the same problem on my Helios4 when I tried building as described on the wiki. [This message](https://zfsonlinux.topicbox.com/groups/zfs-discuss/Te72d6d04ef0261a6-M7fbff7132cbd06e7b6a96439/zfs-discuss-exec-format-error-on-arm-unsupported-interworking-call-thumb-arm) on zfs-discuss describes the cause of this issue.

Based on that, I narrowed it down to assembly code for setjmp and longjmp in the lua interpreter in zfs-0.8.2/module/lua/setjmp/setjmp_arm.S. This assembly code uses 32-bit ARM instructions, but the Armbian kernel for the Helios4 is all Thumb2, hence the "unsupported interworking call".

I have a crude hack that incompletely fixes the problem: I modified the lua setjmp and longjmp to use Thumb2. It compiles, and I use this ZFS setup every day, but I have never tested the lua feature. Also, the fix is incomplete in that it doesn't detect the type of kernel (32-bit ARM vs Thumb2) and just assumes the kernel is Thumb2.

Maybe someone will find this useful, so I've attached a patch.

[lua_setjmp_patch.txt](https://github.com/zfsonlinux/zfs/files/4132107/lua_setjmp_patch.txt)
