### ISSUE TITLE
inverted parent/child vs origin/clone relationship is possible

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#7414]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | 17.0
Linux Kernel                 | 4.16.0-gentoo
Architecture                 | ~amd64
ZFS Version                  | master
SPL Version                  | master

### Describe the problem you're observing

I'm able to

```
zfs snap pool@snap
zfs clone pool@snap pool/vol
zfs promote pool/vol
```

now 'pool' is a child of 'vol'

**Comment by ahrens** [comment]
Can you describe the problem you're seeing?

I don't think that `pool` is a child of `pool/vol`.  However, `pool` is a clone if `pool/vol`.

**Comment by kpande** [comment]
sorry, i meant clone, instead of child.

this is not necessarily a major issue, it is just confusing. you can promote the clone of the root dataset, but you cannot 'detach' them so some users were wondering "how do I undo the promote" (which the obvious answer to us is, simply promote the root dataset again)

and I wasn't sure if this was intentional or something we want to trap and warn about.

**Comment by ahrens** [comment]
It sounds like the confusion would be with any parent/child vs origin/clone relationship difference, i.e. this is not specific to the root dataset.  The confusion would be there if e.g. pool/parent was a clone of pool/parent/child.  It might make sense to have an informational message when doing a promote or rename that results in this situation.

**Comment by loli10K** [comment]
Just for reference, this may be the cause of `rsend/rsend_008_pos` known failure: #6066

**Comment by tcaputi** [comment]
I'm looking into cleaning up some of the disabled tests that we've accumulated over the years and was taking some time to look at this (and specifically #6066). The analysis on that ticket is correct and it does pose some interesting problems. It's easy enough to get the send side not to crash anymore: all we need to do is recognize that the origin - clone relationship matters much more than the parent - child one, since the parent-child one can easily be fixed after the fact with calls to the `zfs_rename` ioctl.

The receive side is a bit trickier though. The receive side has `recv_incremental_replication()` implemented, which should be capable of figuring out these renames. However, there are 2 problems that can occur as a result of the way the receive code uses `guid_to_name()` to search for datasets to receive into:

1. If you attempt to do a base snapshot send and receive to and from the same pool, this function will attempt to find the parent dataset for the child dataset. Instead of finding its real parent (which hasn't been received yet) it will find the original parent that the send file was created under. This can cause a number of errors when zfs tries to understand and correct the hierarchy.
2. If you attempt to do a base snapshot send and receive to a different pool, this function will simply find no parent to receive the child dataset under, which will cause an error. Ideally, the code should be able to receive the child into a dataset with a temporary name and then correct the hierarchy later after all other datasets have been received.

All of this is quite confusing for the user (and for the code). My gut says that I don't like how `guid_to_name()` currently works, trying to find datasets that work by brute force searching. At the same time, I don't see how else we can do recursive receives when renames are involved without a function like that.

@ahrens any thoughts on this?

**Comment by ahrens** [comment]
Without looking at the code recently (though I do recall implementing that mess), it seems like solving #2 would be relatively straightforward. We need to detect that the parent doesn’t exist, and put it under the root of the receive (ie under the cli arg to SF’s receive). And then later rename it where it belongs (which might “just work”). 

We want to do the same for #1, but the key is that we should only consider parents that are under the receive root. If it’s elsewhere, we want to treat the parent as non existent, same as #2. I don’t think there’s any case where we would want a received fs to “escape” from the target fs hierarchy.

**Comment by tcaputi** [comment]
>  I don’t think there’s any case where we would want a received fs to “escape” from the target fs hierarchy.

I was under the belief that this code exists for just this purpose. The use case was if someone sent a recursive base snapshot of all their datasets, then moved them around on the receive side and tried to do an incremental receive on top of that.

**Comment by ahrens** [comment]
IIRC the receive will try to rename everything back to where it is on the source side, and normally succeed (except maybe in this “inverted” case). I’m not at a computer now to check, so I could be wrong?
