### ISSUE TITLE
Wiki: tell CentOS users to install EPEL first

### ISSUE THREAD

**Issue by gjedeer** [zfsonlinux/zfs#7498]
Since the Wiki is not editable by strangers:

This happens when you follow install instructions on freshly installed CentOS 7: https://github.com/zfsonlinux/zfs/issues/4733

The [CentOS install page](https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-EL7-(CentOS-RHEL)-to-a-Native-ZFS-Root-Filesystem) should mention the necessary first step to install ZFS: `yum install epel-release`

**Comment by hoonetorg** [comment]
@gjedeer : correct, if you want to build kmods with DKMS.
On prod systems you (at least I) don't want to enable EPEL always.
Also I had sometimes troubles when upgrading zfs with DKMS.

That's why I prefer using kABI-tracking kmod repo/packages, which works great (s.a. https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS)

**Comment by gjedeer** [comment]
I don't really have an opinion on that, I run 2 servers with elrepo-ml kernel (latest mainline) so DKMS is the only option for me. It worked so far.

All I'm asking is for someone with WIki rights to change https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS#dkms so it mentions that epel-release is needed.

**Comment by behlendorf** [comment]
Updated.
