### ISSUE TITLE
Add guide for root-on-zfs for DigitalOcean instance (Ubuntu 18.04) [wiki patch]

### ISSUE THREAD

**Issue by AndrewJDR** [zfsonlinux/zfs#7550]
In case this is useful for others, I'm providing it.

I saved it out with `git format-patch` against the wiki git repo:
https://gist.githubusercontent.com/AndrewJDR/f6d8fa6823e13b232f699c810e0cbd88/raw/278a4ee97807b25dc4ff621c93622adfe6aff806/0001-Add-DigitalOcean-root-on-zfs-guide-Ubuntu-18.04.patch

**Comment by AndrewJDR** [comment]
@behlendorf Seeing as it's coming up on 18 months, could we consider merging this?

**Comment by behlendorf** [comment]
Thanks for reminding us about this and putting together the guide.  My concern would be that the ZFS on Linux wiki might not be the best home for this content.  By necessity the guide is specific to Digital Ocean droplets, it may make more sense to host it there as a community tutorial.  

https://www.digitalocean.com/community/tutorials

Let's run this by @rlaager who maintains the current Ubuntu Root on ZFS guide.

**Comment by rlaager** [comment]
Sorry for the delay. I didn't see this.

My biggest concern here is about long-term maintenance. Maintaining these HOWTOs is a fair amount of work. If it ends up falling on me, I'm A) not interested in DigitalOcean, and B) don't have any way to test this. Are you planning on maintaining this long-term?

If this is to be merged upstream, I'd like to see the following changed/answered, more-or-less:

1. Can the need for the recovery ISO be eliminated, especially since it involves opening a ticket with DigitalOcean? For example, is there a way to add the e2fsck & resize2fs as some sort of early-boot script, possibly an initramfs hook? Then the rest of the steps could be run from the regular ext4 environment, right?
2. Is the partition resizing deterministic? (I would expect it is.) If so, that whole bit about calculating the offset should be avoidable.
3. How much does this need to vary from the existing HOWTO? Could the middle of this simply refer people to certain steps of the existing HOWTO? Alternatively, could this be like Debian vs. Ubuntu differences where the HOWTOs are nearly identical copies of each other, with only the required changes being different, and then they can be maintained in lock step otherwise?
4. Why is ordering important in /etc/fstab?
5. Is `GRUB_HIDDEN_TIMEOUT` actually a float? I thought it was an int, so it should be `1` rather than `1.0`.

**Comment by AndrewJDR** [comment]
Thanks for taking a look. Investigating really solid answers a couple of your questions would be more work/time than I can really commit to this. I'll try my best to address the points off the top of my head, though:

* I'm not aware of any kind of early boot script on the DO side.

* In terms of determinism, to feel good enough to remove that calculation from the document and use fixed values, I'd have to verify that in such a way that I am highly confident about it. Even then, I'm not sure it would be future proof -- the disks on the low-end DO instance type may change to have a different sector size or other properties in the future, causing the document to become incorrect later.

* At least at the time of writing, I found this deviated quite a bit from the standard HOWTO -- enough that if referring back to the main HOWTO, there would be so many references that it would be difficult to follow. There's again a possible issue of future-proofness -- the references in this document could fall out of date if the master HOWTO changes and I doubt anyone would notice enough to correct those references.

Overall, this may not be the most optimal way of doing it, but it does get the job done and there's no other documentation of how to do this on the net that I'm aware of, so perhaps it's better than nothing? Happy to fix the GRUB_TIMEOUT issue if the document is otherwise more-or-less acceptable. Otherwise I may just submit it to the digitalocean docs at some point so it at least has a home on the net somewhere.

Cheers.

**Comment by rlaager** [comment]
> Investigating really solid answers a couple of your questions would be more work/time than I can really commit to this.
...
> I may just submit it to the digitalocean docs at some point so it at least has a home on the net somewhere.

That or a blog post is probably the best.
