### ISSUE TITLE
centos $releasever compatible links

### ISSUE THREAD

**Issue by brianjmurrell** [zfsonlinux/zfs#7583]
Would it be possible to create CentOS `$releasever` compatible links at http://download.zfsonlinux.org/epel/?  Right now for example http://download.zfsonlinux.org/epel/7.5.1804/x86_64/repodata/repomd.xml returns

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>epel/7.5.1804/x86_64/repodata/repomd.xml</Key>
<RequestId>2929A67AA143A094</RequestId>
<HostId>
Pnis5S4vZ0br4pIpigrYlyrCZ9Wi4a7ASU2hMu3HIJDiFu48vtnq92whmFPxKs1F4+Oid4Q/zAo=
</HostId>
</Error>
```

**Comment by behlendorf** [comment]
@brianjmurrell unfortunately since the packages are currently hosted in S3 we can't easily create symlinks.  Going forward it would probably be a good idea to use the full release version.  Although, on CentOS I'm pretty sure I looked in to this before and `$releasever` expands to only the major version number.

**Comment by brianjmurrell** [comment]
@behlendorf Yes, as you were.  You are already all good in this regard.  I was confusing CentOS' extended versioning such as 7.5.1804, thinking that was their `$releasever` also but it's not.  It's RHEL's _7Server_ `$releasever` that often needs compatibility symlinking.
