### ISSUE TITLE
Add Debian Folder to Support Building Packages for Debian and Debian Based Distros

### ISSUE THREAD

**Issue by Ryushin** [zfsonlinux/zfs#7657]
Add the debian folder along with some bug patches be added to the ZoL base to fully support building packages on Debian and Debian based distros such as Devuan.

I would think the easiest thing would just be to copy the debian folder from the debian package source and add the patches for sysvinit and remove the lsb_release dependency:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826994
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900089

**Comment by Fabian-Gruenbichler** [comment]
On Tue, Jun 26, 2018 at 04:57:37AM -0700, Ryushin wrote:
> Add the debian folder along with some bug patches be added to the ZoL base to fully support building packages on Debian and Debian based distros such as Devuan.
> 
> I would think the easiest thing would just be to copy the debian folder from the debian package source and add the patches for sysvinit and remove the lsb_release dependency:
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826994
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900089
> 

Antonio Russo (@aerusso) is already in the process of preparing
something like this, just be a patient for a bit longer.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891890

**Comment by beren12** [comment]
sure. but it seems more and more the debian maintainers are actively ignoring sysvinit support even though it's officially supported by debian, *and* there's been a patch available for them to use just for a year and a half. 

see bottom of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826994

**Comment by beren12** [comment]
I hope russo is able to knock something together but i feel like we should not have to fight with the debian packaging team for simple things like updates, or init support. Maybe we can get another person on the packaging team to help keep it up to date?

**Comment by aerusso** [comment]
FYI: I'm not associated with Debian any more than I've been volunteering patches there. It's definitely **not** within my ability to push any uploads to Debian.

@beren12 I don't really think that a zfsonlinux bug report is the right place to suggest changes to downstream packaging---that would probably be that downstream's bugtracker.

As for

> Add the debian folder along with some bug patches be added to the ZoL base to fully support building packages on Debian and Debian based distros such as Devuan.
>I would think the easiest thing would just be to copy the debian folder from the debian package source and add the patches for sysvinit and remove the lsb_release dependency:
>https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826994
>https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900089

1. First of all, "and remove the lsb_release dependency" has already been addressed #7540. I don't claim to understand the reasoning behind that name check, but #7554 should have fixed this issue (I still haven't gotten anyone from Devuan to actually build and test that package). It's also the least invasive change.

2. It's not "just be to copy the debian folder from the debian package source and add the patches for sysvinit and remove the lsb_release dependency"---too much has changed with the SPL merge, it won't just compile. [I've fixed that, by the way](https://salsa.debian.org/aerusso-guest/zfs/tree/debian/git). [My github fork](https://github.com/aerusso/zfs/tree/debian/packaged) is a little behind---I'm kind of busy right now. I have an [ITP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891890) and [wishlist bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902165) filed about this too. There's also a legal issue, if you dig through those threads. I'd love to see more interest in this, especially in the form of people compiling and testing it out on their machines.

3. It's also not just the case of "copy the debian folder" because it needs to integrate into the existing testing framework. I'm not 100% sure how that should work. Also, Debian goes off and  changes the locations of lots of things---this is really the package maintainer's job, not upstream's. Where should the line be drawn? I don't know. Should the configure script be used to set the options for the Debian packages created? (That would closest approximate the current situation) I *personally* run Debian, so I'd be fine with a directory that just works with Debian, but I don't want to push sub-par packaging for other deb-based distros.

4. For the above reason, I'm actually less disturbed by the existing rpm->deb packaging (assuming it works).  There is #7412 which I think represents an issue in the conversion process. For whatever reason, when I build the deb, even with `--enable-sysvinit` I'm not finding the sysv scripts in there. That might be an issue with my environment (which is entirely systemd) leaking into the packaging process, but I still consider that a bug. But that discussion should be had there.

Honestly, as far as I can tell, we (zfsonlinux) **do** already support Debian-based distributions. The end-user experience that will be accomplished by migrating away from the rpm conversion process isn't going to be all that different.

**Comment by aerusso** [comment]
> Opening this request was just trying to get the ball rolling. It looks like you have already been pushing that ball uphill already. Another thought when opening this request was to eventually have Devuan use the ZoL source instead of using the Debian source.

Distribution-specific customization should really be done by downstream package maintainers. I'm not sure what our policy is for building packages for other distributions (some distributions do have packages built for them). However, supporting multiple distributions means that there isn't going to be a `debian` directory that is one-size-fits-all. It's quite possible that the build system will construct a `debian` directory after a call to `configure`. This is inappropriate for any downstream Debian or derivative.

> Yea, I see your points. It seems more and more that a ZoL release should not just "include" the Debian folder. Seems like a better thing to do is for ZoL to make their own apt source with their own Debian based packages. Then the Debian official packages could be just not be used.

Have you tried installing the Debian packages that are produced (I think the appropriate call is `./configure --prefix= --with-config=user ;  make pkg-utils deb-dkms`)? Notwithstanding the bug I already mentioned, this *should* be functional now.

Again, given how tightly a file system should integrate into a distribution, it's quite likely the packaging produced here will not be appropriate for any high-quality downstream Debian derivative.

**Comment by behlendorf** [comment]
> I'm not sure what our policy is for building packages for other distributions.

For the reasons you've mentioned we strongly prefer for the downstream distribution to handle the packaging.  We can help can provide generic functionality in `configure` for them to leverage, but they know best what conventions their distribution follows.

**Comment by Conan-Kudo** [comment]
The core issue with it ignoring `--enable-sysvinit` is the same one that happens when `--enable-systemd` is ignored. Somewhere along the line, it checks for `/bin/systemctl` and overrides the configure setting from the packager/user.

This is particularly annoying since I don't normally want systemd in the buildroot for building packages that don't link to libsystemd (and I'm a Fedora user/developer).

**Comment by RJVB** [comment]
>     1. First of all, "and remove the lsb_release dependency" has already been addressed #7540.

FWIW, on my Ubuntu 14.04 system:

```
> lsb_release -is
Ubuntu
```

>For the reasons you've mentioned we strongly prefer for the downstream distribution to handle the packaging.

I hear you, but I also found out the hard way that the Ubuntu packaging scripts I use (from an older ZoL release) were just outdated enough to miss a crucial file (scripts/enum-extract.pl). Without having looked whether or not it's already the case I'd say that even if you leave distro packaging (and dkms.conf tweaking) to distro managers you could provide a dkms build target that creates a complete /usr/src/foo-x.y.z directory if you intend to support DKMS.

**Comment by Conan-Kudo** [comment]
The current packaging in ZoL will produce working dkms packages for Debian/Ubuntu now, anyway. I fixed these issues a while ago in 7670f721fc82e6cdcdd31f83760a79b6f2f2b998.

**Comment by RJVB** [comment]
I saw the files, but it's not clear how they get used, in particular when there is no debian directory to start with. Of course I didn't (yet) dive into the online documentation...
