### ISSUE TITLE
[Gentoo ebuilds] sys-fs/zfs, sys-fs/zfs-kmod, sys-kernel/spl don't work anymore after merge of spl into zfs

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#7717]
This is basically a request to have/get updated ebuilds to be able to use

latest zfs-master & spl-master on Gentoo again

CC: @ryao

**Comment by bunder2015** [comment]
They work just fine for me if you uninstall spl first

**Comment by kernelOfTruth** [comment]
@bunder2015 you're right, it worked - it seemed that there wasn't any announcement or clarification for that on how to deal with this change (looked at several places and didn't find anything)

Thanks

**Comment by bunder2015** [comment]
This should only affect the 9999 ebuild, since the spl merge isn't taking place until 0.8 at the earliest.  I thought a spl blocker was added to the ebuild but I must be mistaken. @prometheanfire @gyakovlev

**Comment by prometheanfire** [comment]
I use a builtin kernel and manually run some stuff based off the ebuild.  It works. I think the only thing that'd need to get done is to drop the dep on spl.

**Comment by gyakovlev** [comment]
there is a soft blocker for `!sys-kernel/spl` in zfs-kmod-9999.ebuild since spl merge happened.
probably portage decides to remove spl after installing teh new zfs-kmod and things go downhill.
maybe make it a hard blocker?
on a side note: max kernel version needs bumping. It definitely supports kernel newer than 4.16

I'll probably to brush up live ebuilds sometime soon.

**Comment by bunder2015** [comment]
Oh it's in kmod.  That would explain why I didn't see it earlier.  Thanks
