### ISSUE TITLE
master doesn't print "(repairing)" during scrubs

### ISSUE THREAD

**Issue by tonyhutter** [zfsonlinux/zfs#7779]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Centos
Distribution Version	| 7
Linux Kernel	| 3.10
Architecture	| x86_64
ZFS Version	| master
SPL Version	| master

### Describe the problem you're observing

`zpool status` should print `(repairing)` for any drives that show errors during a scrub:
```
  scan: scrub in progress since Wed Aug  8 21:19:52 2018
	664M scanned at 664M/s, 21.0M issued at 21.0M/s, 665M total
	5.93M repaired, 3.15% done, 0 days 00:00:30 to go
config:

	NAME            STATE     READ WRITE CKSUM
	mypool          ONLINE       0     0     0
	  mirror-0      ONLINE       0     0     0
	    /tmp/file1  ONLINE      13     0     0  (repairing)
	    /tmp/file2  ONLINE       0     0     0
	    /tmp/file3  ONLINE       0     0     0
```

The zfs-0.7-release branch will print it, but master will not.  The regression looks to be caused by d2734cce68 which is not in zfs-0.7-release.  Specifically, the early return line for non-root-vdevs prevents pool_scan_stat_t for the leaf vdev to be populated:
```
static void
root_vdev_actions_getprogress(vdev_t *vd, nvlist_t *nvl)
{
        spa_t *spa = vd->vdev_spa;

        if (vd != spa->spa_root_vdev)
        	return; 
```
If it's removed, then "(repairing)" correctly appears.
```
diff --git a/module/zfs/vdev_label.c b/module/zfs/vdev_label.c
index 29d7d65..cd4b033 100644
--- a/module/zfs/vdev_label.c
+++ b/module/zfs/vdev_label.c
@@ -357,9 +357,6 @@ root_vdev_actions_getprogress(vdev_t *vd, nvlist_t *nvl)
 {
        spa_t *spa = vd->vdev_spa;
 
-       if (vd != spa->spa_root_vdev)
-               return;
-
        /* provide either current or previous scan information */
        pool_scan_stat_t ps;
        if (spa_scan_get_stats(spa, &ps) == 0) {
```
### Describe how to reproduce the problem
```
#!/bin/bash
ZPOOL=./cmd/zpool/zpool
ZFS=./cmd/zfs/zfs
ZINJECT=./cmd/zinject/zinject
MOUNTDIR=/tmp/mount
MKFILE=./tests/zfs-tests/cmd/mkfile/mkfile
VDEV1=/tmp/file1
VDEV2=/tmp/file2
VDEV3=/tmp/file3
POOL=mypool
POOLTYPE=mirror
FILESIZE=700000000

truncate -s 1000M $VDEV1 $VDEV2 $VDEV3
mkdir -p $MOUNTDIR
$ZPOOL create -f -m $MOUNTDIR -o failmode=continue $POOL $POOLTYPE $VDEV1 $VDEV2 $VDEV3
$ZFS set compression=off $POOL
$MKFILE $FILESIZE $MOUNTDIR/file

$ZINJECT -d $VDEV1 -e io -T read -f 90 $POOL
$ZPOOL scrub $POOL

# We should see "(repairing)" in zpool status
$ZPOOL status
$ZINJECT -c all

$ZPOOL destroy $POOL
rm -f $VDEV1 $VDEV2 $VDEV3
```

**Comment by sdimitro** [comment]
Thank you for submitting this issue. So I think I know exactly what happened.

The reason why I factored out that code into `root_vdev_actions_getprogress()`
and added the check to only generate the nvlist for the root vdev was because
the data that we were copying into the new nvlist are spa-wide. So my
intention was to only have one nvlist with those spa-wide data in the root
vdev's nvlist instead of having the same copy of this nvlist for each vdev
in the config.

Now this causes a problem in `print_status_config()` of `zpool status`. The
function is called recursively over all the vdev's in the config and it
prints the "(repaining)" part of the status under the following condition:
```
static void
print_status_config(zpool_handle_t *zhp, status_cbdata_t *cb, const char *name,
    nvlist_t *nv, int depth, boolean_t isspare)
{
...
        (void) nvlist_lookup_uint64_array(nv, ZPOOL_CONFIG_SCAN_STATS,
            (uint64_t **)&ps, &c);

        if (ps != NULL && ps->pss_state == DSS_SCANNING &&
            vs->vs_scan_processed != 0 && children == 0) {
                (void) printf(gettext("  (%s)"),
                    (ps->pss_func == POOL_SCAN_RESILVER) ?
                    "resilvering" : "repairing");
        }
...
}
```

So the problem is that `ps` is NULL because that vdev doesn't have a copy of
the spa-wide data in its nvlist to tell whether we are in the middle of a
scrub or not.

I think it would be great if we could rely solely on something like
`vs_scan_processed` but the problem is that this field is not zeroed out once
we are done scanning the vdev. I'm not sure if this is on purpose or it was
just easier to not touch that field again.

I'm ok with taking out that root vdev check and inlining the helper function
to bring back multiple copies of that nvlist and restore the zpool status
output as long as there are no other problems. Another option would be to
restructure the userland code to share this nvlist while traversing the vdev
configuration.

It will be a while until I get to work on this, so if anyone wants to take
it from here I'll be happy to discuss this change and review code.
