### ISSUE TITLE
zfs_admin_snapshot default value inconsistency

### ISSUE THREAD

**Issue by gmelikov** [zfsonlinux/zfs#7835]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| -
Distribution Version	| -
Linux Kernel	| -
Architecture	| -
ZFS Version	|  master
SPL Version	| master

### Describe the problem you're observing

As was found in mailing lists http://list.zfsonlinux.org/pipermail/zfs-discuss/2018-August/032050.html , zfs_admin_snapshot default parameter has been changed in commit
https://github.com/zfsonlinux/zfs/commit/f74b821a6696fef9e9953aae05941e99bf83800e , but documentation is different https://github.com/zfsonlinux/zfs/blob/master/man/man5/zfs-module-parameters.5#L1499 .

@behlendorf what is appropriate default value? `0`?

**Comment by brandonhaberfeld** [comment]
Under what scenario would one want the default of 0?  Snaps would be
default then not be able to be renamed, created, destroyed?  I would have
though the default should be 1 to always allow this?

**Comment by brandonhaberfeld** [comment]
Indeed.

**Comment by behlendorf** [comment]
The documentation needs to be updated.  The intended default value was for this functionality to be enabled.  Even when enabled only NFS clients which mount with `no_root_squash` will be allowed to rename, create, destroy snapshots.

**Comment by GregorKopka** [comment]
@behlendorf could you please elaborate why zfs_admin_snapshot=1 was made the default in https://github.com/zfsonlinux/zfs/commit/f74b821a6696fef9e9953aae05941e99bf83800e when you, imho sensibly, stated before in https://github.com/zfsonlinux/zfs/commit/0500e835af3ea1f3abe27a572f7b2328b4cde386 that
> To prevent configuration mistakes a zfs_admin_snapshot module option was added which disables the mkdir/rmdir/mv functionally.  System administators desiring this functionally must explicitly enable it.

?

Wouldn't that feature not better be controlled through a per-dataset property(*) instead of a system wide setting defaulting to allowing this everywhere?

*) preferably, for my taste, with a default of disabled so an accidental rm that somehow enters the snapdir won't be able to nuke everything en-passant

**Comment by behlendorf** [comment]
> Wouldn't that feature not better be controlled through a per-dataset property(*) instead of a system wide setting defaulting to allowing this everywhere?

@GregorKopka yes it would.  What I failed to include in the description is that this functionality could be re-enabled because permissions are handled through delegations on the server side.  Exporting the filesystem with `no_root_squash` does bypass those checks, but hopefully that's not common configuration.  Since this is rarely used functionality I wouldn't be opposed to globally disabling it again.  At least until we can improve the man page, and verify it does behave as intended.

**Comment by GregorKopka** [comment]
The `no_root_squash` option is required for root filesystems to function correctly, so I guess it's not quite uncommon.

Apart from that, managing snapshots through .zfs/snapshots is _magic_  - and all magic, in my experience, tends to backfire when exposed to unsuspecting practitioners. It should need an informed decision to activate this feature (be it global or hopefully eventually per filesystem) as it silently removes the conception of snapshots being immutable (unless invoking `zfs rename|rollback|destroy`) and thus protected against mistakes with normal shell commands.

**Comment by DeHackEd** [comment]
This was brought up before in #1571 where the "magic" argument (or a variant thereof) was made and won.

**Comment by gmelikov** [comment]
a6214a0 was reverted, needs changes in tests, reopen.
