### ISSUE TITLE
ZFS Encrypted Send

### ISSUE THREAD

**Issue by ElvishJerricco** [zfsonlinux/zfs#7966]
It'd be great if we could send a snapshot in an encrypted form, even if the source snapshot is not encrypted.

The main motivation for this is encrypted, incremental backups of unencrypted datasets. So if you're not using ZFS native encryption, you can still send incremental ZFS snapshots for backup without having to trust the backup target with unencrypted data.

**Comment by ElvishJerricco** [comment]
@jumbi77 Yes, but the transfer will not itself be encrypted. i.e. you have to trust the backup server not to intercept the data as it's piping into `zfs recv`.

**Comment by unshare** [comment]
Isn't `ssh` adequate for this? Like:
```zfs send ... | ssh user@destination zfs receive ...```
Pretty much UNIX-way, user-friendly and doesn't require a separate PKI.

**Comment by gmelikov** [comment]
if I understand correctly, this feature request is about encrypt data in `zfs send` to send data to `zfs recv` as encrypted dataset. So you can use unencrypted dataset without performance penalty and send it anywhere encrypted to backup.

**Comment by gmelikov** [comment]
So, we're already have `zfs send -w, --raw` flags to send encrypted dataset as usual unencrypted one, so the feature request is: implement the reverse of `zfs send -w, --raw` flag.

**Comment by kpande** [comment]
`send -w` pulls raw blocks from disk, not that it decrypts an encrypted dataset.

`recv -o encryption=on` would encrypt unencrypted dataset.

I don't think you will have any luck getting `zfs send` to actively encrypt blocks, it would be a huge mess where you provide a key to use for encryption while it's sending. as it is, `zfs send -D` is in the midst of being deprecated because it is so unmaintainable. this new requested feature would be rather similar.

you are better off using `send -w` and using native encryption locally.

**Comment by gmelikov** [comment]
@kpande oops, you're right about -w flag.

**Comment by ElvishJerricco** [comment]
@gmelikov No, this is about sending an unencrypted data set, but having the produced stream resemble an encrypted dataset sent with `zfs send -w`. @kpande is right that it's more like `-D`, but for encryption. I, for one, intend to use LUKS for encryption, not ZFS, so that Grub can boot the kernel from my ZFS dataset using cryptodisk. Given this, it's impossible for me to send backups via ZFS to an untrusted backup server, since I'll be forced to give the server full access to plaintext backups. The other solution is to fix #7153, but that doesn't look like it's going to happen.
