### ISSUE TITLE
Build failure on  4.9.132-dappersec kernel

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#8101]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Dapper Linux
Distribution Version	| 
Linux Kernel	| 4.9.132-dappersec
Architecture	| x86_64
ZFS Version	| zfs-0.8.0-rc1-11-g9d489ab
SPL Version	| 

### Describe the problem you're observing

Build failure, due to warning from grsecurity patches.

```
/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/zfs/zfs_sysfs.c: In function ‘zfs_kobj_add_attr’:
/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/zfs/zfs_sysfs.c:151:38: error: assignment of member ‘name’ in read-only object
zkobj->zko_attr_list[attr_num].name = attr_name;
^
/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/zfs/zfs_sysfs.c:152:38: error: assignment of member ‘mode’ in read-only object
zkobj->zko_attr_list[attr_num].mode = 0444;
```

### Describe how to reproduce the problem

Build ZFS on Dapper Linux with 4.9.132-dappersec kernel

**Comment by behlendorf** [comment]
Actually this is a duplicate of #7960.

**Comment by UralZima** [comment]
Hi. I am the author if https://github.com/zfsonlinux/zfs/issues/7960 
I can't post to my issue. so I am posting here.
The issue was ended with this commit https://github.com/bunder2015/zfs/commit/85552fbf10f90ea8e025c6191d89523db4ce4dbf 
but is it integrated to master???

I tried to build latest master, and I get: 
*/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/zfs/zfs_sysfs.c: In function ‘zfs_kobj_add_attr’:
*/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/zfs/zfs_sysfs.c:158:38: error: assignment of member ‘name’ in read-only object
*  zkobj->zko_attr_list[attr_num].name = attr_name;
*                                      ^
*/var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/zfs/zfs_sysfs.c:159:38: error: assignment of member ‘mode’ in read-only object
*  zkobj->zko_attr_list[attr_num].mode = 0444;


The line numbers changed, was 151,152 now 158,159. Can we reopen this or mine issue to make sure it is integrated to master?
