### ISSUE TITLE
no way to specify encryptionroot when receiving encrypted dataset

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#8169]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| ~amd64
Linux Kernel	| 4.18.20-gentoo
Architecture	| amd64
ZFS Version	| 0.8.0-rc2_11_gc40a1124
SPL Version	| 0.8.0-rc2_11_gc40a1124

### Describe the problem you're observing
I don't want to send all child dataset, but I do want to link them together using `encryptionroot` property. This seems impossible with current implementation of `zfs send|recv` in 0.8.0-rc2.

### Describe how to reproduce the problem
```
# zfs create -o encryption=on -o keyformat=passphrase rpool/testcryptroot
Enter passphrase:
Re-enter passphrase:
# zfs create rpool/testcryptroot/cryptchild
# zfs get encryptionroot rpool/testcryptroot/cryptchild
NAME                            PROPERTY        VALUE                SOURCE
rpool/testcryptroot/cryptchild  encryptionroot  rpool/testcryptroot  -
# zfs snap -r rpool/testcryptroot@testsnap1
# zfs send -w rpool/testcryptroot@testsnap1 | zfs recv newjack/remotecryptroot
# zfs send -w rpool/testcryptroot/cryptchild@testsnap1 | zfs recv -o encryptionroot=newjack/remotecryptroot newjack/remotecryptroot/cryptchild
cannot receive: invalid property 'encryptionroot'
# zfs send -pw rpool/testcryptroot/cryptchild@testsnap1 | zfs recv newjack/remotecryptroot/cryptchild
# zfs get encryptionroot newjack/remotecryptroot/cryptchild
NAME                                PROPERTY        VALUE                               SOURCE
newjack/remotecryptroot/cryptchild  encryptionroot  newjack/remotecryptroot/cryptchild  -
# zfs destroy -R newjack/remotecryptroot
# zfs send -Rw rpool/testcryptroot@testsnap1 | zfs recv newjack/remotecryptroot
# zfs get encryptionroot newjack/remotecryptroot/cryptchild
NAME                                PROPERTY        VALUE                    SOURCE
newjack/remotecryptroot/cryptchild  encryptionroot  newjack/remotecryptroot  -
# 
```

**Comment by kpande** [comment]
like it says in the man page, without `-w` I can link it just fine, but this is cumbersome as it requires the remote key to be loaded. I don't see how I can reasonably implement a recursive send/recv with encrypted dataset that has the ability to exclude children while simultaneously maintaining the original `encryptionroot` heirarchy on the new pool..

**Comment by kpande** [comment]
```
# zfs send -p rpool/testcryptroot/cryptchild@testsnap1 | zfs recv -x encryption newjack/remotecryptroot/cryptchild
cannot send rpool/testcryptroot/cryptchild@testsnap1: encrypted dataset rpool/testcryptroot/cryptchild may not be sent with properties without the raw flag
cannot receive: failed to read from stream
zfs send -Lec rpool/testcryptroot/cryptchild@testsnap1 | zfs recv -x encryption newjack/remotecryptroot/cryptchild
cannot receive new filesystem stream: inherited key must be loaded
# zfs load-key newjack/remotecryptroot
Enter passphrase for 'newjack/remotecryptroot': 
# zfs send -Lec rpool/testcryptroot/cryptchild@testsnap1 | zfs recv -x encryption newjack/remotecryptroot/cryptchild
# zfs get encryptionroot newjack/remotecryptroot/cryptchild
NAME                                PROPERTY        VALUE                    SOURCE
newjack/remotecryptroot/cryptchild  encryptionroot  newjack/remotecryptroot  -

```

**Comment by kpande** [comment]
@tcaputi can you please comment on the uselessness of `zfs recv` with encrypted datasets?

**Comment by tcaputi** [comment]
@kpande In the future, if you have encryption related issues feel free to @ me. I don't monitor all of the issues that come through the Github page myself, and sometimes issues slip through the cracks and I don't get notified.

Unfortunately, what you are asking for is not possible with the current command line tools. When you do separate raw sends of the parent and child zfs has no way of knowing that the user key for them both is the same. This is because the receive side has no knowledge of the user keys at all. When you send both datasets in a recursive stream (`-R`), the stream tells the receive side how the keys are related, which then calls into some hidden ioctls. These hidden ioctls re-establish the key hierarchy on the receive side. We decided to make these hidden because it is very easy for a user to put themselves in a situation where they related 2 keys that are not actually related, which would cause all kinds of authentication errors.

Recursive streams do not currently have a `--exclude` or `--include` option so you are correct that you can't use `-R` while excluding certain datasets, but this is true with all recursive streams, not just raw ones. As a workaround you could rename the encrypted datasets you wish to exclude on the source so that they are not kept under a different encryption root.

**Comment by kpande** [comment]
I simply can't use `-R` because it requires that every child dataset have a snapshot. So I'll need two encryptionroot on source and enter two keys to unlock at system startup? that seems very silly.

in this case, I am verifying in my replication script that the property is correct. why is it that we can set `-o origin=` on recv commandline, but not `-o encryptionroot=`? I think we'd all be perfectly fine with some authentication errors if it means we can actually USE the backup heirarchy that is created.

**Comment by kpande** [comment]
@tcaputi can we have an environment variable such as `ZFS_RECEIVE_ENCRYPTIONROOT` that is checked to allow overriding the received value at my own peril? similar to the check for `zfs remap` or `zpool status -c` as root.

**Comment by tcaputi** [comment]
`zfs remap` is not a good example since last I heard we are planning on removing that. @behlendorf what do you think should be done here?

**Comment by kpande** [comment]
> Then you just zfs send -R everything under pool/encryptionroot/data_for_backup

nope, send -R won't work without -w because we can't send properties without raw flag. that must be fixed first..

**Comment by tcaputi** [comment]
I meant `zfs send -Rw`. Apologies.

**Comment by kpande** [comment]
well with #8168 it'd be nice to avoid `-w` or even be able to do what the man page says with `-R` and do a `recv -x encryption` on the remote side so we can send unencrypted datasets into encrypted pools and vice versa. I understand that getting the issues with raw send fixed is a priority, since it is my own pool facing the corruption. I was also trying to keep backups going in the meanwhile but I can't do it as is.

out of curiosity, what would happen if I patched ZFS to not prevent me from doing `send -R` without `-w` flag and then pipe it to `zfs recv -x encryption`?

**Comment by tcaputi** [comment]
> out of curiosity, what would happen if I patched ZFS to not prevent me from doing send -R without -w flag and then pipe it to zfs recv -x encryption?

There are a few problems that are all connected:

- `encryption` is technically a "set-once" property like `casesensitivity`. These properties are readonly, except when the dataset is created. We did this so that it wouldn't be possible to have partially encrypted datasets with no way to know what data is and isnt encrypted.  Readonly properties are not sent in the send stream, and therefore neither is the encryption property. Raw sends transfer the property in a separate payload, along with the encryption key data.
- unfortunately, even though `encryption` is a "set-once" property, users still want to think about it in the same way they think about `compression` or `checksum`. `zfs send -p` includes all writable properties in a send stream, including `compression` and `checksum` but not `encryption`. We didn't want people to get themselves in trouble by assuming that `zfs send -p` included the `encryption` property. In order to prevent that we made `zfs send -p` force the user to add `-w` for encrypted datasets.
- `zfs send -R` implies the `-p` flag, meaning it inherits all of these considerations.
- `zfs send -R` also has some nasty implications having to do with receiving multiple datasets in an encryption hierarchy. If we want to allow the user to receive datasets with an arbitrary encryption hierarchy without doing a raw send, we have some very complicated problems to solve on the receive side. Here are some questions we never found great answers to:

1. Do we prompt the user for a passphrase for every encryption root in the stream?
2. If we do prompt for passphrases during the receive how would that work? `stdin` is already being used for the receive file. Do we always force the user to have a file-based key location? If that's true then we're not really preserving the keylocation property from the send stream.
3. What happens if a user mis-enters a password and wants to go back to a previous dataset? We would need to add a "go back" option into the command line utility
4. What do we do with clones? If you send a clone in a recursive stream you may or may not have included the origin in the stream as well. If you did we need to make sure they share the same encryption key. If you did not include it then what do we do?

There are other issues that came up, but by this point I was having a hard time keeping track of them myself and I was the one working on the code. In order to have a clear set of rules, error messages, and warning messages we decided that it would be easier for everyone if we just don't allow properties without doing a raw send.

**Comment by kpande** [comment]
I just assumed that if one wants to send without -w that it would send a typical stream with all of the considerations for a normal send of an unencrypted dataset.

that is, it would be up to the recv side to decide how to encrypt and relate items.

1. send -R wouldn't be sending encryptionroot, or encryption property, as you said.

if I recv into an encryptionroot, it  needs the key loaded. all children should have the same encryptionroot.

example:

I have `rpool/encrypted` on source and want to send it (key loaded) without `-w` to the remote host backup tree (key loaded) `pool/backup` using `send -R` to preserve all heirarchy. each ds should have `pool/backup` as `encryptionroot`.

2. I'm not sure what you mean, which scenario would cause a user to enter a passphrase?

- with `send -R` (without `-w`), recv into encryptionroot, key must already be loaded. we inherit the key.

- with `send -w` we're receiving the keys.

3. same as 2

4. origin must exist locally with the same target encryptionroot, is this not doable?

**Comment by tcaputi** [comment]
> send -R wouldn't be sending encryptionroot, or encryption property, as you said.

If you do a regular send without `-w`, `-p`, `or -R`, that is exactly what it currently does.

> I have rpool/encrypted on source and want to send it (key loaded) without -w to the remote host backup tree (key loaded) pool/backup using send -R to preserve all heirarchy. each ds should have pool/backup as encryptionroot.

I'm confused. You say "preserve all heirarchy" and then `each ds should have pool/backup as encryptionroot". Haven't you lost the encryption root hierarchy then?

> I'm not sure what you mean, which scenario would cause a user to enter a passphrase?
> - with send -R (without -w), recv into encryptionroot, key must already be loaded. we inherit the key.
> - with send -w we're receiving the keys.

`zfs send -w` will always include the encrypted keys, so the user does not need to be prompted. `zfs send -R` (without `-w`) can include a mix of encrypted and unencrypted datasets. For the base receive, if the dataset doesnt inherit from an encryption root we would need to ask for passwords whenever we receive an encrypted dataset.

> origin must exist locally with the same target encryptionroot, is this not doable?

The problem is that you don't necessarily need to send the origin to the other side. It might be possible to figure this out, but there are a lot of cases here (origin included in send stream? origin exists on target? key loaded on target, etc).

**Comment by kpande** [comment]
> If you do a regular send without -w, -p, or -R, that is exactly what it currently does.
however, I need to preserve all other properties. hence wanting to `send -R|p | recv -x encryption`.

> I'm confused. You say "preserve all heirarchy" and then `each ds should have pool/backup as encryptionroot". Haven't you lost the encryption root hierarchy then?
I meant preserve parent-child-clone ordering. I suppose you're right that if someone were sending a tree with `pool/encryptionroot1/root2/root3` would possibly be confused if they expected that to be preserved with `-R|p`, but if you want that preserved, just use `-w`.

**Comment by tcaputi** [comment]
> however, I need to preserve all other properties. hence wanting to send -R|p | recv -x encryption.

I understand.

> I meant preserve parent-child-clone ordering. I suppose you're right that if someone were sending a tree with pool/encryptionroot1/root2/root3 would possibly be confused if they expected that to be preserved with -R|p, but if you want that preserved, just use -w.

We made the opposite choice. At the time, our line of thinking was "people get in trouble for keeping data that really should be encrypted in plaintext", so we wanted to prevent users from making that mistake. Perhaps this is something we can revisit. (@behlendorf)

> we seem to have it figured out for normal send stream, why is encryption so different?

Encryption has a unique kind of "inheritance" that isnt shared by other properties. Basically, `encryptionroot` is inherited through parents like normal properties, but it is also inherited through clones, unlike any other property in zfs. If you are a clone, you must always get youre encryptionroot from your origin regardless of what your parent is.

**Comment by kpande** [comment]
> `zfs send -R` (without `-w`) can include a mix of encrypted and unencrypted datasets. For the base receive, if the dataset doesnt inherit from an encryption root 

you would think it should simply decrypt all data instead of trying to reencrypt with keys it doesn't have.

**Comment by kpande** [comment]
> We made the opposite choice. At the time, our line of thinking was "people get in trouble for keeping data that really should be encrypted in plaintext", so we wanted to prevent users from making that mistake. Perhaps this is something we can revisit. (@behlendorf)

while i appreciate the sentiment, not having some option to override it makes it a huge pain point.

**Comment by behlendorf** [comment]
> I don't see how I can reasonably implement a recursive send/recv with encrypted dataset that has the ability to exclude children while simultaneously maintaining the original encryptionroot hierarchy on the new pool.

@kpande there's a lot here to digest so let me see if I correctly understand the core problem you're trying to solve.  Based on your comment above, my understanding is that for backup purposes you want to be able to recursively send/recv an encrypted pool preserving everything but excluding some datasets.  If that's the case, then I believe the [redacted send/recv feature](https://drive.google.com/file/d/0B4BF1vnv6p0-cHZEeEJaZmNpZVE/view?usp=sharing)  being ported in #7958 could potentially be a reasonable way to handle your use case.  If it's not, then let's figure out why not since a large part of the remaining work is making sure it works well with all the existing features, including encryption.

**Comment by kpande** [comment]
when I use my backups, I have to load a key for every single encrypted filesystem that I've sent using `zfs send -w` without `-R`.

excluding children is not the main issue but a contributing factor, because I do not use `zfs send -R` but rather scripted logic to walk the filesystem tree and use `zfs send -w -p` to recv things into the same layout on a different system.

I cannot use `zfs send -R` because I do not use `zfs snapshot -r` to prevent zero-size snapshots from being generated as they produce unnecessary IO on recv.

Tom says that `zfs send -w | recv -o encryptionroot=foo/bar foo/bar/baz` will cause authentication errors and I understand the issue here, even though an override to recv would be nice, just in case I actually know what I'm doing and want to recreate a layout that should work; `--no-support-required`

so in the meanwhile I wanted to avoid `send -w` and switched to use `send -p` alone, but this doesn't work because `send -p` requires `send -R` for encrypted datasets, and all of the issues that come with it.

**Comment by behlendorf** [comment]
Thanks for concise summary of this problematic use case, I can see what you're driving at here.  I'm definitely open to revisiting some of the restrictions we put in place when initially designing the feature.  What I think we need to move forward is a concrete proposal which addresses the major pain points.  Then we can carefully evaluate it to see how feasible it would be it implement given all of the existing features, and potentially propose some alternatives.

**Comment by kpande** [comment]
ok, I see two classes of issue in this one problem to move forward with

1. that `send -p` requires `send -w`, this should be eliminated and replaced with recv-side restrictions/warnings. I could then use `send -p` to preserve properties and use `recv -x encryption` to preserve `encryptionroot` when the recv side has keys loaded.

2. that `send -w` does not preserve `encryptionroot` without `send -R`, probably a harder problem to solve, but would be nice to have for blind backup implementations.

**Comment by tcaputi** [comment]
Sorry, I'e been a bit busy with some other problems lately.... I will come back around to this before the end of the week.

**Comment by IslandLife** [comment]
I may be missing something but I recently found a simple solution to this same problem. And it requires NO changes or features.
First make snapshot of the parent (not recursive). Send that parent (only) to the backup system  as a full snapshot with the -w flag.  Since this is typically a trivial filesystem this takes little time.   
Load (temporarily) the key for the parent on the backup system. Then for only those filesystems you want to be regularly backed send a (full) snapshot to the backup system. The backup system will encrypt .. but using the key we sent (by -w) earlier.   They will share the encryption root.  If you don't want to throw away snapshots on the backup system made previously then as an alternative you can use send/recv (both on the backup system) to populate under your new backup root.  This might also save you the tedious task of sending a full snapshot from source host to backup host.   The result is the same: the backup filesystems  will all share the encryption root.  Now return to the source host and send incremental snapshots for any or all filesystems with -w.   I admit I haven't  addressed properties in this workaround.  But this workaround would let users get started with  send -w  and preserve encryptionroot hierarchy.

**Comment by kpande** [comment]
you cannot mix raw and non-raw send. this leads to corruption; #8308.

**Comment by zviratko** [comment]
I just hit this recently, good to know I'm not alone. I also can't use R because of exclusions, yet I need to maintain the relationships (it would make management of the keys very awkward in the future for me).

So please, just allow `encryptionroot ` to be set and let the user manage it if he wants. Yes if misconfigured it could cause trouble, so add a check whether this is true (if possible) or warn the user.

**Comment by ptx0** [comment]
@zviratko you can see that in January, @tcaputi said "will come back around to this before the end of the week", and now it's almost 6 months into the year. they would rather it be a useless feature.

**Comment by tcaputi** [comment]
So far, from what I understand, it seems that this issue could be resolved if `zfs send -R` allowed users to exclude datasets. If we were to implement that, would that be sufficient?

**Comment by kpande** [comment]
not really, because many people avoid send -R for other reasons

**Comment by tcaputi** [comment]
Could you provide an example of a reason so that I can get an idea of the types of problems we need to be considering?

**Comment by kpande** [comment]
send -R does not allow separation of the many things it changes about the send stream;

there is no `-r` to make it /only/ recursive (avoid linking clones, everything should be full send, etc)

though you can link clones using `recv -o origin=`, this is the same idea being requested in this ticket, to allow us to manually link `encryptionroot` on recv.

`send -R` doesn't work if a snapshot is missing in the heirarchy. it used to.

@prometheanfire is another consumer of `send|recv` that would probably be able to provide more insight.

**Comment by kpande** [comment]
also send -R with recv -F causes elimination of recv-side snapshots that don't exist, there's no override for this.

**Comment by briefbanane** [comment]
I have a similar use case. I have an encryption root `srcroot` with various sub-volumes and also a different encryption root `remoteroot` which I'd like to use for selective replication of some of those sub-volumes. In particular I'd like to be able to send a single one of those sub-volumes to `remoteroot` preserving its properties, while its encryption root should become `remoteroot`.

It seems that there is no way to do this at the moment (maybe redacted send would do the job, but that seems to be overkill for my usecase). Sending with `-p` forces me to do `-w` and so each sub-volume becomes its own encryption root, making everything very cumbersome.

I would be very happy with suggestion 1. in

> ok, I see two classes of issue in this one problem to move forward with
> 
>     1. that `send -p` requires `send -w`, this should be eliminated and replaced with recv-side restrictions/warnings. I could then use `send -p` to preserve properties and use `recv -x encryption` to preserve `encryptionroot` when the recv side has keys loaded.
> 
>     2. that `send -w` does not preserve `encryptionroot` without `send -R`, probably a harder problem to solve, but would be nice to have for blind backup implementations.

**Comment by Fabian-Gruenbichler** [comment]
> I have a similar use case. I have an encryption root `srcroot` with various sub-volumes and also a different encryption root `remoteroot` which I'd like to use for selective replication of some of those sub-volumes. In particular I'd like to be able to send a single one of those sub-volumes to `remoteroot` preserving its properties, while its encryption root should become `remoteroot`.
> 
> It seems that there is no way to do this at the moment (maybe redacted send would do the job, but that seems to be overkill for my usecase). Sending with `-p` forces me to do `-w` and so each sub-volume becomes its own encryption root, making everything very cumbersome.
> 
> I would be very happy with suggestion 1. in
> 
> > ok, I see two classes of issue in this one problem to move forward with
> > ```
> > 1. that `send -p` requires `send -w`, this should be eliminated and replaced with recv-side restrictions/warnings. I could then use `send -p` to preserve properties and use `recv -x encryption` to preserve `encryptionroot` when the recv side has keys loaded.
> > 
> > 2. that `send -w` does not preserve `encryptionroot` without `send -R`, probably a harder problem to solve, but would be nice to have for blind backup implementations.
> > ```

to expand a bit on this:
we'd either need

1. an additional flag for `zfs send` that causes the "keep snapshots on source and destination in sync" behaviour of `-R`, and drop the requirement for `-p` to require `-w` with encrypted datasets
2. drop the requirement for `-R` to require `-w` with encrypted datasets

I have a rough draft of dropping the linkage between `-p` and `-w` (it does require `recv -x encryption` on the initial send/recv, but that is no problem for us and makes the whole encrypted->potentially unencrypted transition more explicit which is probably a good thing). AFAIU this would not be a problem technically, but needs some usability/"please don't shoot yourself in the foot" considerations. I haven't yet checked how hard it would be to extract the "here is a list of snapshots on the source side that you should keep, drop everything else on the destination" part of `-R`.

dropping the linkage between `-R` and `-w` seems more involved, but maybe the following approach can be made workable:

1. add new flag for `zfs send` to opt into decrypted stream behaviour
2. set new flag/add special properties in stream to allow recv side to detect this
3. skip certain checks (encrypted->unencrypted, unencrypted->encrypted) on recv side
4. add extra checks for clone/origin handling (either prevent such decrypted streams if they would contain clones without their origin, or just altogether, or just by special casing them on the receive side to properly check all requirements and set encryptionroot accordingly)

step 1 prevents accidentally sending encrypted datasets and receiving/persisting them in plain text
steps 2-4 are there to minimize potential for confusion and foot-shooting

in any case, our desired behaviour is the following:
- sync single dataset including all snapshots and properties except encryption
- no matter whether the source is encrypted or not
- no matter whether the destination is encrypted or not, but with encryptionroot inheritance from destination parent

we could work around this by construction a `-o foo=bar` string for all properties set on the source side, and using a plain `zfs send -I ... | zfs receive -x encryption -o foo=bar -o foo2=baz ...`, but that is clearly just a bad work around, and we'd have to keep a list of "properties to not include" current with ZFS changes, etc.pp.. we can handle clones by explicitly passing `-o origin=foobar`, although that is not very high on our list of requirements.

@tcaputi / @behlendorf any input from your sides which approach seems more doable?
@kpande could you re-open this issue, since it is clearly not fixed yet? would either of the above variants solve your problem as well?

**Comment by Fabian-Gruenbichler** [comment]
@tcaputi @kpande ping?

**Comment by tcaputi** [comment]
Unfortunately, I don't really have a good answer here. There isn't really a good way to implement this in the current state of the send / receive code. @ahrens @behlendorf and I have talked about it on several occasions and haven't really come to any great conclusions that don't involve deprecating `zfs send -R` and making something new. I am still thinking about it though and I will see if I can come up with anything.
