### ISSUE TITLE
space is freed slowly

### ISSUE THREAD

**Issue by gustavotonini** [zfsonlinux/zfs#8383]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04.1
Linux Kernel	| 4.15.0-44
Architecture	| x86_64
ZFS Version	| 0.7.5-1ubuntu16.4
SPL Version	| 0.7.5-1ubuntu2

I have a 24TB zfs pool which had many interrupted "zfs recv" operations. The pool freeing property is stuck at 12.7TB for some days already. Is there anything I can do to speed up async_destroy or force zfs to reclaim this space?

**Comment by kpande** [comment]
this looks like a support request which is better serviced by [IRC or the zfs-discuss mailing list](http://list.zfsonlinux.org). if you could please close this until it's confirmed that your issue is indeed a bug and not some configuration related issue like having `dedup=on` or incorrect `ashift` value, as two possible examples.

**Comment by ahrens** [comment]
If it is truly stuck and not making any progress (you could check the exact number of bytes with `zpool get -p`), it may be because there is an indirect block that has a checksum error.  You can set `zfs_free_leak_on_eio` to leak the space under the busted indirect block, and continue freeing everything else.

**Comment by gustavotonini** [comment]
Thanks @ahrens. It is not stuck. It's just slow. I have already set zfs_free_leak_on_eio.
Is there a way to speed it up? We are almost running out of space.

**Comment by ahrens** [comment]
You can increase `zfs_free_min_time_ms`.  You can also monitor how much time is spent freeing and the rate with zfs_dbgmsg.  If you are freeing clones, it can be very slow in some circumstances which is why we implemented https://github.com/openzfs/openzfs/pull/731.

What is your recordsize?  Are you freeing filesystems, snapshots, or clones?  What rate is it being freed at?  What is your hardware (SSD's vs HDD's?)  What rate to you expect it to be freed at?

**Comment by gustavotonini** [comment]
When my pool got full, the "freeing" space began to be released on demand. It seems that the filesystem understands I'm using the pool very intensively and is executing async_destroy with a lower priority.
