### ISSUE TITLE
zfs list -t snapshot takes ages

### ISSUE THREAD

**Issue by Harvie** [zfsonlinux/zfs#8587]
This takes fraction of second:

`zfs list -H -p -s name -o name,creation -t filesystem,volume`

This takes minutes or more:

`zfs list -H -p -s name -o name,creation -t snapshot`

This effectively prevents me from running nagios check that i need to in order to be sure that backup system is working properly...

(I've added `-s name` because someone on stack overflow said it might help, but i don't think it really helps)

Happens on both 0.7.13 and 0.8.0-rc3_126_g5dbf8b4ed

Can it be caused by the fact that the machine is currently running `zfs recv`?

**Comment by jwittlincohen** [comment]
That's likely because you likely have many more snapshots than filesystems or volumes.   With automatic snapshotting, it's pretty common to have hundreds, and perhaps even thousands, of snapshots.  Listing the snapshots requires a lot of random reads to locate the metadata blocks associated with those snapshots.  This will be particularly slow with raidz/2/3 pools backed by HDDs, as you get the IOPS of single drive per vdev.  However, once the blocks are cached in ARC, it should be very fast. 

You would almost certainly benefit from using a special allocation class to store your metadata.  SSDs provide much greater IOPS and you would typically use a mirror for a special allocation, and a mirror can read independently from each drive, doubling your read IOPS.  I am using a special allocation for my backup pool that mostly stores large media files with recordsize=128k or 1M.   The special allocation is using 59G while the main pool has 75T of data.  If you have a smaller recordsize or lots of small files, you'll need more space for the special allocation.  Brian mentioned that 0.3-1% is a good assumption.  If you use a larger SSD, you can also allocate small blocks to the special allocation.  Each dataset has a setting entitled `special_small_blocks` which is the threshold for allocation small blocks to the special allocation.  By default, it is set to 0, meaning only metadata will be placed on the special allocation.  If, for example, you want all blocks 32K and smaller, you would set this value to 32K.

**Comment by DeHackEd** [comment]
The slowdown is caused by loading a lot of supplementary metadata, most notably the space usage of each snapshot and its creation time (`createtxg`) for sorting reasons. To get maximum load times, use `zfs list -t snapshot -o name -s name` to not load any of the above metadata for the snapshots.

Alternatively, 0.8.0 when released will have the option to store metadata on discrete vdevs, almost universally SSDs, which will make fetching this metadata much faster.

Not a bug, working as intended

**Comment by richardelling** [comment]
There is a really cool thing someone invented, its called a database. Very useful for keeping track of things, especially things that don’t change very often, like snapshot creation times. You should check it out. Very useful for managing lots of snapshots and replications.

For example, when you create a snapshot you can give it a policy-based time to live (TTL). Then a simple database lookup comparing current time to TTLs will tell you which snapshots are expired and can be reaped. Of course the TTL can be stored as a user property on the snapshot, but that also suffers from lookup effort.

The really cool kids in the neighborhood are using prometheus exporters to make such info readily available to metrics collectors and that can be scraped into nagios.

**Comment by Harvie** [comment]
> The slowdown is caused by loading a lot of supplementary metadata, most notably the space usage of each snapshot and its creation time (createtxg) for sorting reasons. To get maximum load times, use zfs list -t snapshot -o name -s name to not load any of the above metadata for the snapshots.

I written in initial post, i know about the `-s name` trick, but it doesn't seem to work for me, since i need both: `-o name,creation`.

This seems very odd to me. I understand that keeping track of used space in filesystem is no necessarily trivial task, it always changes and might need some time to be calculated... But creation time? That's literally never changing. You store it once in single place and you just read it. No need to calculate it in any way. So why it does take so long to get creation time of snapshots???

Can't you just store it along with the name of the snapshot? I know that i can put snapshot creation timestamp to the snapshot name and it will be much faster. But i need my script to work with arbitrary snapshot names...

**Comment by rlaager** [comment]
@Harvie Can you name the snapshots based on time, such that you only need the name and not the creation time? That's a pretty common technique.

**Comment by Harvie** [comment]
I can, but i don't want to, because that would make my approach less robust and less dependable.

**Comment by ptx0** [comment]
how so? that is what most people do.

**Comment by Harvie** [comment]
Because that will only work for snapshots created by me or scripts i've written. I want my check script to be able to work with any arbirary snapshoting solution one might have installed.

**Comment by rlaager** [comment]
Most snapshotting scripts work that way (using the name to provide the date), for exactly this reason. Anyway, as noted, loading more metadata takes longer.

**Comment by Harvie** [comment]
> Most snapshotting scripts work that way

But the date format is not consistent across various software and might even change after upgrade.

**Comment by Harvie** [comment]
You know what is extremely weird?? I have some issues with high number of snapshots. I have like 300000 snapshots accidentaly created by znapzend. And i wanted to delete most of them, so i've created list of snapshots i want to remove and then i started to delete them in loop one by one using zfs destroy.

It turned out deletion of one snapshot in my setup takes around 10 seconds, that makes more than 30 days to delete all of them.

And now comes the weird part:

I've instead sent the list of snapshots to following command `xargs -L 1  -P 2048 zfs destroy`, which launches zfs destroy in 2048 parallel processes. It takes like 10-20 minutes of idling without any visible cpu or io resource usage, then follows few seconds of IO load peak (2048 processes showing 100% in iotop) and then 2048 snapshots are destroyed... This way i can manage to destroy all these snapshots in few hours instead of 34 days...

How is this possible? I have 12 CPU cores with HT, but the improvement is still order of magnitude more than i would expect from such CPU parallelism... Seems to me that there's some idling or ineffectivity in snapshot handling...

**Comment by rlaager** [comment]
@Harvie You may be able to delete snapshots faster by passing multiple snapshots (for the same dataset) to `zfs destroy`. You separate them with commas. See the man page. You'll probably still need to chunk them up into batches (for command line length limits and similar, if nothing else).

**Comment by Harvie** [comment]
I have upgraded to ZFS 0.8.1, what can i do to enable metadata caching to improve performance for this stuff?

**Comment by scineram** [comment]
Why didn’t you write channel program for deletion?

**Comment by Harvie** [comment]
@scineram but i don't want to delete all the snapshots. listing is slow even when i have just the snapshots that i need...

**Comment by behlendorf** [comment]
> what can I do to enable metadata caching to improve performance for this stuff?

This is enabled by default in 0.8.1 (see #7668 for details).  After the initial access this type of metadata will be preferentially cached.  If you have a very large number of snapshots you may want to increase the `dbuf_metadata_cache_max_bytes` module option.  You can check the size of the cache in `/proc/spl/kstat/zfs/dbufstats`, the `metadata_cache_*` values describe the cache.  If the cache is too small for your workload, then I'd expect the `metadata_cache_overflow` kstat to be frequently incremented.

**Comment by Harvie** [comment]
@behlendorf do i need zil/cache vdev for this? or it will just cache to ram when i don't have such?

**Comment by Harvie** [comment]
@behlendorf thanks for clarification. BTW is it easy to remove "special" device from pool if i find it does not suit my needs?

**Comment by Harvie** [comment]
> (Note only new metadata will be written there).

Is there way to force rewriting of all metadata in order to move it to newly added special device?

**Comment by Harvie** [comment]
Does it make sense to have "special" device as partition on the same disk as the rest of the pool? Does it  make sense to use similar hardware as rest of the pool does (eg. rotary harddrive)? Or do i need to use something faster (like SSD) to improve performance? What if my pool is already on SSD? Will i benefit from using special device on SSD?

**Comment by GregorKopka** [comment]
> The slowdown is caused by loading a lot of supplementary metadata, most notably the space usage of each snapshot and its creation time (`createtxg`) for sorting reasons. To get maximum load times, use `zfs list -t snapshot -o name -s name` to not load any of the above metadata for the snapshots.

Using `-o name -s name` helps a little but even with it the performance of `zfs list` shows plenty of room for improvement, see https://github.com/zfsonlinux/zfs/issues/8898 for details.

**Comment by Harvie** [comment]
@behlendorf can i remove special device when i don't have any redundancy in my zpool (no mirrors, no raidz, etc...)?

(I don't use such setup for long term reliable storage, but as temporary place to do some one time work...)
