### ISSUE TITLE
Fedora 30 Builds

### ISSUE THREAD

**Issue by yurikoles** [zfsonlinux/zfs#8633]
### System information

Type | Version/Name
 --- | --- 
Distribution Name | Fedora
Distribution Version	| 30
Linux Kernel	| 5.0.7
Architecture	| amd64
ZFS Version	| 0.7.13
SPL Version	| 0.7.13

### Describe the problem you're observing

There is no official ZFS builds for Fedora 30

### Describe how to reproduce the problem
Navigate to https://github.com/zfsonlinux/zfs/wiki/Fedora, search for Fedora 30

Fedora 30 is under Final Freeze from 2019-04-16.

**Comment by mskarbek** [comment]
If you follow strictly kernel compatibility matrix for 0.7.13 then it becomes obvious that there can't be any package for fc30 - 5.0.7 is not supported and there is no 4.19.x kernel package in fc30 repo. So you will have to wait until 0.8.0 release, try to justify earlier 0.7.14 release with updated kernel compatibility or downgrade kernel to the latest package of 4.19 release from fc29.

**Comment by Ringdingcoder** [comment]
However, judging from the "compat" changesets in master, I don't spot anything that would prevent operation on Fedora’s kernel. I think I will give it a try next week on my work PC.

**Comment by k-korn** [comment]
spl/zfs 0.7.13  actually works pretty good at Fedora 29 kernel 5.0.9-200.fc29.x86_64 here.
Chances are pretty high it will work on 5.0.9 at Fedora 30.

**Comment by yurikoles** [comment]
Also works fine fine for me on ArchLinux 5.0.<point> kernels with zfs-dkms from AUR.

**Comment by steve-ttt** [comment]
is there a workaround or anything for this yet?

**Comment by mskarbek** [comment]
> is there a workaround or anything for this yet?

This should help https://gist.github.com/mskarbek/8119c2555c7f56a1a4f0e14462d9382e#file-build_zfs-dkms-sh. The script will build all the necessary packages from the sources using `buildah` and Fedora 30 docker image.

**Comment by Ringdingcoder** [comment]
Thanks, @k-korn. It’s working well on F30 as well.

**Comment by f1yankees** [comment]
HI guys,

I am running two versions of ZOL on F30, one with kernel 5.10 and one with 5.09, both without issue.  I installed these back when I was running F29 from the standard repo and they carried with me when I upgraded.

However, because there is no release for F30, dnf is running into problems every time I do any regular system updates.  Of course we all would love 0.8.0 and are thankful for the dev work, but is there an easy way to bump the repository to F30 in the meantime?

`[f1yankees@thestadium ~]$ sudo dnf update
[sudo] password for f1yankees: 
ZFS on Linux for Fedora 30                                1.4 kB/s | 307  B     00:00    
Failed to synchronize cache for repo 'zfs'
Ignoring repositories: zfs
Last metadata expiration check: 0:18:28 ago on Thu 09 May 2019 10:45:34 AM CDT.
Dependencies resolved.
`

**Comment by behlendorf** [comment]
Now that Fedora 30 is out, I'll go ahead and create a repository for it.

**Comment by behlendorf** [comment]
Thanks for your patience, the Fedora 30 repository is now available.

**Comment by f1yankees** [comment]
Awesome, thank you!!
