### ISSUE TITLE
How to apply native encryption to existing ZFS pool in-place

### ISSUE THREAD

**Issue by whalehub** [zfsonlinux/zfs#8657]
I have a ZFS pool backed by about 56TB of storage and I want to use native encryption on it with the latest release candidate. Are there any instructions or is there any documentation on how to go about upgrading an existing ZFS pool to a natively encrypted one in-place (i.e. without requiring twice the amount of space temporarily)?

Another thing, will natively encrypted ZFS pools created by the latest release candidate be compatible with the stable 0,8 release of ZoL?

Thanks in advance!

**Comment by ptx0** [comment]
this is not a bug report

**Comment by jwittlincohen** [comment]
@whalehub 

Per the man page: 

`Selecting encryption=on when creating a dataset indicates that the default encryption suite will be selected, which is currently aes-256-ccm.  In order to provide consistent data protection, encryption must be specified at dataset creation time and it cannot be changed afterwards.`

**Comment by alek-p** [comment]
Please use the mailing list for questions

**Comment by whalehub** [comment]
@jwittlincohen Thanks!
