### ISSUE TITLE
root on zfs wiki doesn't work

### ISSUE THREAD

**Issue by fvigotti** [zfsonlinux/zfs#8717]
Hi,
I'm talking about https://github.com/zfsonlinux/zfs/wiki/Ubuntu-18.04-Root-on-ZFS
First of all I'm sorry not have time to fix this but I'm also probably not enough expert to be the best person to do that.. anyway someone should really try to follow the wiki step by step and perform that installation..

this has been wrong in so many ways that at the end I've ended up creating something by myself lurking around the web..
anyway switching from the artful installation I've done myself to the bionic installation I've taken a look to see if your guide has changed in some way that could help me..
( i'm installing ubuntu 18.04.2  on cryptfs root and also with zfs root on raid ) 
the only part that I've taken is : NetworkManager
and that is .. *WRONG* , because you setup a network manager but without installing the application that use it... whe you reboot you will have systemd-networkd service instead and so your guide follow up using apt..
but the network is down.. I've ended up setting systemd-networkd instead .. this worked in my setup..
```bash
NIF=$(route | grep '^default' | grep -o '[^ ]*$')
echo "network interface = $NIF" 
cat << EOF > /mnt/etc/systemd/network/20-${NIF}-wired.network
[Match]
Name=${NIF}

[Network]
DHCP=ipv4
EOF
```
other issues I've had with that setup..
```
# zfs create                                 rpool/var/log
# zfs create                                 rpool/var/spool
```
are not empty when my system bootup and everything fails.. because zfs cannot mount them. I've also cleared the mount-dirs of those pools in chroot, rebooted but got the issue again.. even tried to add `overlay` to zfs but other problems show up because seems to fail those dirs on unmounting during reboot.. I've gived up and left those dirs on the root rpool anyway.. 

but again.. my setup is so different from this wiki, and the last time I've used this wiki that was so wrong.. that I wonder if someone have tested it.. maybe a linear step-by-step using qemu or virtualbox with an image in which then everything works could be a better starting point for those who are learning and that can then start from a working setup to a more customized one ...

I'm sorry if I've seemed a bit harsh.. it's just a suggestion thank for your work  :) 

thank you,
Francesco

**Comment by rlaager** [comment]
It's hard to respond to vague complaints that it's completely broken, because that doesn't match my experience at all. People use the guide all the time and it works for them. While I don't test every scenario every time (because this is not automated), I test at least one scenario fully after pretty much every change. I most recently used the guide (albeit with some tweaks) on a real system on Saturday. Also, a colleague of mine, who is brand new to ZFS, successfully used the HOWTO completely unassisted on his own machine a couple of weeks ago.

My typical advice to people who want to do something different is to follow the HOWTO once, exactly as written. That can be in a VM if nothing else. Once you have a working system, it's a lot easier to see how everything fits together, and then you can make changes as desired.

Anyway, on to the direct issues...

The default network configuration in step 4.2 does not use NetworkManager. It uses netplan, with the default renderer, which is systemd-networkd, both of which are installed by default. As noted in the instructions, you do need to adjust `NAME` to match your network card's name. This definitely works.

NetworkManager is mentioned in a "Hint" on step 8.2b. That step is the alternative to use if you want a "full GUI environment". In that case, you install `ubuntu-desktop`. [The ubuntu-desktop package "Recommends" network-manager.](https://packages.ubuntu.com/bionic-updates/ubuntu-desktop) Last I checked, Ubuntu installs Recommends by default. If that has changed, it might be worth adding a note or something, but again, it's only a hint for _if_ you want to use NetworkManager.

If you wish to use NetworkManager, that hint instructs you to change your `01-netcfg.yaml` to delegate everything to NetworkManager. The contents of this file are correct. That matches my `01-netcfg.yaml` on my "daily driver" laptop, which uses NetworkManager.

I am familiar with the issues with `/var/log` and `/var/spool`. The guide has for quite some time (including the entirety of the time that an 18.04 version of the HOWTO has existed) recommended `/var/log` be a legacy mountpoint. This way, it is in `/etc/fstab` and systemd handles mount ordering properly. (This is thankfully no longer necessary on systems with `zfs-mount-generator`, so that will improve by the next Ubuntu LTS release, which should be 20.04.) However, `/var/spool` was only converted to a legacy mountpoint on March 17, so I can see how that could have been a problem for you. The fact that `/var/log` does not unmount on shutdown (at least at the normal step) doesn't actually seem to cause any problems; it also seems unavoidable because systemd/journald holds that open.

**Comment by fvigotti** [comment]
Hi thanks for your reply @rlaager  . yes the configuration is for netplan, but when you reboot netplan seems to be not installed this leave the pc without networking , ( also in my guide I've had to also add wifi card because on notebook there are multiple network card, this should be a `hint` ) another hint is to check which network manager is installed with the debootstrap  and install network configuration for that ( at least in my debootsrtap bionic was systemd-networkd and as I said netplan didn't worked but I'm superbusy and doing that installation to a notebook and doesn't have a fast-setup to tests various steps multiple times ) 

I think that would helped me a lot a stright forward guide to a working env in virtualbox with a lts version which must works to everyone , because It's for a single specific setup , than a more documented guide with possible differences / choices  during setup , but for me at least was very frustrating googling around and spend 3 days before have a bootable system because no guide worked.. ( yeah maybe 99% is correct but for the remanining 1% if you are not expert you don't know what to fix.. ie: a kernel panic during boot because /var/tmp cannot mount...  )

thank you,
Francesco
