### ISSUE TITLE
Update "Debian Stretch Root on ZFS"

### ISSUE THREAD

**Issue by whalehub** [zfsonlinux/zfs#8856]
Could the instructions for installing Debian Stretch on ZFS in the wiki be updated, now that native encryption has landed in ZFS 0.8?

**Comment by Greek64** [comment]
Well the debian package has not landed yet into stretch (or stretch-backports).
The debian package always trails behind the actual release by a bit. You can see the progress [here](https://tracker.debian.org/pkg/zfs-linux)

Unlike previous zfs versions which were merged to `unstable`, than `testing`, and then `*-backports`, the 0.8 version went straight to `experimental`. Goes to show how unstable the 0.8 version still is.

I doubt the wiki will be updated to suggest installing from source/experimental. (Due to it being a wiki for the layman)
Any brave souls wanting to go that way will probably have to do so on their own...

**Comment by whalehub** [comment]
@Greek64 Fair point, I'll recreate this issue once ZFS 0.8 has landed in the stretch-backports repository.
