### ISSUE TITLE
"Incompatible hardware" ?!?

### ISSUE THREAD

**Issue by gregfr** [zfsonlinux/zfs#9201]
Greetings

I've been using ZFS on Debian/Proxmox for years ; I use it for snapshoting, backups, fast migration... I'm managing several clustered servers at the same hosting provider (OVH), all installed with the provider's installation process.

Recently I registered a new server ; the ZFS installation option is gone, and the tech support says it's because of "incompatible hardware". Of course they cannot say more.

Does anyone has any idea why they say that, and if there is a real potential problem using ZFS on theses machines?

Thanks in advance

**Comment by ronnyegner** [comment]
32 Bit only Hardware? 
Only 4 GB Memory?

**Comment by freqlabs** [comment]
Machine configured with a hardware RAID card?

**Comment by GregorKopka** [comment]
> Recently I registered a new server ; the ZFS installation option is gone, and the tech support says it's because of "incompatible hardware". **Of course they cannot say more.**

When your current hosting provider can't tell why a configuration option in his own interface dosn't show.... switch to a competent hosting provider.

Apart from that: not a zfsonlinux issue but (at best) mailing list material.

**Comment by gregfr** [comment]
Thanks 
@ronnyegner @freqlabs E3-1225v2 - 32GB - SoftRaid 2x2To
@GregorKopka I tend to agree with you, but I've been hosting my servers there for years and migration would be tedious

So I wonder if I take any risk keeping this infrastructure? I cannot see why such (decently powerfull) hardware would be incompatible with ZFS...

**Comment by GregorKopka** [comment]
Possibly they disable ZFS because their hosting product is configured to do software RAID (as 'SoftRaid 2x2To' hints), which really wouln't be a good idea when using ZFS.

Don't use 'normal' RAID arrays (software or hardware dosn't matter, both can't deal with errors that are not accompanied by hard IO errors (simply from having no clue which part of the data is intact and what part is garbage delivered by faulty hardware) to back ZFS pools, always give ZFS the disks and create the redundancy on the pool level.

Maybe look if you have an option to deactivate 'SoftRaid', possibly ZFS will then show up as an option in the configuration. If it does: the support staff of your provider should have known that.

**Comment by devZer0** [comment]
i think this is not a valid zfsonlinux bugticket as it cannot be up to the zfsonlinux community to give a guess what's the provider's strategy to decide about zfs hardware incompatibility. 

go ask your hosting provider again.

**Comment by freqlabs** [comment]
For more information about hardware recommendations for ZFS you may refer to http://open-zfs.org/wiki/Hardware
