### ISSUE TITLE
Why is my issue ignored?

### ISSUE THREAD

**Issue by maniac0s** [zfsonlinux/zfs#9328]
I posted this here 19 days ago yet got no helping answers to this issue. 

https://github.com/zfsonlinux/zfs/issues/9222

**Comment by mschilli87** [comment]
@maniac0s: There are 900 open issues right now. How many people do you think are working on this? And given that your issue is not even something that anyone can easily reproduce locally to test and try solutions, who should anyone be able to help you. If you get no answer after such a long time my best guess is that nobody knows a solution based on the information provided by you. Surely there was no secret zfsonlinux meating where it was decided to ignore this issue as a personal attack against you. :wink:

**Comment by devZer0** [comment]
this is outdated, there has been a lot of help yesterday. please close
