### ISSUE TITLE
Signature checking and bitrot detection by boot

### ISSUE THREAD

**Issue by inf3rno** [zfsonlinux/zfs#9376]
Sorry for the questions, but something is not clear for me and I got no answer on the mailing list. This might be a feature request too, it depends on the missing info. As far as I understand ZFS (especially ZFS with native encryption) loads something before the OS kernel. So the boot process is something like `UEFI -> boot loader -> {something} -> OS kernel -> init system -> services` . I can check the signature of the boot loader with secure boot and afaik. it is possible to do almost anything after the kernel is loaded, so checking the init system and the services should not be a problem. What I want to do is checking the signature of that "something" before the kernel loads (if it is possible to sign it) and after giving the password when it tries to load the OS kernel I want to check the kernel too and do a scrub too. So it will make sure that the OS is not hacked before loading it and the data is not corrupted. As far as I understand all components must be checked by the previous component to make sure that everything is fine that we load. Increased booting time is not an issue, because the whole thing will run on a server that will be booted extremely rarely. I tried to ask the same question on several forums and Q&A sites, but maybe 5% of the answerers understands the problem and nobody knows how to do it, so probably this is not even supported currently by ZFS. Am I right?

**Comment by ghfields** [comment]
I was unable to find the mailing list question, therefore any of the responses you may have received already.

The most basic boot chain would involve UEFI stub:
'UEFI -> kernel -> Initrd /w ZFS module -> system root'

But all MBR and some UEFI systems shoehorn a bootloader in there also:
'UEFI/MBR -> bootloader -> kernel -> Initrd /w ZFS module -> system root'

Some bootloaders have primitive ZFS support builtin so it can all kernel/initrd files that reside on compatible ZFS pools.  In all cases, the zfs root filesystem is indicated on the kernel commandline when initiated by the bootloader or the UEFI kernel call.

So... there is no {something} other than the kernel commandline.

There are projects like [TrustedGRUB2](https://github.com/Rohde-Schwarz/TrustedGRUB2) that have attempted to use the TPM to measure and record boot parameters.  I have not personally tried to use this with ZFS.  Additionally, this particular project utilizes the increasingly less common TPM 1.2 standard.  TPM 2.0 is available, but its development is in great flux (just see this [CHANGELOG](https://github.com/tpm2-software/tpm2-tools/blob/master/CHANGELOG.md) from 3 weeks ago).

In any case, ZFS doesn't have to provide anything additional to make these secure boot initiatives function.  It is a matter of secure boot implementations taking the time to support ZFS.

**Comment by inf3rno** [comment]
@ghfields 
I sent it to the `zfs-discuss@list.zfsonlinux.org` on 25th September. Not sure what went wrong, I did not get any replies.

> So... there is no {something} other than the kernel commandline.

Do we have 2 kernels then? Maybe I misunderstood, but for example by LUKS I think the Linux kernel is encrypted too, so without knowing the password it is not possible to load the kernel. But maybe I am wrong. I thought ZFS native encryption works similarly. I guess I am missing something about how boot really works. :S 

> There are projects like TrustedGRUB2 that have attempted to use the TPM to measure and record boot parameters.

Afaik. I just need to sign the GRUB I want to use with my private key and add my public key to the UEFI. I did not do it yet thought, but in theory that's all, I don't need to wait for any project or use Microsoft signed boot loaders, etc...

**Comment by AttilaFueloep** [comment]
@inf3rno 
Grubs zfs support is quite limited so it is not able to read from pools with newer features like encryption, Therefore you need to create a separate `/boot` partition with a filesystem grub supports. From there grub will read its `grub.cfg`, the kernel and initramfs. 

So you have two options. 

- You can use [grubs gpg signatures support](https://www.gnu.org/software/grub/manual/grub/html_node/Using-digital-signatures.html#Using-digital-signatures) to ensure the integrity of the kernel and initramfs on the boot partition. This is good for bit rot detection but not for tamper resistance, since an attacker still can change `grub.cfg`.

- or you can go for a LUKS encrypted `/boot` partition. Grub will `cryptsetup open` and mount the `/boot` partition and read the kernel and initramfs from there. This is tamper resistant since both involved components are either signed or encrypted (see below). For bit rot detection you can use grubs digital signatures inside `/boot`.

I took the second approach as follows. Create a custom grub image (grub-mkimage(1))  which includes all needed grub modules and a simple `grub.cfg`. Sign this EFI binary with your secure boot key and place it into the EFI system partition. The baked in `grub.cfg` just mounts `/boot`, sets `$root` and loads `grub.cfg` from the `/boot` partition.

I can give more details if there's interest.

**Comment by inf3rno** [comment]
@AttilaFueloep I would go with ZFS native encrytion.  I don't insist on using grub if you can recommend a better boot loader I can solve the same tamper resistant encryption with.

**Comment by AttilaFueloep** [comment]
> I would go with ZFS native encrytion. I don't insist on using grub if you can recommend a better boot loader I can solve the same tamper resistant encryption with.

There is none I know of, hence the grub juggling I'm doing.

**Comment by inf3rno** [comment]
@AttilaFueloep That's bad news. :S  I'll look around, hope dies last...

**Comment by inf3rno** [comment]
@AttilaFueloep 
I left some time to digest this. I am not sure I understand the boot process properly. From what I understand only the bootloader is loaded before the kernel and nothing else. So if the bootloader does not support the encryption that was used, then the kernel cannot be unencrypted. That's why it works only with LUKS, because GRUB supports that, while it does not support ZFS native encryption. If I am correct, then a relative tamper proof solution would be writing the kernel to a pendrive with a read-only switch, so it cannot be modified after it was written if the attacker does not have physical access to the computer. The only drawback compared to the LUKS and encrypted kernel that still they can check the kernel version and lookup vulnerabilities for it, but I can live with that. I hope I understand now properly how it is done. If not, please correct me!

**Comment by AttilaFueloep** [comment]
I don't think that this is the proper place to discuss Linux boot details, so I keep my reply short. For details you can read e.g. [this](https://docs.fedoraproject.org/en-US/Fedora/19/html/Installation_Guide/s1-boot-init-shutdown-process.html).

> That's why it works only with LUKS, because GRUB supports that, while it does not support ZFS native encryption.

Right.

> Yet another option to encrypt the kernel with LUKS and use ZFS native encryption on the rest.

That's the solution I was describing. Since all files needed for booting reside under `/boot` you can create a small LUKS encrypted partition, mounted at `/boot` while the root file system is on an encrypted ZFS dataset. A search engine like google should bring up enough recipes.

**Comment by inf3rno** [comment]
@AttilaFueloep Okay, thanks for the link, I'll look into this and hopefully start the server this week.
