### ISSUE TITLE
ZFS option to add raw disks without creating GPT partitions

### ISSUE THREAD

**Issue by stevecs** [zfsonlinux/zfs#94]
I see in the change logs that this was added a while ago (2009-11-02) that when adding a raw volume to a pool zfs will create a GPT partition on the disk and actually add the partition not the raw volume as the user requested, this is also started at ~1049KB offset:

Disk /dev/sdq: 251GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt

Number  Start   End    Size    File system  Name  Flags
 1      1049kB  251GB  251GB                zfs
 9      251GB   251GB  8389kB

This poses problems when the volumes presented to ZFS are not physical drives but are luns due to alignment issues.   Also this creates more of a management issue when dealing with many devices as seen in large deployments when trying to remove/replace a device with one of a larger size (having to now not only replace all the devices in the vdev but also modify the gpt tables).  

If possible would like an option to NOT create a partition table but to use the device as presented.

**Comment by rlaager** [comment]
This is essentially the opposite of #1162. I'm mentioning it to link them together.

**Comment by Nable80** [comment]
Dear developers, is there any hope to (finally) get such an option in the official package? I wanted to use ZOL on relatively large JBOD and a dozen of completely senseless EFI partitions isn't the thing that I want to see in my system. I know that there are higher priority problems... but could you tell me what is currently holding this one?

**Comment by jumbi77** [comment]
@Nable80 there is currently an open PR for creating pools w/o gpt: https://github.com/zfsonlinux/zfs/pull/6277

**Comment by koitsu** [comment]
This whole matter was solved properly in Illumos recently.  GPT primary/backup headers and EFI partitions are only created if the -B flag is given to zpool create: https://www.illumos.org/issues/7446

Not auto-GPT'ing and auto-partitioning by default is fully justified in the original ZFS Best Practises Guide, section "Storage Pools": https://web.archive.org/web/20150207105847/http://www.solarisinternals.com/wiki/index.php/ZFS_Best_Practices_Guide#Storage_Pools

This same mentality and thought process is applied in ZFS on FreeBSD, as denoted here (don't miss the last 2 lines of the commit message): https://svnweb.freebsd.org/base?view=revision&revision=331395

Bootable devices/pools obviously need GPT and/or EFI (or alternately MBR, though achieving 4K alignment may be complicated/a problem with MBR).  However, this behaviour being default for zpool create (i.e. for all pools, bootable or not) on Linux is a bummer.  But I'm biased coming from both a FreeBSD and Solaris background.

**Comment by koitsu** [comment]
@ehem Couple things I can think of.  This is more of a brain dump than "here's where the problem lies":

1. With GPT, there is a primary table (LBAs 1 through 33) and backup table (LBAs {last-LBA-of-disk-minus-33} to {last-LBA}).  Your `dd` only clears the primary.  I don't know about Linux, but FreeBSD will actually tell you (in console/dmesg) if the primary is corrupt and will fall back to using data from the backup table at the end of the physical disk.  As such, when working with GPT, you have to clear out both tables.  LBA 0 is usually the PMBR.

2. On Linux (at least back in the 2.6.x days; not sure about today), the kernel kept an internal cache of what the MBR/GPT contained, all the way down to partitions.  If you manipulated the regions directly on the disk, you had to inform the kernel via a special `ioctl()` to get the kernel to "re-taste" (re-read) MBR/GPT areas.  The only way I know how to do this on Linux is to use `fdisk` followed by the `w` command, but as said before, there may be a newer command today that can do it.

**Comment by ehem** [comment]
> @ehem Couple things I can think of. This is more of a brain dump than "here's where the problem lies":
> 1. With GPT, there is a primary table (LBAs 1 through 33) and backup table (LBAs {last-LBA-of-disk-minus-33} to {last-LBA}). Your dd only clears the primary. I don't know about Linux, but FreeBSD will actually tell you (in console/dmesg) if the primary is corrupt and will fall back to using data from the backup table at the end of the physical disk. As such, when working with GPT, you have to clear out both tables. LBA 0 is usually the PMBR.

Indeed.  Didn't bring it up, but I'd ended up writing a small program to explicitly whack all traces of both.  There was **no** possibility of a GPT or other such format on the device beforehand.  Also note the error message ```
/dev/xvdk does not contain an EFI label but it may contain partition
information in the MBR.
```  I don't know whether `zpool create` will look for a backup GPT, but `zpool` was clearly indicating **no** GPT ("EFI label") was present.  At which point the `dd` would of nuked all traces of any such construct which had been present.  That error is **garbage**.


> 2. On Linux (at least back in the 2.6.x days; not sure about today), the kernel kept an internal cache of what the MBR/GPT contained, all the way down to partitions. If you manipulated the regions directly on the disk, you had to inform the kernel via a special ioctl() to get the kernel to "re-taste" (re-read) MBR/GPT areas. The only way I know how to do this on Linux is to use fdisk followed by the w command, but as said before, there may be a newer command today that can do it.

Indeed, you're referring to `ioctl(fd, BLKRRPART)`.  I don't recall the exact sequence of actions I took prior to the above, but the kernel was unaware of any disk slicing before the commands were run (either I'd included the ioctl() during the erase, or perhaps restarted the VM).

As near as I can tell `zpool create`'s logic is roughly:
```
if(gpt_is_present(passed_in_dev)) {
  /* some action or error message I didn't reproduce */
  return EDIE_FULLDEVICE;
} else if(!isdigit(passed_in_devname[strlen(passed_in_devname)-1]) {
  errormsg("%s does not contain an EFI label but it may contain partition\ninformation in the MBR.\n", passed_in_devname);
  return EDIE_FULLDEVICE;
}
```
This isn't 100% accurate of course.  Notably the above wouldn't produce the error message for /dev/xvdk0, whereas `zpool create` gave the error for that situation (no error for /dev/xvdk1 though).  I hope the code checks for GPTs inside devices named "/dev/xvdk1" (yes, many setups GPTs inside slices _will_ be found and sub-devices created), but haven't tried this since I was trying to eliminate all traces of any such constructs.

This is a really awful misfeature here.  One should include slack for slightly differing device sizes, but this is ridiculous.  Using whole media devices as filesystems has been a long-time tradition, I highly dislike having to spend a fair bit of time to get a tool to do the basic operation I desire without adding useless garbage overhead on top.

**Comment by ttyS4** [comment]
I am experimenting using loopback devices to hide the device from ZoL's zpool create command.
So with just a single device pool it is:

```
losetup /dev/loop2 /dev/vdb
zpool create mypool /dev/loop2
zpool export mypool
losetup -d /dev/loop2
zpool import
zpool import mypool
```

as an end result I have my pool directly on the unpartitioned device.

**Comment by llamafilm** [comment]
I came across this issue while searching for something similar.  In the first post there is discussion about the "bug" of 1049 kB offset.  I think this happens simply because `parted` uses base 10 instead of base 2 for its calculation:
512B * 2048 sector offset = 1048576 B = 1049 kB = 1024 KiB

**Comment by rlaager** [comment]
I'm closing this in favor of #3452, which has more notes about implementation.

**Comment by pepa65** [comment]
> For the sanity of the next person to run into this breakage, I did manage a workaround:
> 
> ```
> # cp -l /dev/xvdk /dev/xvdk1
> # zpool create test -f /dev/xvdk1
> ```
> 
> Yes, that really was successful at bypassing this insanity.

Does this link need to be recreated after every reboot, or can it safely disappear once the zpool has been created?

**Comment by ehem** [comment]
> Does this link need to be recreated after every reboot, or can it safely disappear once the zpool has been created?
> 
> EDIT: It seems that exporting the pool, removing the link and then importing it is enough.

Yup.  The link gets stored in `/etc/zfs/zpool.cache` (eww! writable cache file in /etc!) and it simply needs to be updated.  Doing anything other than taking the whole of the device provided on the command-line is a **bug**.

I'm sure someone wanted a GPT and had to add it later, but 1000x that many people want it to take the whole device specified.  There is no way to know _actual_ the desires of the person running the command.  Whereas it is _easy_ to add a GPT beforehand if desired, but quite difficult with this **bug** to prevent it from being added.

**Comment by pepa65** [comment]
```
cp -l /dev/sdx /dev/sdx1
zpool create pool /dev/sdx1
zpool export pool
rm /dev/sdx1
zpool import pool
```

This should be in the README or some other very prominent place!! The `-l` flag for `cp` is important. Softlinking does not do the job..!

**Comment by walterav1984** [comment]
Thanks for posting this workaround, since large 20TB (Seagate EXOS X20) GPT formatted disks on MacPro 3,1 seems to stall/freeze the firmware during boot (boot picker will time out finding nothing or will shutdown after x minutes). 
First I thought this was a ZFS only issue, but no matter if the disk is formatted as GPT with just HFS+ in MacOS Montery self or in linux with gdisk (without partition) or with gnome disk-utility it will hang using the onboard 6-port intel esb2 sata2 controller. Maybe other certain exotic Uefi 64 machines are also affected?

Formatting these large disks in a "layout/partition less" fashion with ZFS or (even btrfs) makes boot behavior normal again on MacPro 3,1 boot picker instantly shows up and let you boot any OS again.

Also using this hard link tip works  for `/dev/disk/by-id/ata-STxxxxxx-part1` using the `-part1` addition.

Do I understand correctly @pepa65 that this kind of partition-less formatting introduces issue(s) when [replacing a bad disk](https://github.com/openzfs/zfs/issues/14174) in a broken pool?

**Comment by koitsu** [comment]
> Do I understand correctly @pepa65 that this kind of partition-less formatting introduces issue(s) when [replacing a bad disk](https://github.com/openzfs/zfs/issues/14174) in a broken pool?

No.  That issue relates to someone having a FreeBSD-created ZFS pool which was then migrated/attached to a Linux system where OpenZFS decided to auto-create partitions and it resulted in loss of the last 8MByte of their disk(s).  If the pool was quite full (utilisation-wise), this probably caused them data loss, and for a bootable pool almost certainly destroyed the (preexisting) backup GPT header.  That ticket is a good example of why this auto-partitioning stuff should never have been created in the first place (and I said something to this effect [5 years ago](https://github.com/openzfs/zfs/issues/94#issuecomment-375568933)).  I am a proponent of auto-partitioning being added as a flag to OpenZFS for Linux, but by default it should not be doing this.

To add a bit more detail: FreeBSD does not do any kind auto-partitioning on ZFS disk members.  If you want to use partitions as pool members instead of raw disks, you are expected to do the partitioning yourself with gpart(8).  If you want to have bootable ZFS pool, you are expected to [do the partitioning and bootloader setup yourself](https://wiki.freebsd.org/RootOnZFS/GPTZFSBoot) (though if installing the OS from scratch, I believe the installer can now do this for you).  Solaris behaves identically in this regard.  It is only OpenZFS on Linux that behaves unlike the rest.

**Comment by pepa65** [comment]
@walterav1984 What @koitsu said..!
The argument was about slightly unequally sized disks in raid, and if you then put a slightly smaller one in, it doesn't quite fit in size-wise..? But if you had made the earlier ones a bit smaller, it would not be a problem..! In any case, ZFS is intelligent enough to not let that lead to any casualties.

**Comment by koitsu** [comment]
> @walterav1984 What @koitsu said..! The argument was about slightly unequally sized disks in raid, and if you then put a slightly smaller one in, it doesn't quite fit in size-wise..? But if you had made the earlier ones a bit smaller, it would not be a problem..! In any case, ZFS is intelligent enough to not let that lead to any casualties.

Your understanding of a vdev is mostly correct: you must replace a bad disk with one of equal or larger size (i.e. LBA count).  This is how ZFS is designed and isn't OpenZFS on Linux specific.  In fact, even HBA RAID controllers operate this same way.  If you want to use partitions to try and alleviate this, go right ahead, but it's wasted effort (IMO) since you cannot reliably predict "how small" a replacement disk in the future might be.  The general advice we sysadmins will give you is: buy spare disks (of the exact same model/part number) at the time you buy disks for your pool, or go with a vendor (ex. Dell) that can guarantee replacement disks in the future -- even from other vendors -- have the same LBA count.

**Comment by walterav1984** [comment]
Thanks for the input, will try to break the pool and replace and test disks to see if it really doesn't introduce a replacement disk with forced partitioning and less space or that I have to replace a disk with a hardlink `-part1` before keeping this as a solution.

**Comment by ehem** [comment]
A similar approach is to use a loop device and set the loop device to be 10% smaller than the disk.  That is usually enough to compensate for manufacturer variances and as suggested by [@ttyS4](https://github.com/openzfs/zfs/issues/94#issuecomment-427472111) this also takes care of the GPT issue.  This **requires** autoexpand to be disabled.

At this point I've concluded the OpenZFS project is unresponsive and am now asking Linux distributions to patch out this bug.  Hopefully having every Linux distribution patch out the bug might get the message across.

**Comment by Nable80** [comment]
10% is a huge amount even on a 1TB disk. And actually I didn't come across any variance between vendors during the past 10 years or even more. Yes, SSD and HDD have significantly different typical sizes (e.g. 960 vs 1000GB) but all ``X`` TB HDD that I used had the same LBA count regardless of the vendor.

**Comment by ehem** [comment]
@Nable80 this is off the topic of OpenZFS adding GPTs being a Bad Idea.

The number wasn't meant to be exact, you simply shave a little bit off every disk to avoid future pain.  Indeed this is rather less of an issue with there now being only 2.5 disk vendors, but when there were 10 it was a significant issue.  Another alternative is to simply plan on incrementally growing your array and get larger storage each time (flash cannot yet compete with disks for shear space, but the only constant is change).

**Comment by tonyhutter** [comment]
> At this point I've concluded the OpenZFS project is unresponsive and am now asking Linux distributions to patch out this bug. Hopefully having every Linux distribution patch out the bug might get the message across.

@ehem I believe the OpenZFS project is largely in favor of raw disk support.  We just need someone to implement the feature:

_"We would just need someone will to put together a PR for this which passes the CI, and then some folks to review and test it."_
https://github.com/openzfs/zfs/issues/11408#issuecomment-1015896508

**Comment by ehem** [comment]
> @ehem I believe the OpenZFS project is largely in favor of raw disk support. We just need someone to implement the feature:

You're looking to have it done _your_ way (you have to add an extra flag), instead of the way everyone expects it to work (operating similar to `mkfs`).  This is a major difference since the former requires significant familiarity with the source, whereas the latter simply involves ripping the thing out.

I'm left extremely confused as to what possible useful purpose this bug serves?  People will make mistakes and choose poor configurations. Doing highly unexpected things causes far greater damage as it will be unable to prevent people from shooting themselves in the foot. and breaks things for people who expected the program to follow well-established behaviors.

Seriously, what useful purpose does this provide?  I haven't the faintest clue, unless it lets someone pad their resume.

**Comment by pepa65** [comment]
If it would be way easier to just rip it out (and most likely it is!) then I would be greatly in favour of doing that. If people want partitioning, there are standard recommended tools for that, that are very easy to use, as precise as you would want to. It would simplify the code base of OpenZFS, there would be nothing lost.
