### ISSUE TITLE
cannot upgrade zpool

### ISSUE THREAD

**Issue by flixman** [zfsonlinux/zfs#9471]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Debian
Distribution Version	| 10.1
Linux Kernel	|  4.19.0-5
Architecture	|  amd64
ZFS Version	| 0.8.2-2~bpo10+1
SPL Version	| 0.8.2-2~bpo10+1

### Describe the problem you're observing
Zpool status, after updating using using buster-backports, reports the zpools can be upgraded. When I do that, I get the following error:

    cannot set property for 'hddpool': invalid argument for this pool operation

### Describe how to reproduce the problem
apt install zfs-dkms/buster-backports
reboot
zpool upgrade \<pool\>

**Comment by AndCycle** [comment]
did you upgrade your zfsutils-linux?

**Comment by flixman** [comment]
Indeed. These are the application I have upgraded:
apt list --installed | grep bpo
libnvpair1linux/buster-backports,now 0.8.2-2~bpo10+1 amd64 [installed,upgradable to: 0.8.2-2]
libuutil1linux/buster-backports,now 0.8.2-2~bpo10+1 amd64 [installed,upgradable to: 0.8.2-2]
libzfs2linux/buster-backports,now 0.8.2-2~bpo10+1 amd64 [installed,upgradable to: 0.8.2-2]
libzpool2linux/buster-backports,now 0.8.2-2~bpo10+1 amd64 [installed,upgradable to: 0.8.2-2]
phpldapadmin/now 1.2.2-6.1~bpo9+1 all [installed,local]
zfs-dkms/buster-backports,now 0.8.2-2~bpo10+1 all [installed,upgradable to: 0.8.2-2]
zfsutils-linux/buster-backports,now 0.8.2-2~bpo10+1 amd64 [installed,upgradable to: 0.8.2-2]

I even re-installed all of them, yesterday, and no changes.

**Comment by Rayzilt** [comment]
Can you double check that the kernel module and userland utils are the same version?

Running 'zpool version' and 'modinfo zfs' should give you the info.

**Comment by flixman** [comment]
This one is weird. I used to have installed zfs-0.7.12-2, which I upgraded to 0.8.2-2. This is what I get:
**# zpool version**
zfs-0.8.2-2~bpo10+1
zfs-kmod-0.7.12-2+deb10u1

**# uname -a**
Linux kngnt 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**modinfo zfs | head**
version:        0.8.2-2~bpo10+1
srcversion:     29C160FF878154256C93164
vermagic:       4.19.0-5-amd64 SMP mod_unload modversions 
root@kngnt:~# modinfo /lib/modules/4.19.0-5-amd64/updates/dkms/zfs.ko | head
filename:       /lib/modules/4.19.0-5-amd64/updates/dkms/zfs.ko
version:        0.8.2-2~bpo10+1
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
alias:          devname:zfs
alias:          char-major-10-249
srcversion:     29C160FF878154256C93164
depends:        spl,znvpair,icp,zlua,zunicode,zcommon,zavl

Why does zfs-kmod-0.7.12-2+deb10u1 appear on zpool version?

**Comment by filip-paczynski** [comment]
Hi, according to the man page for `zpool version`:
```
zpool version - Displays the software version of the zpool userland utility and the zfs kernel module.
```
So, I guess that first version is userland and the second is kernel module. Looks like userland (`zfs` command) is newer than zfs kernel module. This is probably due to the fact that zfs-kmod package is still present and OS prefers kmod over dkms if both are present.   
I guess previously Debian used kmod method, and now i uses dkms. This also kind of explains why the kmod was kept - there was nothing to upgrade it with.

I suggest to do the following:
1. umount all datasets
1. export the pool
1. `rmmod zfs spl`
1. `apt remove` all zfs-related packages of 0.7.x version 
1. make sure that `modinfo` for zfs,spl,znvpair,icp,zlua,zunicode,zcommon,zavl reports 0.8.2 version  
   do not use paths here, just module names, to find out what will actually get used
1. reboot (just to be safe)
1. re-import the pool

Note: I have not tested this method, however I've built Debian packages for my systems and I've run into this kind of issue at some point, IIRC.

**Comment by flixman** [comment]
@filip-paczynski you might be right: I have observed that both zfs-zed and zfs-initramfs were kept at 0.7.x version. I have upgraded zfs-initramfs successfully, but after the reboot I am getting the situation I am describing in [issue #9473](https://github.com/zfsonlinux/zfs/issues/9473). I guess I will have to fix that first before coming back to this one :-/.

**Comment by filip-paczynski** [comment]
@flixman If you have these packages @0.7.x then it's not ZFS issue, it's Debian issue (sth to do with packaging, I detest being involved in packaging systems, so I can't help).

I'm yet to try ZFS on root, but as far as I understand, there are some limitations regarding zpool features for boot/root pools - for example checksum algorithms `edonr` and `skein` not being supported on zfs-on-root, according to manpage for `zpool-features` - which might mean that if You've got these `enabled`, You won't boot.   

Personally in my experience with ZFS (since 0.6.x) I've learned to only enable the features I need (no "global" `zpool upgrade <poolname>`). You can selectively enable features  using `zpool set feature@feature_name=enabled pool_name`

I guess any problem with multiple versions will also cause problems on booting, it basically falls into 'undefined behaviour' category (which means it won't work).

**Comment by flixman** [comment]
I understand that, but if I have been booting flawlessly until now, I think I should be still booting fine after the upgrade. And yes, definitely I will contact the Debian package maintainer to notify them about those missing dependencies

**Comment by filip-paczynski** [comment]
Ok, I'd be glad if You could share the solution here, since it might prove helpful for anyone using Debian packaging & zfs-on-root.

**Comment by flixman** [comment]
absolutely... as soon as I get a solution xD !

**Comment by filip-paczynski** [comment]
>  I think I should be still booting fine after the upgrade. 

Not if You have conflicting versions. 'invalid relocation target' sounds like version incompatibility (but my linker knowledge is very dusty).   
I think you'd have to first solve the version problems, then re-install zfs-initramfs (to force initrd.img rebuild etc).

**Comment by flixman** [comment]
@filip-paczynski you were right, there was an issue with the module stored on the initramfs. However, it was strange: generating the initramfs triggered another bug related to some simbol not being available for the spl/zfs module. The only way I have found to get it fixed has been to upgrade my kernel to the one provided with buster backports... so I'm gonna call it a day.
