### ISSUE TITLE
Fedora 31 Repository Package Missing

### ISSUE THREAD

**Issue by turkstra** [zfsonlinux/zfs#9526]
Fedora 31 was officially released today. In order to upgrade, a new zfs-release rpm/repository must be created.

**Comment by JustDevZero** [comment]
Interested also on this, thanks in advance!

**Comment by rgessner** [comment]
+1 for a f31 repo

**Comment by tonyhutter** [comment]
We're working on it.  There's some problems with our version of buildbot working under F31 that I'm trying to run down...

**Comment by martin236** [comment]
Just updated and have same ZFS repo missing ....

**Comment by edgan** [comment]
I did a rebuild of the Fedora 30 src.rpm in a lxd Fedora 31 container without issue. Then I upgraded to Fedora 31 from Fedora 30. I installed the rebuilt rpms and they just work for me.

**Comment by ivantomica** [comment]
From what I understood @tonyhutter issue is with adding builder to the http://build.zfsonlinux.org/builders where packages are being built. I'm not seeing new Fedora 31 builder there so perhaps it is not public? 

Somebody perhaps know where to look into the particular issue with the build?

**Comment by rgessner** [comment]
I have changed the `zfs.repo` file so that it is fixed at 30 and does not use the `$releasever` variable. Works without problems here.

**Comment by MartenBE** [comment]
> I have changed the `zfs.repo` file so that it is fixed at 30 and does not use the `$releasever` variable. Works without problems here.

I am currently awaiting to a fix to install zfs on a newly installed F31 server which doesn't have zfs installed yet. Is the workaround mentioned by @rgessner a good solution, or will it have some unwanted side effects?

**Comment by mskarbek** [comment]
> I am currently awaiting to a fix to install zfs on a newly installed F31 server which doesn't have zfs installed yet. Is the workaround mentioned by @rgessner a good solution, or will it have some unwanted side effects?

That will work fine, you will just have to remember to update the repo file when propper repository for fc31 will be created.

**Comment by tonyhutter** [comment]
@ivantomica yes we're currently testing the F31 packages on an internal buildbot server, since it's not quite ready for prime time yet.  There's some extra dependencies we need to add to the F31 builders to get them to pass some of the test suite tests.  There were also some issues with our version of buildbot needing python 2.  The test suite is currently running on our internal buildbot server, and I'm just working though the list of F31 test failures (https://gist.githubusercontent.com/tonyhutter/13ce6f1574c5875a7f557b68f56088a8/raw/534a978836639f8d105cf2cc91bc616b07a8623a/gistfile1.txt)

**Comment by tonyhutter** [comment]
Fedora 31 0.8.2 packages are now available:
http://download.zfsonlinux.org/fedora/zfs-release.fc31.noarch.rpm

Thanks all for your patience!

**Comment by JerryPenguin** [comment]
Thx for your hard work
