### ISSUE TITLE
zloop fails within one hour

### ISSUE THREAD

**Issue by AttilaFueloep** [zfsonlinux/zfs#9658]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Arch
Distribution Version	|  rolling
Linux Kernel	| 5.3.13
Architecture	| amd64
ZFS Version	|  master@42a826e
SPL Version	| 

### Describe the problem you're observing

With current master zloop runs in the build directory fail within one hour.  The last run produced three crashes in one hour. I've seen different failures on multiple runs. Is anybody else seeing this?

### Describe how to reproduce the problem
Build current master and run zloop inside the build directory: `scripts/zloop.sh`

**Comment by behlendorf** [comment]
The `zloop.sh` test case is a torture test designed to randomly exercise the code in a way that uncovers otherwise had to find bugs and races.  Most of these scenarios are completely unrealistic for any real production system.  Regardless, we of course want to understand and resolve any crashes.  We do see `ztest` fail occasionally in the CI for a couple known reasons which are not dangerous but do still need to be resolved.

**Comment by AttilaFueloep** [comment]
> The `zloop.sh` test case is a torture test designed to randomly exercise the code in a way that uncovers otherwise had to find bugs and races. Most of these scenarios are completely unrealistic for any real production system.

Yes, and it has done a great job in uncovering bugs in my crypto code by exercising code paths rarely hit in normal operations. That's why I ask. Currently I can't be sure that the failures are introduced by my code.

**Comment by Ornias1993** [comment]
@AttilaFueloep You will never be, you need to actually trace the issues thrown.
We had the same problem with ZSTD and it took/takes quite some work to figure it out. sometimes...

It's not a trace-the-bug test, more of a general stability test.

**Comment by AttilaFueloep** [comment]
Yes, I know and of course I do. Years ago I had `zloop` runs on OmniOS surviving > 12h regularly. Things have changed in between, so I have to adjust my expectations, I guess.

**Comment by Ornias1993** [comment]
With more code comes more bugs and possible black swan scenarios... :(

**Comment by behlendorf** [comment]
The goal is to be running `ztest` 24/7 without issue.  However, that's been a challange with all the on going feature development.  If someone's looking to contribute systematically investigating and fixing each `ztest` failure would be time well spent.

**Comment by AttilaFueloep** [comment]
Brian, thanks for clarifying things. I appreciate the 24/7 goal and understand the challenge with the ton of new features that went in. Actually this is was I meant with "things have changed". Debugging `ztest` is a challenge as well, I didn't manage to run it in a meaningful way under `gdb`, so I refrain for now.

**Comment by Ornias1993** [comment]
@AttilaFueloep
If you look at how ztest is run on buildbot, it would be possible to run it 24 hours and just look at all the failed ztests outputs individually and verify if they are related to your changes. As it segregates all failed ztests from the main zloop output.

**Comment by AttilaFueloep** [comment]
@Ornias1993 
> verify if they are related to your changes

Depending on your use case, that's the challenging part. I work on the aes-gcm implementation (soon to come, hold your breath ;-) where an encryption bug can lead to an error in a completely different area of ZFS.

Speaking of ZTS, is there an easy way to force all tests to create aes-gcm encrypted datasets? It's my impression that the different encryption modes (ccm/gcm) aren't covered well in ZTS.

**Comment by Ornias1993** [comment]
> Speaking of ZTS, is there an easy way to force all tests to create aes-gcm encrypted datasets? It's my impression that the different encryption modes (ccm/gcm) aren't covered well in ZTS.

I actually had a similair issue with compression. There where so many different files referencing different compression algorithms, that about half of them didn't cover all algorithms anymore... Possibly because contributors forgot to add algorithms.

Easiest fix was to centralise all references to compression algorithms to one place in #9645

That is: If currently compression modes are a variable in those tests.

If they are not:
A lot of tests use `rand-prop $prop $values`
For those you could do something like I did in #9645 and just copy and paste it to all places where possible/relevant and improve coverage a bit.

**Comment by AttilaFueloep** [comment]
Interesting, let me have a look. It could take me a while though.

**Comment by Ornias1993** [comment]
@AttilaFueloep I know, actually I think more property tests needs to be based around the properties.shlib file... but that would take some work indeed... :(
