### ISSUE TITLE
ZFS version 0.8.2 not available on Ubuntu 18.04.03 LTS 

### ISSUE THREAD

**Issue by ajl5t** [zfsonlinux/zfs#9678]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04.03
Linux Kernel	| 4.15.0-55-generic
Architecture	| x86_64
ZFS Version	| 0.7.5-1ubuntu16.6
SPL Version	| 0.7.5-1ubuntu1

### Describe the problem you're observing
ZFS version 0.8.2 does not appear to be available for download for Ubuntu 18.04 LTS (Bionic) on the main Ubuntu archive repository.

### Describe how to reproduce the problem

Using rmadison to check available software versions, indicates that Ubuntu 18.04 LTS (Bionic) only has 0.7.5 as the available version:
```
zfsutils-linux | 0.6.5.6-0ubuntu8  | xenial/universe | amd64, arm64, armhf, i386, powerpc, ppc64el, s390x
zfsutils-linux | 0.6.5.6-0ubuntu28 | xenial-updates  | amd64, arm64, armhf, i386, powerpc, ppc64el, s390x
zfsutils-linux | 0.7.5-1ubuntu15   | bionic          | amd64, arm64, armhf, i386, ppc64el, s390x
zfsutils-linux | 0.7.5-1ubuntu16.6 | bionic-updates  | amd64, arm64, armhf, i386, ppc64el, s390x
zfsutils-linux | 0.7.12-1ubuntu5   | disco           | amd64, arm64, armhf, i386, ppc64el, s390x
zfsutils-linux | 0.8.1-1ubuntu14   | eoan            | amd64, arm64, armhf, i386, ppc64el, s390x
zfsutils-linux | 0.8.1-1ubuntu14.2 | eoan-updates    | amd64, arm64, armhf, i386, ppc64el, s390x
zfsutils-linux | 0.8.2-3ubuntu2    | focal           | amd64, arm64, armhf, ppc64el, s390x
```
Are there plans to make ZFS version 0.8.2 available for Ubuntu 18.04 LTS (Bionic)?  If not, is there a recommended approach for upgrading an LTS version of Ubuntu 18.04 to ZFS version 0.8.2?  If building from source code is the only option - will that mess with kernel upgrades going forward?  Ideally, I would like to avoid having to build from source code here.

Many thanks in advance for any guidance on this.

**Comment by ghfields** [comment]
Canonical is maintains those Ubuntu repos, not the ZFS on Linux project.  Additionally, while Ubuntu will backport certain security and stability patches, feature upgrades are done at the time of new releases.

There is a caveat though.... ZFS is built into the kernel.  Ubuntu releases HWE kernels for LTS releases.  The 18.04.4 kernel should be the same kernel as 19.10.  If you install 18.04.4 directly or use apt to upgrade to the HWE kernel, you should have ZOL 0.8.1.  [It is scheduled to be available February 6th, 2020](https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule).  They will need to be careful to make sure that the userland "zfsutils" package is also upgraded only for those HWE kernel users.

That all being said.... There are a couple of 3rd party PPAs available that people use to install 0.8.2 on 18.04.  I am hesitant promote an particular PPA since ZOL nor I are involved in the compiling of those binaries.

**Comment by Ornias1993** [comment]
Besides the great comment of @ghfields this is not a github issue.
Please close this and submit this to the mailinglist instead, as described in the contribution guidelines.

**Comment by ajl5t** [comment]
Understood.  Thanks for the detail.

**Comment by Ornias1993** [comment]
No problem, it should be actually more clear what is and is not a github issue honestly...
Hope Ubuntu gets 0.8.* released quickly for you! :)
