### ISSUE TITLE
Remove Linux only features that blocks importing on FreeBSD

### ISSUE THREAD

**Issue by iio7** [zfsonlinux/zfs#9889]
I needed to migrate a pool from a Linux system to a FreeBSD system. I exported the pool on the Linux system and wanted to import it on FreeBSD 12.1, only to discover "Linux only" settings that are active by default, which blocks any import on FreeBSD!

```
status: The pool can only be accessed in read-only mode on this system. It
        cannot be accessed in read-write mode because it uses the following
        feature(s) not supported on this system:
        org.zfsonlinux:userobj_accounting (User/Group object accounting.)
action: The pool cannot be imported in read-write mode. Import the pool with
        "-o readonly=on", access the pool on a system that supports the
        required feature(s), or recreate the pool from backup.
```

The pool was created by default settings, hence the above is enabled by default.

The pool is filled with data and I cannot copy the data to another pool. This is so undescribable frustrating!

**Comment by misterbigstuff** [comment]
it doesn't look like you've asked a question or posited any actual problem with ZFS, can you elaborate what you want to do? it looks like "remove Linux only features" is your goal, but you could have just not enabled Linux only features when designing the pool.

**Comment by ghfields** [comment]
None of the OpenZFS variants, by default, create pools with limited featuresets with the purpose of cross compatibility.  In fact, variants even have issues with pools being created on newer versions not being usable with older versions.  So you can see, there is a chronology at play also.  

Those who want to ultimate compatibility (within reason) would do a `zpool create -o version=28 ...` but more reasonably, would do a `zpool create -d` followed by `-o feature@...` to explicitly select the features that you wish to enable.  

There is talk about incorporating feature presets that could help. These would be a collection of all features present only on all the most up-to-date variants of a user selected calendar year.  Even with this work done, this would not be a default, therefore you would still be in the situation you are in currently.

For reference, this table shows the current state of feature flag interoperability. http://build.zfsonlinux.org/zfs-features.html  Since you have removed the provided issue template, I don't know which version of ZOL you are running.

Now for a solution... You still have options.  You can: 
1. Mount the pool as read-only on FreeBSD (as the message states)
2. Create a compatible pool on the Linux machine, transfer the data, then move the disks to FreeBSD
3. Use the network to move data between Linux and FreeBSD via ssh/netcat and zfs send/receive or rsync.
4. Wait until FreeBSD gains the feature flags needed

Currently, ZFSonLinux code is being rewritten so it can be built on FreeBSD.  There is not stated timeline for that project, so might not be a reasonable path.

**Comment by iio7** [comment]
> Those who want to ultimate compatibility (within reason) would do a zpool create -o version=28 ... but more reasonably, would do a zpool create -d followed by -o feature@... to explicitly select the features that you wish to enable.

Why don't you make it so that the options that are shared between all OS's are those that are set by default, and then those that aren't needs to be set explicitly? That would make a whole lot more sense.

I'm not dealing with an issue where FreeBSD is behind LInux, I'm dealing with an issue of "Linux on options set by default", which just doesn't run on FreeBSD or Illuminos.

It's the default part that's the problem.

**Comment by ghfields** [comment]
I understand the request is compatibility by default.  This is difficult due to the temporal nature of compatibility.  Enabled vs. Available flags would perpetually changing, likely to cause its own confusion.  Additionally, interoperability with another variant is important to a minority of the userbase (I happen to be one of them).  Since interoperability is a semi-advanced feature, I would argue that we continue to provide the features and performance by default, and expect advanced users to understand and dial back to maintain their needed level of interoperability.

Features are added regularly to all OpenZFS variants.  That's why the proposed compatibility featureset discussion requires the user to specify a compatibility year.

In this case, that FreeBSD 12.1 is behind.  This is not a Linux only feature.  This just happened to be developed first within the ZOL codebase.  It is useful and available on other non-Linux variants.  [This spreadsheet](https://docs.google.com/spreadsheets/d/1CFapSYxA5QRFYy5k6ge3FutU7zbAWbaeGN2nKVXgxCI/edit#gid=0) show other improvements also missing from FreeBSD.  It may be useful to monitor and support the implementations on the FreeBSD side.

Keep an eye on the ZOF project.  https://github.com/zfsonfreebsd/ZoF .  I am not up-to-date on their progress, except seeing plenty of PRs being generated to support the integration into ZOL (which will eventually become the official Open ZFS codebase, and may also make this situation occur less).  

FWIW, the [ZOF man page](https://github.com/zfsonfreebsd/ZoF/blob/projects/zfsbsd/man/man5/zpool-features.5) include `org.zfsonlinux:userobj_accounting`.  I cannot attest to its functionality.

**Comment by iio7** [comment]
Thank you very much for taking the time to clarify this. I also looked further into the project and I was lacking information about how the development actually took place.

**Comment by ghfields** [comment]
Happy to help.  It's all complicated.  Some of us have had the luxury of watching this ZFS grow to help us understand the exchange of ideas.  

If you are interested, please stay close to the project(s).  There's lots of contributions that can be made by people other than filesystem savvy C programmers.

**Comment by iio7** [comment]
Thank you, I will!
